from typing import Any

HAS_GOOGLE_AUTH: bool
HAS_OAUTH2CLIENT: bool

def default_credentials(): ...
def with_scopes(credentials: Any, scopes: Any): ...
def authorized_http(credentials: Any): ...
def refresh_credentials(credentials: Any): ...
def apply_credentials(credentials: Any, headers: Any): ...
def is_valid(credentials: Any): ...
def get_credentials_from_http(http: Any): ...
