from oauth2client import client as client
from typing import Any, Optional

DEVSHELL_ENV: str

class Error(Exception): ...
class CommunicationError(Error): ...
class NoDevshellServer(Error): ...

CREDENTIAL_INFO_REQUEST_JSON: str

class CredentialInfoResponse:
    user_email: Any = ...
    project_id: Any = ...
    access_token: Any = ...
    expires_in: Any = ...
    def __init__(self, json_string: Any) -> None: ...

class DevshellCredentials(client.GoogleCredentials):
    def __init__(self, user_agent: Optional[Any] = ...) -> None: ...
    @property
    def user_email(self): ...
    @property
    def project_id(self): ...
    @classmethod
    def from_json(cls, json_data: Any) -> None: ...
    @property
    def serialization_data(self) -> None: ...
