from oauth2client import client as client
from typing import Any, Optional

logger: Any

class AppAssertionCredentials(client.AssertionCredentials):
    service_account_email: Any = ...
    scopes: Any = ...
    invalid: bool = ...
    def __init__(self, email: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def from_json(cls, json_data: Any) -> None: ...
    def to_json(self) -> None: ...
    def retrieve_scopes(self, http: Any): ...
    @property
    def serialization_data(self) -> None: ...
    def create_scoped_required(self): ...
    def sign_blob(self, blob: Any) -> None: ...
