from oauth2client import client as client
from typing import Any

class Storage(client.Storage):
    def __init__(self, service_name: Any, user_name: Any) -> None: ...
    def locked_get(self): ...
    def locked_put(self, credentials: Any) -> None: ...
    def locked_delete(self) -> None: ...
