import sqlalchemy.types
from oauth2client import client as client
from typing import Any

class CredentialsType(sqlalchemy.types.PickleType): ...

class Storage(client.Storage):
    session: Any = ...
    model_class: Any = ...
    key_name: Any = ...
    key_value: Any = ...
    property_name: Any = ...
    def __init__(self, session: Any, model_class: Any, key_name: Any, key_value: Any, property_name: Any) -> None: ...
    def locked_get(self): ...
    def locked_put(self, credentials: Any) -> None: ...
    def locked_delete(self) -> None: ...
