import google.api_core.client_options as ClientOptions
from .transports.base import CloudTasksTransport
from google.api_core import gapic_v1, retry as retries
from google.auth import credentials
from google.cloud.tasks_v2.services.cloud_tasks import pagers
from google.cloud.tasks_v2.types import cloudtasks, queue, queue as gct_queue, task, task as gct_task
from google.iam.v1 import iam_policy_pb2 as iam_policy, policy_pb2 as policy
from google.protobuf import field_mask_pb2 as field_mask
from typing import Any, Sequence, Tuple, Union

class CloudTasksAsyncClient:
    DEFAULT_ENDPOINT: Any = ...
    DEFAULT_MTLS_ENDPOINT: Any = ...
    queue_path: Any = ...
    parse_queue_path: Any = ...
    task_path: Any = ...
    parse_task_path: Any = ...
    common_billing_account_path: Any = ...
    parse_common_billing_account_path: Any = ...
    common_folder_path: Any = ...
    parse_common_folder_path: Any = ...
    common_organization_path: Any = ...
    parse_common_organization_path: Any = ...
    common_project_path: Any = ...
    parse_common_project_path: Any = ...
    common_location_path: Any = ...
    parse_common_location_path: Any = ...
    from_service_account_file: Any = ...
    from_service_account_json: Any = ...
    @property
    def transport(self) -> CloudTasksTransport: ...
    get_transport_class: Any = ...
    def __init__(self, *, credentials: credentials.Credentials=..., transport: Union[str, CloudTasksTransport]=..., client_options: ClientOptions=..., client_info: gapic_v1.client_info.ClientInfo=...) -> None: ...
    async def list_queues(self, request: cloudtasks.ListQueuesRequest=..., *, parent: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> pagers.ListQueuesAsyncPager: ...
    async def get_queue(self, request: cloudtasks.GetQueueRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> queue.Queue: ...
    async def create_queue(self, request: cloudtasks.CreateQueueRequest=..., *, parent: str=..., queue: gct_queue.Queue=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> gct_queue.Queue: ...
    async def update_queue(self, request: cloudtasks.UpdateQueueRequest=..., *, queue: gct_queue.Queue=..., update_mask: field_mask.FieldMask=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> gct_queue.Queue: ...
    async def delete_queue(self, request: cloudtasks.DeleteQueueRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> None: ...
    async def purge_queue(self, request: cloudtasks.PurgeQueueRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> queue.Queue: ...
    async def pause_queue(self, request: cloudtasks.PauseQueueRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> queue.Queue: ...
    async def resume_queue(self, request: cloudtasks.ResumeQueueRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> queue.Queue: ...
    async def get_iam_policy(self, request: iam_policy.GetIamPolicyRequest=..., *, resource: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> policy.Policy: ...
    async def set_iam_policy(self, request: iam_policy.SetIamPolicyRequest=..., *, resource: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> policy.Policy: ...
    async def test_iam_permissions(self, request: iam_policy.TestIamPermissionsRequest=..., *, resource: str=..., permissions: Sequence[str]=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> iam_policy.TestIamPermissionsResponse: ...
    async def list_tasks(self, request: cloudtasks.ListTasksRequest=..., *, parent: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> pagers.ListTasksAsyncPager: ...
    async def get_task(self, request: cloudtasks.GetTaskRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> task.Task: ...
    async def create_task(self, request: cloudtasks.CreateTaskRequest=..., *, parent: str=..., task: gct_task.Task=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> gct_task.Task: ...
    async def delete_task(self, request: cloudtasks.DeleteTaskRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> None: ...
    async def run_task(self, request: cloudtasks.RunTaskRequest=..., *, name: str=..., retry: retries.Retry=..., timeout: float=..., metadata: Sequence[Tuple[str, str]]=...) -> task.Task: ...
