from oauth2client import clientsecrets as clientsecrets, transport as transport
from oauth2client.contrib import dictionary_storage as dictionary_storage
from oauth2client.contrib.django_util import storage as storage
from typing import Any, Optional

GOOGLE_OAUTH2_DEFAULT_SCOPES: Any
GOOGLE_OAUTH2_REQUEST_ATTRIBUTE: str

class OAuth2Settings:
    scopes: Any = ...
    request_prefix: Any = ...
    def __init__(self, settings_instance: Any) -> None: ...

oauth2_settings: Any

def get_storage(request: Any): ...

class UserOAuth2:
    request: Any = ...
    return_url: Any = ...
    def __init__(self, request: Any, scopes: Optional[Any] = ..., return_url: Optional[Any] = ...) -> None: ...
    def get_authorize_redirect(self): ...
    def has_credentials(self): ...
    @property
    def scopes(self): ...
    @property
    def credentials(self): ...
    @property
    def http(self): ...
