// This file is auto-generated by @hey-api/openapi-ts
import { queryOptions } from '@tanstack/react-query';

import { client as _heyApiClient } from '../client.gen';
import {
  type Options,
  getDistrictAdvancement,
  getDistrictAwards,
  getDistrictDcmpHistory,
  getDistrictEvents,
  getDistrictEventsKeys,
  getDistrictEventsSimple,
  getDistrictHistory,
  getDistrictInsights,
  getDistrictRankings,
  getDistrictTeams,
  getDistrictTeamsKeys,
  getDistrictTeamsSimple,
  getDistrictsByYear,
  getEvent,
  getEventAdvancementPoints,
  getEventAlliances,
  getEventAwards,
  getEventCoprs,
  getEventDistrictPoints,
  getEventInsights,
  getEventMatchTimeseries,
  getEventMatches,
  getEventMatchesKeys,
  getEventMatchesSimple,
  getEventOprs,
  getEventPredictions,
  getEventRankings,
  getEventSimple,
  getEventTeamMedia,
  getEventTeams,
  getEventTeamsKeys,
  getEventTeamsSimple,
  getEventTeamsStatuses,
  getEventsByYear,
  getEventsByYearKeys,
  getEventsByYearSimple,
  getInsightsLeaderboardsYear,
  getInsightsNotablesYear,
  getMatch,
  getMatchSimple,
  getMatchTimeseries,
  getMatchZebra,
  getRegionalAdvancement,
  getRegionalChampsPoolPoints,
  getRegionalRankings,
  getSearchIndex,
  getStatus,
  getTeam,
  getTeamAwards,
  getTeamAwardsByYear,
  getTeamDistricts,
  getTeamEventAwards,
  getTeamEventMatches,
  getTeamEventMatchesKeys,
  getTeamEventMatchesSimple,
  getTeamEventStatus,
  getTeamEvents,
  getTeamEventsByYear,
  getTeamEventsByYearKeys,
  getTeamEventsByYearSimple,
  getTeamEventsKeys,
  getTeamEventsSimple,
  getTeamEventsStatusesByYear,
  getTeamHistory,
  getTeamMatchesByYear,
  getTeamMatchesByYearKeys,
  getTeamMatchesByYearSimple,
  getTeamMediaByTag,
  getTeamMediaByTagYear,
  getTeamMediaByYear,
  getTeamRobots,
  getTeamSimple,
  getTeamSocialMedia,
  getTeamYearsParticipated,
  getTeams,
  getTeamsByYear,
  getTeamsByYearKeys,
  getTeamsByYearSimple,
  getTeamsKeys,
  getTeamsSimple,
} from '../sdk.gen';
import type {
  GetDistrictAdvancementData,
  GetDistrictAwardsData,
  GetDistrictDcmpHistoryData,
  GetDistrictEventsData,
  GetDistrictEventsKeysData,
  GetDistrictEventsSimpleData,
  GetDistrictHistoryData,
  GetDistrictInsightsData,
  GetDistrictRankingsData,
  GetDistrictTeamsData,
  GetDistrictTeamsKeysData,
  GetDistrictTeamsSimpleData,
  GetDistrictsByYearData,
  GetEventAdvancementPointsData,
  GetEventAlliancesData,
  GetEventAwardsData,
  GetEventCoprsData,
  GetEventData,
  GetEventDistrictPointsData,
  GetEventInsightsData,
  GetEventMatchTimeseriesData,
  GetEventMatchesData,
  GetEventMatchesKeysData,
  GetEventMatchesSimpleData,
  GetEventOprsData,
  GetEventPredictionsData,
  GetEventRankingsData,
  GetEventSimpleData,
  GetEventTeamMediaData,
  GetEventTeamsData,
  GetEventTeamsKeysData,
  GetEventTeamsSimpleData,
  GetEventTeamsStatusesData,
  GetEventsByYearData,
  GetEventsByYearKeysData,
  GetEventsByYearSimpleData,
  GetInsightsLeaderboardsYearData,
  GetInsightsNotablesYearData,
  GetMatchData,
  GetMatchSimpleData,
  GetMatchTimeseriesData,
  GetMatchZebraData,
  GetRegionalAdvancementData,
  GetRegionalChampsPoolPointsData,
  GetRegionalRankingsData,
  GetSearchIndexData,
  GetStatusData,
  GetTeamAwardsByYearData,
  GetTeamAwardsData,
  GetTeamData,
  GetTeamDistrictsData,
  GetTeamEventAwardsData,
  GetTeamEventMatchesData,
  GetTeamEventMatchesKeysData,
  GetTeamEventMatchesSimpleData,
  GetTeamEventStatusData,
  GetTeamEventsByYearData,
  GetTeamEventsByYearKeysData,
  GetTeamEventsByYearSimpleData,
  GetTeamEventsData,
  GetTeamEventsKeysData,
  GetTeamEventsSimpleData,
  GetTeamEventsStatusesByYearData,
  GetTeamHistoryData,
  GetTeamMatchesByYearData,
  GetTeamMatchesByYearKeysData,
  GetTeamMatchesByYearSimpleData,
  GetTeamMediaByTagData,
  GetTeamMediaByTagYearData,
  GetTeamMediaByYearData,
  GetTeamRobotsData,
  GetTeamSimpleData,
  GetTeamSocialMediaData,
  GetTeamYearsParticipatedData,
  GetTeamsByYearData,
  GetTeamsByYearKeysData,
  GetTeamsByYearSimpleData,
  GetTeamsData,
  GetTeamsKeysData,
  GetTeamsSimpleData,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getStatusQueryKey = (options?: Options<GetStatusData>) =>
  createQueryKey('getStatus', options);

/**
 * Returns API status, and TBA status information.
 */
export const getStatusOptions = (options?: Options<GetStatusData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStatusQueryKey(options),
  });
};

export const getTeamsQueryKey = (options: Options<GetTeamsData>) =>
  createQueryKey('getTeams', options);

/**
 * Gets a list of `Team` objects, paginated in groups of 500.
 */
export const getTeamsOptions = (options: Options<GetTeamsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeams({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamsQueryKey(options),
  });
};

export const getTeamsSimpleQueryKey = (options: Options<GetTeamsSimpleData>) =>
  createQueryKey('getTeamsSimple', options);

/**
 * Gets a list of short form `Team_Simple` objects, paginated in groups of 500.
 */
export const getTeamsSimpleOptions = (options: Options<GetTeamsSimpleData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamsSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamsSimpleQueryKey(options),
  });
};

export const getTeamsKeysQueryKey = (options: Options<GetTeamsKeysData>) =>
  createQueryKey('getTeamsKeys', options);

/**
 * Gets a list of Team keys, paginated in groups of 500. (Note, each page will not have 500 teams, but will include the teams within that range of 500.)
 */
export const getTeamsKeysOptions = (options: Options<GetTeamsKeysData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamsKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamsKeysQueryKey(options),
  });
};

export const getTeamsByYearQueryKey = (options: Options<GetTeamsByYearData>) =>
  createQueryKey('getTeamsByYear', options);

/**
 * Gets a list of `Team` objects that competed in the given year, paginated in groups of 500.
 */
export const getTeamsByYearOptions = (options: Options<GetTeamsByYearData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamsByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamsByYearQueryKey(options),
  });
};

export const getTeamsByYearSimpleQueryKey = (
  options: Options<GetTeamsByYearSimpleData>,
) => createQueryKey('getTeamsByYearSimple', options);

/**
 * Gets a list of short form `Team_Simple` objects that competed in the given year, paginated in groups of 500.
 */
export const getTeamsByYearSimpleOptions = (
  options: Options<GetTeamsByYearSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamsByYearSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamsByYearSimpleQueryKey(options),
  });
};

export const getTeamsByYearKeysQueryKey = (
  options: Options<GetTeamsByYearKeysData>,
) => createQueryKey('getTeamsByYearKeys', options);

/**
 * Gets a list Team Keys that competed in the given year, paginated in groups of 500.
 */
export const getTeamsByYearKeysOptions = (
  options: Options<GetTeamsByYearKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamsByYearKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamsByYearKeysQueryKey(options),
  });
};

export const getTeamQueryKey = (options: Options<GetTeamData>) =>
  createQueryKey('getTeam', options);

/**
 * Gets a `Team` object for the team referenced by the given key.
 */
export const getTeamOptions = (options: Options<GetTeamData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeam({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamQueryKey(options),
  });
};

export const getTeamSimpleQueryKey = (options: Options<GetTeamSimpleData>) =>
  createQueryKey('getTeamSimple', options);

/**
 * Gets a `Team_Simple` object for the team referenced by the given key.
 */
export const getTeamSimpleOptions = (options: Options<GetTeamSimpleData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamSimpleQueryKey(options),
  });
};

export const getTeamHistoryQueryKey = (options: Options<GetTeamHistoryData>) =>
  createQueryKey('getTeamHistory', options);

/**
 * Gets the history for the team referenced by the given key, including their events and awards.
 */
export const getTeamHistoryOptions = (options: Options<GetTeamHistoryData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamHistoryQueryKey(options),
  });
};

export const getTeamYearsParticipatedQueryKey = (
  options: Options<GetTeamYearsParticipatedData>,
) => createQueryKey('getTeamYearsParticipated', options);

/**
 * Gets a list of years in which the team participated in at least one competition.
 */
export const getTeamYearsParticipatedOptions = (
  options: Options<GetTeamYearsParticipatedData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamYearsParticipated({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamYearsParticipatedQueryKey(options),
  });
};

export const getTeamDistrictsQueryKey = (
  options: Options<GetTeamDistrictsData>,
) => createQueryKey('getTeamDistricts', options);

/**
 * Gets an array of districts representing each year the team was in a district. Will return an empty array if the team was never in a district.
 */
export const getTeamDistrictsOptions = (
  options: Options<GetTeamDistrictsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamDistricts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamDistrictsQueryKey(options),
  });
};

export const getTeamRobotsQueryKey = (options: Options<GetTeamRobotsData>) =>
  createQueryKey('getTeamRobots', options);

/**
 * Gets a list of year and robot name pairs for each year that a robot name was provided. Will return an empty array if the team has never named a robot.
 */
export const getTeamRobotsOptions = (options: Options<GetTeamRobotsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamRobots({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamRobotsQueryKey(options),
  });
};

export const getTeamEventsQueryKey = (options: Options<GetTeamEventsData>) =>
  createQueryKey('getTeamEvents', options);

/**
 * Gets a list of all events this team has competed at.
 */
export const getTeamEventsOptions = (options: Options<GetTeamEventsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventsQueryKey(options),
  });
};

export const getTeamEventsSimpleQueryKey = (
  options: Options<GetTeamEventsSimpleData>,
) => createQueryKey('getTeamEventsSimple', options);

/**
 * Gets a short-form list of all events this team has competed at.
 */
export const getTeamEventsSimpleOptions = (
  options: Options<GetTeamEventsSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventsSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventsSimpleQueryKey(options),
  });
};

export const getTeamEventsKeysQueryKey = (
  options: Options<GetTeamEventsKeysData>,
) => createQueryKey('getTeamEventsKeys', options);

/**
 * Gets a list of the event keys for all events this team has competed at.
 */
export const getTeamEventsKeysOptions = (
  options: Options<GetTeamEventsKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventsKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventsKeysQueryKey(options),
  });
};

export const getTeamEventsByYearQueryKey = (
  options: Options<GetTeamEventsByYearData>,
) => createQueryKey('getTeamEventsByYear', options);

/**
 * Gets a list of events this team has competed at in the given year.
 */
export const getTeamEventsByYearOptions = (
  options: Options<GetTeamEventsByYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventsByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventsByYearQueryKey(options),
  });
};

export const getTeamEventsByYearSimpleQueryKey = (
  options: Options<GetTeamEventsByYearSimpleData>,
) => createQueryKey('getTeamEventsByYearSimple', options);

/**
 * Gets a short-form list of events this team has competed at in the given year.
 */
export const getTeamEventsByYearSimpleOptions = (
  options: Options<GetTeamEventsByYearSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventsByYearSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventsByYearSimpleQueryKey(options),
  });
};

export const getTeamEventsByYearKeysQueryKey = (
  options: Options<GetTeamEventsByYearKeysData>,
) => createQueryKey('getTeamEventsByYearKeys', options);

/**
 * Gets a list of the event keys for events this team has competed at in the given year.
 */
export const getTeamEventsByYearKeysOptions = (
  options: Options<GetTeamEventsByYearKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventsByYearKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventsByYearKeysQueryKey(options),
  });
};

export const getTeamEventsStatusesByYearQueryKey = (
  options: Options<GetTeamEventsStatusesByYearData>,
) => createQueryKey('getTeamEventsStatusesByYear', options);

/**
 * Gets a key-value list of the event statuses for events this team has competed at in the given year.
 */
export const getTeamEventsStatusesByYearOptions = (
  options: Options<GetTeamEventsStatusesByYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventsStatusesByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventsStatusesByYearQueryKey(options),
  });
};

export const getTeamEventMatchesQueryKey = (
  options: Options<GetTeamEventMatchesData>,
) => createQueryKey('getTeamEventMatches', options);

/**
 * Gets a list of matches for the given team and event.
 */
export const getTeamEventMatchesOptions = (
  options: Options<GetTeamEventMatchesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventMatches({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventMatchesQueryKey(options),
  });
};

export const getTeamEventMatchesSimpleQueryKey = (
  options: Options<GetTeamEventMatchesSimpleData>,
) => createQueryKey('getTeamEventMatchesSimple', options);

/**
 * Gets a short-form list of matches for the given team and event.
 */
export const getTeamEventMatchesSimpleOptions = (
  options: Options<GetTeamEventMatchesSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventMatchesSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventMatchesSimpleQueryKey(options),
  });
};

export const getTeamEventMatchesKeysQueryKey = (
  options: Options<GetTeamEventMatchesKeysData>,
) => createQueryKey('getTeamEventMatchesKeys', options);

/**
 * Gets a list of match keys for matches for the given team and event.
 */
export const getTeamEventMatchesKeysOptions = (
  options: Options<GetTeamEventMatchesKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventMatchesKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventMatchesKeysQueryKey(options),
  });
};

export const getTeamEventAwardsQueryKey = (
  options: Options<GetTeamEventAwardsData>,
) => createQueryKey('getTeamEventAwards', options);

/**
 * Gets a list of awards the given team won at the given event.
 */
export const getTeamEventAwardsOptions = (
  options: Options<GetTeamEventAwardsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventAwards({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventAwardsQueryKey(options),
  });
};

export const getTeamEventStatusQueryKey = (
  options: Options<GetTeamEventStatusData>,
) => createQueryKey('getTeamEventStatus', options);

/**
 * Gets the competition rank and status of the team at the given event.
 */
export const getTeamEventStatusOptions = (
  options: Options<GetTeamEventStatusData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamEventStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamEventStatusQueryKey(options),
  });
};

export const getTeamAwardsQueryKey = (options: Options<GetTeamAwardsData>) =>
  createQueryKey('getTeamAwards', options);

/**
 * Gets a list of awards the given team has won.
 */
export const getTeamAwardsOptions = (options: Options<GetTeamAwardsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamAwards({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamAwardsQueryKey(options),
  });
};

export const getTeamAwardsByYearQueryKey = (
  options: Options<GetTeamAwardsByYearData>,
) => createQueryKey('getTeamAwardsByYear', options);

/**
 * Gets a list of awards the given team has won in a given year.
 */
export const getTeamAwardsByYearOptions = (
  options: Options<GetTeamAwardsByYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamAwardsByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamAwardsByYearQueryKey(options),
  });
};

export const getTeamMatchesByYearQueryKey = (
  options: Options<GetTeamMatchesByYearData>,
) => createQueryKey('getTeamMatchesByYear', options);

/**
 * Gets a list of matches for the given team and year.
 */
export const getTeamMatchesByYearOptions = (
  options: Options<GetTeamMatchesByYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamMatchesByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamMatchesByYearQueryKey(options),
  });
};

export const getTeamMatchesByYearSimpleQueryKey = (
  options: Options<GetTeamMatchesByYearSimpleData>,
) => createQueryKey('getTeamMatchesByYearSimple', options);

/**
 * Gets a short-form list of matches for the given team and year.
 */
export const getTeamMatchesByYearSimpleOptions = (
  options: Options<GetTeamMatchesByYearSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamMatchesByYearSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamMatchesByYearSimpleQueryKey(options),
  });
};

export const getTeamMatchesByYearKeysQueryKey = (
  options: Options<GetTeamMatchesByYearKeysData>,
) => createQueryKey('getTeamMatchesByYearKeys', options);

/**
 * Gets a list of match keys for matches for the given team and year.
 */
export const getTeamMatchesByYearKeysOptions = (
  options: Options<GetTeamMatchesByYearKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamMatchesByYearKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamMatchesByYearKeysQueryKey(options),
  });
};

export const getTeamMediaByYearQueryKey = (
  options: Options<GetTeamMediaByYearData>,
) => createQueryKey('getTeamMediaByYear', options);

/**
 * Gets a list of Media (videos / pictures) for the given team and year.
 */
export const getTeamMediaByYearOptions = (
  options: Options<GetTeamMediaByYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamMediaByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamMediaByYearQueryKey(options),
  });
};

export const getTeamMediaByTagQueryKey = (
  options: Options<GetTeamMediaByTagData>,
) => createQueryKey('getTeamMediaByTag', options);

/**
 * Gets a list of Media (videos / pictures) for the given team and tag.
 */
export const getTeamMediaByTagOptions = (
  options: Options<GetTeamMediaByTagData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamMediaByTag({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamMediaByTagQueryKey(options),
  });
};

export const getTeamMediaByTagYearQueryKey = (
  options: Options<GetTeamMediaByTagYearData>,
) => createQueryKey('getTeamMediaByTagYear', options);

/**
 * Gets a list of Media (videos / pictures) for the given team, tag and year.
 */
export const getTeamMediaByTagYearOptions = (
  options: Options<GetTeamMediaByTagYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamMediaByTagYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamMediaByTagYearQueryKey(options),
  });
};

export const getTeamSocialMediaQueryKey = (
  options: Options<GetTeamSocialMediaData>,
) => createQueryKey('getTeamSocialMedia', options);

/**
 * Gets a list of Media (social media) for the given team.
 */
export const getTeamSocialMediaOptions = (
  options: Options<GetTeamSocialMediaData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamSocialMedia({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamSocialMediaQueryKey(options),
  });
};

export const getEventsByYearQueryKey = (
  options: Options<GetEventsByYearData>,
) => createQueryKey('getEventsByYear', options);

/**
 * Gets a list of events in the given year.
 */
export const getEventsByYearOptions = (
  options: Options<GetEventsByYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventsByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventsByYearQueryKey(options),
  });
};

export const getEventsByYearSimpleQueryKey = (
  options: Options<GetEventsByYearSimpleData>,
) => createQueryKey('getEventsByYearSimple', options);

/**
 * Gets a short-form list of events in the given year.
 */
export const getEventsByYearSimpleOptions = (
  options: Options<GetEventsByYearSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventsByYearSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventsByYearSimpleQueryKey(options),
  });
};

export const getEventsByYearKeysQueryKey = (
  options: Options<GetEventsByYearKeysData>,
) => createQueryKey('getEventsByYearKeys', options);

/**
 * Gets a list of event keys in the given year.
 */
export const getEventsByYearKeysOptions = (
  options: Options<GetEventsByYearKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventsByYearKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventsByYearKeysQueryKey(options),
  });
};

export const getEventQueryKey = (options: Options<GetEventData>) =>
  createQueryKey('getEvent', options);

/**
 * Gets an Event.
 */
export const getEventOptions = (options: Options<GetEventData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEvent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventQueryKey(options),
  });
};

export const getEventSimpleQueryKey = (options: Options<GetEventSimpleData>) =>
  createQueryKey('getEventSimple', options);

/**
 * Gets a short-form Event.
 */
export const getEventSimpleOptions = (options: Options<GetEventSimpleData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventSimpleQueryKey(options),
  });
};

export const getEventAlliancesQueryKey = (
  options: Options<GetEventAlliancesData>,
) => createQueryKey('getEventAlliances', options);

/**
 * Gets a list of Elimination Alliances for the given Event.
 */
export const getEventAlliancesOptions = (
  options: Options<GetEventAlliancesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventAlliances({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventAlliancesQueryKey(options),
  });
};

export const getEventInsightsQueryKey = (
  options: Options<GetEventInsightsData>,
) => createQueryKey('getEventInsights', options);

/**
 * Gets a set of Event-specific insights for the given Event.
 */
export const getEventInsightsOptions = (
  options: Options<GetEventInsightsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventInsights({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventInsightsQueryKey(options),
  });
};

export const getEventOprsQueryKey = (options: Options<GetEventOprsData>) =>
  createQueryKey('getEventOprs', options);

/**
 * Gets a set of Event OPRs (including OPR, DPR, and CCWM) for the given Event.
 */
export const getEventOprsOptions = (options: Options<GetEventOprsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventOprs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventOprsQueryKey(options),
  });
};

export const getEventCoprsQueryKey = (options: Options<GetEventCoprsData>) =>
  createQueryKey('getEventCoprs', options);

/**
 * Gets a set of Event Component OPRs for the given Event.
 */
export const getEventCoprsOptions = (options: Options<GetEventCoprsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventCoprs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventCoprsQueryKey(options),
  });
};

export const getEventPredictionsQueryKey = (
  options: Options<GetEventPredictionsData>,
) => createQueryKey('getEventPredictions', options);

/**
 * Gets information on TBA-generated predictions for the given Event. Contains year-specific information. *WARNING* This endpoint is currently under development and may change at any time.
 */
export const getEventPredictionsOptions = (
  options: Options<GetEventPredictionsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventPredictions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventPredictionsQueryKey(options),
  });
};

export const getEventRankingsQueryKey = (
  options: Options<GetEventRankingsData>,
) => createQueryKey('getEventRankings', options);

/**
 * Gets a list of team rankings for the Event.
 */
export const getEventRankingsOptions = (
  options: Options<GetEventRankingsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventRankings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventRankingsQueryKey(options),
  });
};

export const getEventDistrictPointsQueryKey = (
  options: Options<GetEventDistrictPointsData>,
) => createQueryKey('getEventDistrictPoints', options);

/**
 * Gets a list of district points for the Event. These are always calculated, regardless of event type, and may/may not be actually useful.
 */
export const getEventDistrictPointsOptions = (
  options: Options<GetEventDistrictPointsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventDistrictPoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventDistrictPointsQueryKey(options),
  });
};

export const getRegionalChampsPoolPointsQueryKey = (
  options: Options<GetRegionalChampsPoolPointsData>,
) => createQueryKey('getRegionalChampsPoolPoints', options);

/**
 * For 2025+ Regional events, this will return points towards the Championship qualification pool.
 */
export const getRegionalChampsPoolPointsOptions = (
  options: Options<GetRegionalChampsPoolPointsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRegionalChampsPoolPoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRegionalChampsPoolPointsQueryKey(options),
  });
};

export const getEventAdvancementPointsQueryKey = (
  options: Options<GetEventAdvancementPointsData>,
) => createQueryKey('getEventAdvancementPoints', options);

/**
 * Depending on the type of event (district/regional), this will return either district points or regional CMP points
 */
export const getEventAdvancementPointsOptions = (
  options: Options<GetEventAdvancementPointsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventAdvancementPoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventAdvancementPointsQueryKey(options),
  });
};

export const getEventTeamsQueryKey = (options: Options<GetEventTeamsData>) =>
  createQueryKey('getEventTeams', options);

/**
 * Gets a list of `Team` objects that competed in the given event.
 */
export const getEventTeamsOptions = (options: Options<GetEventTeamsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventTeams({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventTeamsQueryKey(options),
  });
};

export const getEventTeamsSimpleQueryKey = (
  options: Options<GetEventTeamsSimpleData>,
) => createQueryKey('getEventTeamsSimple', options);

/**
 * Gets a short-form list of `Team` objects that competed in the given event.
 */
export const getEventTeamsSimpleOptions = (
  options: Options<GetEventTeamsSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventTeamsSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventTeamsSimpleQueryKey(options),
  });
};

export const getEventTeamsKeysQueryKey = (
  options: Options<GetEventTeamsKeysData>,
) => createQueryKey('getEventTeamsKeys', options);

/**
 * Gets a list of `Team` keys that competed in the given event.
 */
export const getEventTeamsKeysOptions = (
  options: Options<GetEventTeamsKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventTeamsKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventTeamsKeysQueryKey(options),
  });
};

export const getEventTeamsStatusesQueryKey = (
  options: Options<GetEventTeamsStatusesData>,
) => createQueryKey('getEventTeamsStatuses', options);

/**
 * Gets a key-value list of the event statuses for teams competing at the given event.
 */
export const getEventTeamsStatusesOptions = (
  options: Options<GetEventTeamsStatusesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventTeamsStatuses({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventTeamsStatusesQueryKey(options),
  });
};

export const getEventMatchesQueryKey = (
  options: Options<GetEventMatchesData>,
) => createQueryKey('getEventMatches', options);

/**
 * Gets a list of matches for the given event.
 */
export const getEventMatchesOptions = (
  options: Options<GetEventMatchesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventMatches({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventMatchesQueryKey(options),
  });
};

export const getEventMatchesSimpleQueryKey = (
  options: Options<GetEventMatchesSimpleData>,
) => createQueryKey('getEventMatchesSimple', options);

/**
 * Gets a short-form list of matches for the given event.
 */
export const getEventMatchesSimpleOptions = (
  options: Options<GetEventMatchesSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventMatchesSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventMatchesSimpleQueryKey(options),
  });
};

export const getEventMatchesKeysQueryKey = (
  options: Options<GetEventMatchesKeysData>,
) => createQueryKey('getEventMatchesKeys', options);

/**
 * Gets a list of match keys for the given event.
 */
export const getEventMatchesKeysOptions = (
  options: Options<GetEventMatchesKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventMatchesKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventMatchesKeysQueryKey(options),
  });
};

export const getEventMatchTimeseriesQueryKey = (
  options: Options<GetEventMatchTimeseriesData>,
) => createQueryKey('getEventMatchTimeseries', options);

/**
 * Gets an array of Match Keys for the given event key that have timeseries data. Returns an empty array if no matches have timeseries data.
 * *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up.
 * *WARNING:* This endpoint and corresponding data models are under *active development* and may change at any time, including in breaking ways.
 */
export const getEventMatchTimeseriesOptions = (
  options: Options<GetEventMatchTimeseriesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventMatchTimeseries({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventMatchTimeseriesQueryKey(options),
  });
};

export const getEventAwardsQueryKey = (options: Options<GetEventAwardsData>) =>
  createQueryKey('getEventAwards', options);

/**
 * Gets a list of awards from the given event.
 */
export const getEventAwardsOptions = (options: Options<GetEventAwardsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventAwards({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventAwardsQueryKey(options),
  });
};

export const getEventTeamMediaQueryKey = (
  options: Options<GetEventTeamMediaData>,
) => createQueryKey('getEventTeamMedia', options);

/**
 * Gets a list of media objects that correspond to teams at this event.
 */
export const getEventTeamMediaOptions = (
  options: Options<GetEventTeamMediaData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEventTeamMedia({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEventTeamMediaQueryKey(options),
  });
};

export const getMatchQueryKey = (options: Options<GetMatchData>) =>
  createQueryKey('getMatch', options);

/**
 * Gets a `Match` object for the given match key.
 */
export const getMatchOptions = (options: Options<GetMatchData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMatch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMatchQueryKey(options),
  });
};

export const getMatchSimpleQueryKey = (options: Options<GetMatchSimpleData>) =>
  createQueryKey('getMatchSimple', options);

/**
 * Gets a short-form `Match` object for the given match key.
 */
export const getMatchSimpleOptions = (options: Options<GetMatchSimpleData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMatchSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMatchSimpleQueryKey(options),
  });
};

export const getMatchTimeseriesQueryKey = (
  options: Options<GetMatchTimeseriesData>,
) => createQueryKey('getMatchTimeseries', options);

/**
 * Gets an array of game-specific Match Timeseries objects for the given match key or an empty array if not available.
 * *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up.
 * *WARNING:* This endpoint and corresponding data models are under *active development* and may change at any time, including in breaking ways.
 */
export const getMatchTimeseriesOptions = (
  options: Options<GetMatchTimeseriesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMatchTimeseries({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMatchTimeseriesQueryKey(options),
  });
};

export const getMatchZebraQueryKey = (options: Options<GetMatchZebraData>) =>
  createQueryKey('getMatchZebra', options);

/**
 * Gets Zebra MotionWorks data for a Match for the given match key.
 */
export const getMatchZebraOptions = (options: Options<GetMatchZebraData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMatchZebra({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMatchZebraQueryKey(options),
  });
};

export const getDistrictsByYearQueryKey = (
  options: Options<GetDistrictsByYearData>,
) => createQueryKey('getDistrictsByYear', options);

/**
 * Gets a list of districts and their corresponding district key, for the given year.
 */
export const getDistrictsByYearOptions = (
  options: Options<GetDistrictsByYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictsByYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictsByYearQueryKey(options),
  });
};

export const getDistrictHistoryQueryKey = (
  options: Options<GetDistrictHistoryData>,
) => createQueryKey('getDistrictHistory', options);

/**
 * Gets a list of District objects with the given district abbreviation. This accounts for district abbreviation changes, such as MAR to FMA.
 */
export const getDistrictHistoryOptions = (
  options: Options<GetDistrictHistoryData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictHistoryQueryKey(options),
  });
};

export const getDistrictInsightsQueryKey = (
  options: Options<GetDistrictInsightsData>,
) => createQueryKey('getDistrictInsights', options);

/**
 * Gets insights for a given district.
 */
export const getDistrictInsightsOptions = (
  options: Options<GetDistrictInsightsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictInsights({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictInsightsQueryKey(options),
  });
};

export const getDistrictEventsQueryKey = (
  options: Options<GetDistrictEventsData>,
) => createQueryKey('getDistrictEvents', options);

/**
 * Gets a list of events in the given district.
 */
export const getDistrictEventsOptions = (
  options: Options<GetDistrictEventsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictEventsQueryKey(options),
  });
};

export const getDistrictAwardsQueryKey = (
  options: Options<GetDistrictAwardsData>,
) => createQueryKey('getDistrictAwards', options);

/**
 * Gets a list of awards in the given district.
 */
export const getDistrictAwardsOptions = (
  options: Options<GetDistrictAwardsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictAwards({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictAwardsQueryKey(options),
  });
};

export const getDistrictEventsSimpleQueryKey = (
  options: Options<GetDistrictEventsSimpleData>,
) => createQueryKey('getDistrictEventsSimple', options);

/**
 * Gets a short-form list of events in the given district.
 */
export const getDistrictEventsSimpleOptions = (
  options: Options<GetDistrictEventsSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictEventsSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictEventsSimpleQueryKey(options),
  });
};

export const getDistrictEventsKeysQueryKey = (
  options: Options<GetDistrictEventsKeysData>,
) => createQueryKey('getDistrictEventsKeys', options);

/**
 * Gets a list of event keys for events in the given district.
 */
export const getDistrictEventsKeysOptions = (
  options: Options<GetDistrictEventsKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictEventsKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictEventsKeysQueryKey(options),
  });
};

export const getDistrictTeamsQueryKey = (
  options: Options<GetDistrictTeamsData>,
) => createQueryKey('getDistrictTeams', options);

/**
 * Gets a list of `Team` objects that competed in events in the given district.
 */
export const getDistrictTeamsOptions = (
  options: Options<GetDistrictTeamsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictTeams({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictTeamsQueryKey(options),
  });
};

export const getDistrictTeamsSimpleQueryKey = (
  options: Options<GetDistrictTeamsSimpleData>,
) => createQueryKey('getDistrictTeamsSimple', options);

/**
 * Gets a short-form list of `Team` objects that competed in events in the given district.
 */
export const getDistrictTeamsSimpleOptions = (
  options: Options<GetDistrictTeamsSimpleData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictTeamsSimple({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictTeamsSimpleQueryKey(options),
  });
};

export const getDistrictTeamsKeysQueryKey = (
  options: Options<GetDistrictTeamsKeysData>,
) => createQueryKey('getDistrictTeamsKeys', options);

/**
 * Gets a list of `Team` objects that competed in events in the given district.
 */
export const getDistrictTeamsKeysOptions = (
  options: Options<GetDistrictTeamsKeysData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictTeamsKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictTeamsKeysQueryKey(options),
  });
};

export const getDistrictRankingsQueryKey = (
  options: Options<GetDistrictRankingsData>,
) => createQueryKey('getDistrictRankings', options);

/**
 * Gets a list of team district rankings for the given district.
 */
export const getDistrictRankingsOptions = (
  options: Options<GetDistrictRankingsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictRankings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictRankingsQueryKey(options),
  });
};

export const getDistrictAdvancementQueryKey = (
  options: Options<GetDistrictAdvancementData>,
) => createQueryKey('getDistrictAdvancement', options);

/**
 * Gets a list of advancement information per team in a district.
 */
export const getDistrictAdvancementOptions = (
  options: Options<GetDistrictAdvancementData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictAdvancement({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictAdvancementQueryKey(options),
  });
};

export const getDistrictDcmpHistoryQueryKey = (
  options: Options<GetDistrictDcmpHistoryData>,
) => createQueryKey('getDistrictDcmpHistory', options);

/**
 * Gets a list of DCMP events and awards for the given district abbreviation.
 */
export const getDistrictDcmpHistoryOptions = (
  options: Options<GetDistrictDcmpHistoryData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDistrictDcmpHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDistrictDcmpHistoryQueryKey(options),
  });
};

export const getRegionalAdvancementQueryKey = (
  options: Options<GetRegionalAdvancementData>,
) => createQueryKey('getRegionalAdvancement', options);

/**
 * Gets information about per-team advancement to the FIRST Championship.
 */
export const getRegionalAdvancementOptions = (
  options: Options<GetRegionalAdvancementData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRegionalAdvancement({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRegionalAdvancementQueryKey(options),
  });
};

export const getRegionalRankingsQueryKey = (
  options: Options<GetRegionalRankingsData>,
) => createQueryKey('getRegionalRankings', options);

/**
 * Gets the team rankings in the regional pool for a specific year.
 */
export const getRegionalRankingsOptions = (
  options: Options<GetRegionalRankingsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRegionalRankings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRegionalRankingsQueryKey(options),
  });
};

export const getInsightsLeaderboardsYearQueryKey = (
  options: Options<GetInsightsLeaderboardsYearData>,
) => createQueryKey('getInsightsLeaderboardsYear', options);

/**
 * Gets a list of `LeaderboardInsight` objects from a specific year. Use year=0 for overall.
 */
export const getInsightsLeaderboardsYearOptions = (
  options: Options<GetInsightsLeaderboardsYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getInsightsLeaderboardsYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getInsightsLeaderboardsYearQueryKey(options),
  });
};

export const getInsightsNotablesYearQueryKey = (
  options: Options<GetInsightsNotablesYearData>,
) => createQueryKey('getInsightsNotablesYear', options);

/**
 * Gets a list of `NotablesInsight` objects from a specific year. Use year=0 for overall.
 */
export const getInsightsNotablesYearOptions = (
  options: Options<GetInsightsNotablesYearData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getInsightsNotablesYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getInsightsNotablesYearQueryKey(options),
  });
};

export const getSearchIndexQueryKey = (options?: Options<GetSearchIndexData>) =>
  createQueryKey('getSearchIndex', options);

/**
 * Gets a large blob of data that is used on the frontend for searching. May change without notice.
 */
export const getSearchIndexOptions = (
  options?: Options<GetSearchIndexData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSearchIndex({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSearchIndexQueryKey(options),
  });
};
