from google.appengine.api import taskqueue as taskqueue
from google.appengine.ext import db as db
from typing import Any

class Error(Exception): ...
class PermanentTaskFailure(Error): ...
class SingularTaskFailure(Error): ...

def set_log_level(log_level) -> None: ...
def run(data): ...

class _DeferredTaskEntity(db.Model):
    data: Any

def run_from_datastore(key) -> None: ...
def invoke_member(obj, membername, *args, **kwargs): ...
def serialize(obj, *args, **kwargs): ...
def defer(obj, *args, **kwargs): ...

class Handler:
    def run_from_request(self, environ): ...
    def post(self, environ): ...
    def __call__(self, environ, start_response): ...

application: Any
