// This file is auto-generated by @hey-api/openapi-ts

export type AllianceList = Array<Array<string>>;

export type Award = {
  /**
   * Type enum of the award. If null, this will be automatically determined from the name_str. See https://github.com/the-blue-alliance/the-blue-alliance/blob/py3/src/backend/common/consts/award_type.py
   */
  type_enum?: number;
  /**
   * Name of the award
   */
  name_str: string;
  /**
   * Key of the team winning this award. Formatted like `frcXXXX` where `XXXX` is the team number. Can be null
   */
  team_key?: string;
  /**
   * Name of the individual winning this award. Can be null
   */
  awardee?: string;
};

export type EventInfo = {
  /**
   * Event code used to sync data with FIRST
   */
  first_code?: string;
  /**
   * Integer constant representing the playoff format. References constants here: https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/playoff_type.py
   */
  playoff_type?: number;
  /**
   * A list of webcast URLs to set for this event. This will overwrite the existing webcast list
   */
  webcasts?: Array<{
    /**
     * A webcast url
     */
    url?: string;
  }>;
  /**
   * A mapping of temp key --> remapped key (including B team keys)
   */
  remap_teams?: {
    [key: string]: string;
  };
};

export type MatchAlliance = {
  teams: Array<string>;
  /**
   * Score of the match. Null means the match has not been played
   */
  score: number;
  surrogates?: Array<string>;
  dqs?: Array<string>;
};

export type Match = {
  /**
   * Competition level of the match
   */
  comp_level: 'qm' | 'ef' | 'qf' | 'sf' | 'f';
  /**
   * Set number of the match
   */
  set_number: number;
  /**
   * Number of the match in the current set
   */
  match_number: number;
  /**
   * Competing teams and score info for this match
   */
  alliances: {
    red: MatchAlliance;
    blue: MatchAlliance;
  };
  /**
   * Dict of {'red': {K1: V1, K2: V2, ...}, 'blue': {...}}. Where Kn are keys and Vn are values for those keys. Valid keys Kn vary by year. For 2014, valid keys are: 'auto', 'assist', 'truss+catch', 'teleop_goal+foul'.
   */
  score_breakdown?: string;
  /**
   * String in the format "(H)H:MM AM/PM" for when the match will be played in the event's local timezone
   */
  time_str?: string;
  /**
   * UTC time of match in ISO 8601 format (YYYY-MM-DDTHH:MM:SS)
   */
  time_utc?: string;
  /**
   * The name for the match, to be shown on the event page
   */
  display_name?: string;
};

/**
 * TBA event key to update. For example, 2017cthar
 */
export type EventKeyParam = string;

export type UpdateEventInfoData = {
  /**
   * A JSON dictionary, mapping property name to the new value.
   */
  body: EventInfo;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/info/update';
};

export type UpdateEventInfoErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateEventInfoResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type UpdateAlliancesData = {
  /**
   * A list of alliances, in order of alliance number. An alliance is a list of team keys, in order of selection. An alliance can have an arbitrary number of teams (provided that all alliances have the same number of teams).
   */
  body: AllianceList;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/alliance_selections/update';
};

export type UpdateAlliancesErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateAlliancesResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type UpdateAwardsData = {
  /**
   * List of awards. An award is a dict of:
   *
   * *name_str*: String of award name. ex: "Tournament Winner" or "Dean's List Finalist"  *team_key*: String in the format `frcXXX` for the team that won the award. Can be null.  *awardee*: String corresponding to the name of an individual that won the award. Can be null.
   */
  body: Array<Award>;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/awards/update';
};

export type UpdateAwardsErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateAwardsResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type UpdateMatchesData = {
  /**
   * List of matches
   */
  body: Array<Match>;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/matches/update';
};

export type UpdateMatchesErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateMatchesResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type DeleteMatchesData = {
  /**
   * List of match keys
   */
  body: Array<string>;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/matches/delete';
};

export type DeleteMatchesErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type DeleteMatchesResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type UpdateRankingsData = {
  /**
   * A dict of `breakdowns` and `rankings
   */
  body: {
    breakdowns: Array<string>;
    /**
     * List of dicts describing ranking data. In addition to the properties given, there should be one K/V pair for each item in the `breakdown` section (to pass game-specific ranking elements)
     */
    rankings: Array<{
      /**
       * Team key, like `frcXXXX` where `XXXX` is the team number
       */
      team_key?: string;
      /**
       * Integer rank of this team
       */
      rank?: number;
      /**
       * Number of non-surrogate wins
       */
      wins?: number;
      /**
       * Number of non-surrogate losses
       */
      losses?: number;
      /**
       * Number of non-surrogate ties
       */
      ties?: number;
      /**
       * Number of matches played
       */
      played?: number;
      /**
       * Number of non-surrogate DQ'd matches
       */
      dqs?: number;
    }>;
  };
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/rankings/update';
};

export type UpdateRankingsErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateRankingsResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type UpdateTeamListData = {
  /**
   * List of team keys
   */
  body: Array<string>;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/team_list/update';
};

export type UpdateTeamListErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateTeamListResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type UpdateMatchVideosData = {
  /**
   * Dict of {key: partial match key, value: youtube video id}
   */
  body: string;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/match_videos/add';
};

export type UpdateMatchVideosErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateMatchVideosResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type UpdateEventMediaData = {
  /**
   * List of YouTube video IDs to add
   */
  body: Array<string>;
  path: {
    /**
     * TBA event key to update. For example, 2017cthar
     */
    eventKey: string;
  };
  query?: never;
  url: '/event/{eventKey}/media/add';
};

export type UpdateEventMediaErrors = {
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were missing
   */
  400: unknown;
  /**
   * One or both of `X-TBA-Auth-ID` `X-TBA-Auth-Sig` were invalid
   */
  401: unknown;
};

export type UpdateEventMediaResponses = {
  /**
   * The operation completed successfully
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: 'https://www.thebluealliance.com/api/trusted/v1' | (string & {});
};
