application: tbatv-dev
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- appstats: on
- remote_api: on

libraries:
- name: django
  version: "1.2"

handlers:
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /javascript
  static_dir: static/javascript
- url: /jwplayer
  static_dir: static/jwplayer
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /tasks/.*
  script: cron_main.py
  login: admin
- url: /admin/.*
  script: admin_main.py
  login: admin
- url: /api/.*
  script: api_main.py
- url: .*
  script: main.py

skip_files:
- ^(.*/)?.*\.less.*
