application: tbatv-dev-hrd
version: 1-2
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "4d"

builtins:
- appstats: on
- remote_api: on

libraries:
- name: django
  version: "1.2"

handlers:
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /javascript
  static_dir: static/javascript
- url: /jwplayer
  static_dir: static/jwplayer
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
- url: /apple-touch-icon-precomposed.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /tasks/.*
  script: cron_main.app
  login: admin
- url: /admin/.*
  script: admin_main.app
  login: admin
- url: /api/.*
  script: api_main.app
- url: .*
  script: main.app

skip_files:
- ^(.*/)?.*\.less.*
- .git/*
- test_data/*
- tests/*
- utils/*
- run_tests.py
- pavement.py
- do_compress.py
- ^(.*/)?.*\.jar.*
- static/css/less_css/*
- static/css/precompiled_css/*
- static/javascript/bootstrap_js/*
- static/javascript/jquery_js/*
- static/javascript/tba_js/*
