application: tbatv-dev
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- remote_api: on

handlers:
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /javascript
  static_dir: static/javascript
- url: /jwplayer
  static_dir: static/jwplayer
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt


- url: /tasks/.*
  script: cron_main.py
- url: /admin/.*
  script: admin_main.py
  login: admin
- url: /api/.*
  script: api_main.py
- url: .*
  script: main.py

