version: prod-1

runtime: python27
api_version: 1
threadsafe: false

instance_class: F1
automatic_scaling:
  max_idle_instances: 1

builtins:
- appstats: on
- remote_api: on
- deferred: on

libraries:
- name: django
  version: "1.5"
- name: numpy
  version: "1.6.1"
- name: endpoints
  version: "1.0"
- name: pycrypto  # for mobile API
  version: "2.6"
- name: jinja2
  version: "2.6"

handlers:
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
  expiration: "1h"
- url: /javascript
  static_dir: static/javascript
- url: /jwplayer
  static_dir: static/jwplayer
- url: /flowplayer
  static_dir: static/flowplayer
- url: /ovp
  static_dir: static/ovp
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "1d"
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
  expiration: "1d"
- url: /apple-touch-icon-precomposed.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
  expiration: "1d"

- url: /tasks/.*
  script: cron_main.app
  login: admin
- url: /admin/.*
  script: admin_main.app
  login: admin
- url: /api/.*
  script: api_main.app
- url: /_ah/spi/.* # Endpoints for internal mobile API
  script: mobile_main.app
- url: .*
  script: main.app

includes:
- app_shared.yaml
