runtime: python27
api_version: 1
threadsafe: false

instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: 0.8
  min_pending_latency: 200ms
  max_pending_latency: automatic

builtins:
- remote_api: on
- deferred: on

libraries:
- name: django
  version: "1.11"
- name: numpy
  version: "1.6.1"
- name: pycrypto  # for mobile API
  version: "2.6"
- name: ssl
  version: 2.7.11
- name: jinja2
  version: "2.6"
- name: pytz
  version: "2016.4"
- name: MySQLdb
  version: "latest"

handlers:
- url: /css
  static_dir: static/compiled/css
- url: /images
  static_dir: static/images
  expiration: "1h"
- url: /javascript
  static_dir: static/compiled/javascript
- url: /jwplayer
  static_dir: static/jwplayer
- url: /flowplayer
  static_dir: static/flowplayer
- url: /ovp
  static_dir: static/ovp
- url: /icons
  static_dir: static/icons
  expiration: "1d"
- url: /swagger
  static_dir: static/swagger
  expiration: "1h"
- url: /favicon.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon.ico
  expiration: "1d"
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /firebase-messaging-sw.js
  static_files: static/compiled/javascript/firebase-messaging-sw.js
  upload: static/compiled/javascript/firebase-messaging-sw.js
  expiration: "1d"
- url: /manifest.json
  static_files: static/manifest.json
  upload: static/manifest.json
  expiration: "1d"
- url: /.well-known
  static_dir: static/well-known
  mime_type: application/json

- url: /tasks/.* # Here to take care of requests until new dispatch.yaml kicks in
  script: cron_main.app
  login: admin
- url: /admin/console/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /admin/.*
  script: admin_main.app
  login: admin
- url: /api/v3/.* # Here to take care of requests until new dispatch.yaml kicks in
  script: api.apiv3_main.app
- url: /api/.*
  script: api_main.app
- url: /_ah/api/.* # Endpoints for internal mobile API
  script: mobile_main.app
- url: /_ah/queue/deferred.*
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /clientapi/.*
  script: clientapi.clientapi_service.app
- url: .*
  script: main.app

includes:
- app_shared.yaml

env_variables:
  ENDPOINTS_SERVICE_NAME: tbatv-prod-hrd.appspot.com
  FIREBASE_PROJECT_ID: tbatv-prod-hrd
