import json
import os

DEBUG = os.environ.get('SERVER_SOFTWARE', '').startswith('Dev')

# The CONFIG variables should have exactly the same structure between environments
# Eventually a test environment should be added. -gregmarra 17 Jul 2012
if DEBUG:
    CONFIG = {
        "env": "dev",
        "memcache": False,
    }
else:
    CONFIG = {
        "env": "prod",
        "memcache": True,
    }

CONFIG['kickoff'] = True

# The following lines are autogenerated when running 'paver less' and 'paver javascript'
MAIN_CSS = 'tba_style-1356084948.main.min.css' # AUTOGENERATED
GAMEDAY_CSS = 'tba_style-1356084948.gameday.min.css' # AUTOGENERATED
MAIN_JS = 'tba_combined-1356084957.main.min.js' # AUTOGENERATED
GAMEDAY_JS = 'tba_combined-1356084957.gameday.min.js' # AUTOGENERATED
# End autogenerated lines

# Setting CSS/JS paths
CONFIG['MAIN_CSS'] = MAIN_CSS
CONFIG['GAMEDAY_CSS'] = GAMEDAY_CSS
CONFIG['MAIN_JS'] = MAIN_JS
CONFIG['GAMEDAY_JS'] = GAMEDAY_JS
