from .builder import TreeBuilder
from .css import CSS as CSS
from .dammit import UnicodeDammit as UnicodeDammit
from .element import CData as CData, Comment as Comment, Declaration as Declaration, Doctype as Doctype, NavigableString, PageElement, ProcessingInstruction as ProcessingInstruction, ResultSet as ResultSet, Script as Script, Stylesheet as Stylesheet, Tag as Tag, TemplateString as TemplateString
from .filter import ElementFilter as ElementFilter, SoupStrainer
from .formatter import Formatter
from bs4._typing import _Encoding, _Encodings, _IncomingMarkup, _InsertableElement, _RawAttributeValue, _RawAttributeValues, _RawMarkup
from bs4._warnings import AttributeResemblesVariableWarning as AttributeResemblesVariableWarning, GuessedAtParserWarning as GuessedAtParserWarning, MarkupResemblesLocatorWarning as MarkupResemblesLocatorWarning, UnusualUsageWarning as UnusualUsageWarning, XMLParsedAsHTMLWarning as XMLParsedAsHTMLWarning
from bs4.exceptions import FeatureNotFound as FeatureNotFound, ParserRejectedMarkup as ParserRejectedMarkup, StopParsing as StopParsing
from typing import Any, Counter as CounterType, Iterator, Sequence

__all__ = ['AttributeResemblesVariableWarning', 'BeautifulSoup', 'Comment', 'Declaration', 'ProcessingInstruction', 'ResultSet', 'CSS', 'Script', 'Stylesheet', 'Tag', 'TemplateString', 'ElementFilter', 'UnicodeDammit', 'CData', 'Doctype', 'FeatureNotFound', 'ParserRejectedMarkup', 'StopParsing', 'AttributeResemblesVariableWarning', 'GuessedAtParserWarning', 'MarkupResemblesLocatorWarning', 'UnusualUsageWarning', 'XMLParsedAsHTMLWarning']

class BeautifulSoup(Tag):
    ROOT_TAG_NAME: str
    DEFAULT_BUILDER_FEATURES: Sequence[str]
    ASCII_SPACES: str
    element_classes: dict[type[PageElement], type[PageElement]]
    builder: TreeBuilder
    is_xml: bool
    known_xml: bool | None
    parse_only: SoupStrainer | None
    markup: _RawMarkup | None
    current_data: list[str]
    currentTag: Tag | None
    tagStack: list[Tag]
    open_tag_counter: CounterType[str]
    preserve_whitespace_tag_stack: list[Tag]
    string_container_stack: list[Tag]
    original_encoding: _Encoding | None
    declared_html_encoding: _Encoding | None
    contains_replacement_characters: bool
    def __init__(self, markup: _IncomingMarkup = '', features: str | Sequence[str] | None = None, builder: TreeBuilder | type[TreeBuilder] | None = None, parse_only: SoupStrainer | None = None, from_encoding: _Encoding | None = None, exclude_encodings: _Encodings | None = None, element_classes: dict[type[PageElement], type[PageElement]] | None = None, **kwargs: Any) -> None: ...
    def copy_self(self) -> BeautifulSoup: ...
    hidden: bool
    def reset(self) -> None: ...
    def new_tag(self, name: str, namespace: str | None = None, nsprefix: str | None = None, attrs: _RawAttributeValues | None = None, sourceline: int | None = None, sourcepos: int | None = None, string: str | None = None, **kwattrs: _RawAttributeValue) -> Tag: ...
    def string_container(self, base_class: type[NavigableString] | None = None) -> type[NavigableString]: ...
    def new_string(self, s: str, subclass: type[NavigableString] | None = None) -> NavigableString: ...
    def insert_before(self, *args: _InsertableElement) -> list[PageElement]: ...
    def insert_after(self, *args: _InsertableElement) -> list[PageElement]: ...
    def popTag(self) -> Tag | None: ...
    def pushTag(self, tag: Tag) -> None: ...
    def endData(self, containerClass: type[NavigableString] | None = None) -> None: ...
    def object_was_parsed(self, o: PageElement, parent: Tag | None = None, most_recent_element: PageElement | None = None) -> None: ...
    def handle_starttag(self, name: str, namespace: str | None, nsprefix: str | None, attrs: _RawAttributeValues, sourceline: int | None = None, sourcepos: int | None = None, namespaces: dict[str, str] | None = None) -> Tag | None: ...
    def handle_endtag(self, name: str, nsprefix: str | None = None) -> None: ...
    def handle_data(self, data: str) -> None: ...
    def decode(self, indent_level: int | None = None, eventual_encoding: _Encoding = ..., formatter: Formatter | str = 'minimal', iterator: Iterator[PageElement] | None = None, **kwargs: Any) -> str: ...

class BeautifulStoneSoup(BeautifulSoup):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
