from _typeshed import Incomplete
from bs4 import element as element
from bs4._typing import _NamespaceMapping
from bs4.element import ResultSet as ResultSet, Tag as Tag
from soupsieve import SoupSieve as SoupSieve
from types import ModuleType
from typing import Any, Iterator

soupsieve: ModuleType | None

class CSS:
    api: Incomplete
    tag: Incomplete
    def __init__(self, tag: element.Tag, api: ModuleType | None = None) -> None: ...
    def escape(self, ident: str) -> str: ...
    def compile(self, select: str, namespaces: _NamespaceMapping | None = None, flags: int = 0, **kwargs: Any) -> SoupSieve: ...
    def select_one(self, select: str, namespaces: _NamespaceMapping | None = None, flags: int = 0, **kwargs: Any) -> element.Tag | None: ...
    def select(self, select: str, namespaces: _NamespaceMapping | None = None, limit: int = 0, flags: int = 0, **kwargs: Any) -> ResultSet[element.Tag]: ...
    def iselect(self, select: str, namespaces: _NamespaceMapping | None = None, limit: int = 0, flags: int = 0, **kwargs: Any) -> Iterator[element.Tag]: ...
    def closest(self, select: str, namespaces: _NamespaceMapping | None = None, flags: int = 0, **kwargs: Any) -> element.Tag | None: ...
    def match(self, select: str, namespaces: _NamespaceMapping | None = None, flags: int = 0, **kwargs: Any) -> bool: ...
    def filter(self, select: str, namespaces: _NamespaceMapping | None = None, flags: int = 0, **kwargs: Any) -> ResultSet[element.Tag]: ...
