from bs4 import BeautifulSoup as BeautifulSoup, __version__ as __version__
from bs4._typing import _IncomingMarkup
from bs4.builder import builder_registry as builder_registry
from html.parser import HTMLParser
from typing import Any

def diagnose(data: _IncomingMarkup) -> None: ...
def lxml_trace(data: _IncomingMarkup, html: bool = True, **kwargs: Any) -> None: ...

class AnnouncingParser(HTMLParser):
    def handle_starttag(self, name: str, attrs: list[tuple[str, str | None]], handle_empty_element: bool = True) -> None: ...
    def handle_endtag(self, name: str, check_already_closed: bool = True) -> None: ...
    def handle_data(self, data: str) -> None: ...
    def handle_charref(self, name: str) -> None: ...
    def handle_entityref(self, name: str) -> None: ...
    def handle_comment(self, data: str) -> None: ...
    def handle_decl(self, data: str) -> None: ...
    def unknown_decl(self, data: str) -> None: ...
    def handle_pi(self, data: str) -> None: ...

def htmlparser_trace(data: str) -> None: ...
def rword(length: int = 5) -> str: ...
def rsentence(length: int = 4) -> str: ...
def rdoc(num_elements: int = 1000) -> str: ...
def benchmark_parsers(num_elements: int = 100000) -> None: ...
def profile(num_elements: int = 100000, parser: str = 'lxml') -> None: ...
