from _typeshed import Incomplete
from bs4._typing import _AtMostOneElement, _OneElement, _PageElementMatchFunction, _QueryResults, _RawAttributeValues, _RegularExpressionProtocol, _StrainableAttribute, _StrainableElement, _StrainableString, _StringMatchFunction, _TagMatchFunction
from bs4.element import AttributeDict as AttributeDict, NavigableString as NavigableString, PageElement as PageElement, ResultSet as ResultSet, Tag as Tag
from typing import Any, Callable, Iterator

class ElementFilter:
    match_function: _PageElementMatchFunction | None
    def __init__(self, match_function: _PageElementMatchFunction | None = None) -> None: ...
    @property
    def includes_everything(self) -> bool: ...
    @property
    def excludes_everything(self) -> bool: ...
    def match(self, element: PageElement, _known_rules: bool = False) -> bool: ...
    def filter(self, generator: Iterator[PageElement]) -> Iterator[_OneElement]: ...
    def find(self, generator: Iterator[PageElement]) -> _AtMostOneElement: ...
    def find_all(self, generator: Iterator[PageElement], limit: int | None = None) -> _QueryResults: ...
    def allow_tag_creation(self, nsprefix: str | None, name: str, attrs: _RawAttributeValues | None) -> bool: ...
    def allow_string_creation(self, string: str) -> bool: ...

class MatchRule:
    string: str | None
    pattern: _RegularExpressionProtocol | None
    present: bool | None
    exclude_everything: bool | None
    function: Incomplete
    def __init__(self, string: str | bytes | None = None, pattern: _RegularExpressionProtocol | None = None, function: Callable | None = None, present: bool | None = None, exclude_everything: bool | None = None) -> None: ...
    def matches_string(self, string: str | None) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...

class TagNameMatchRule(MatchRule):
    function: _TagMatchFunction | None
    def matches_tag(self, tag: Tag) -> bool: ...

class AttributeValueMatchRule(MatchRule):
    function: _StringMatchFunction | None

class StringMatchRule(MatchRule):
    function: _StringMatchFunction | None

class SoupStrainer(ElementFilter):
    name_rules: list[TagNameMatchRule]
    attribute_rules: dict[str, list[AttributeValueMatchRule]]
    string_rules: list[StringMatchRule]
    def __init__(self, name: _StrainableElement | None = None, attrs: dict[str, _StrainableAttribute] = {}, string: _StrainableString | None = None, **kwargs: _StrainableAttribute) -> None: ...
    @property
    def includes_everything(self) -> bool: ...
    @property
    def excludes_everything(self) -> bool: ...
    @property
    def string(self) -> _StrainableString | None: ...
    @property
    def text(self) -> _StrainableString | None: ...
    def matches_tag(self, tag: Tag) -> bool: ...
    def allow_tag_creation(self, nsprefix: str | None, name: str, attrs: _RawAttributeValues | None) -> bool: ...
    def allow_string_creation(self, string: str) -> bool: ...
    def matches_any_string_rule(self, string: str) -> bool: ...
    def match(self, element: PageElement, _known_rules: bool = False) -> bool: ...
    def search_tag(self, name: str, attrs: _RawAttributeValues | None) -> bool: ...
    def search(self, element: PageElement) -> PageElement | None: ...
