from google.appengine.ext import db as db

class _ClassKeyProperty(db.ListProperty):
    def __init__(self, name) -> None: ...
    def __set__(self, *args) -> None: ...
    def __get__(self, model_instance, model_class): ...

class PolymorphicClass(db.PropertiedClass):
    def __init__(cls, name, bases, dct) -> None: ...

class PolyModel:
    def __new__(*args, **kwds): ...
    @classmethod
    def kind(cls): ...
    @classmethod
    def class_key(cls): ...
    @classmethod
    def class_name(cls): ...
    @classmethod
    def from_entity(cls, entity): ...
    @classmethod
    def all(cls, **kwds): ...
    @classmethod
    def gql(cls, query_string, *args, **kwds): ...
