from google.appengine.api import datastore as datastore
from google.appengine.ext import db as db
from typing import Any

class Mutex(db.Model):
    LIFETIME: Any
    def acquire(self, blocking: bool = ..., retry_delay_ms: int = ...): ...
    def release(self) -> None: ...
    def is_held(self): ...

def acquire(mutexes, blocking: bool = ...): ...
def release(mutexes): ...
