import proto
from typing import Any

class ListQueuesRequest(proto.Message):
    parent: Any = ...
    filter: Any = ...
    page_size: Any = ...
    page_token: Any = ...

class ListQueuesResponse(proto.Message):
    @property
    def raw_page(self): ...
    queues: Any = ...
    next_page_token: Any = ...

class GetQueueRequest(proto.Message):
    name: Any = ...

class CreateQueueRequest(proto.Message):
    parent: Any = ...
    queue: Any = ...

class UpdateQueueRequest(proto.Message):
    queue: Any = ...
    update_mask: Any = ...

class DeleteQueueRequest(proto.Message):
    name: Any = ...

class PurgeQueueRequest(proto.Message):
    name: Any = ...

class PauseQueueRequest(proto.Message):
    name: Any = ...

class ResumeQueueRequest(proto.Message):
    name: Any = ...

class ListTasksRequest(proto.Message):
    parent: Any = ...
    response_view: Any = ...
    page_size: Any = ...
    page_token: Any = ...

class ListTasksResponse(proto.Message):
    @property
    def raw_page(self): ...
    tasks: Any = ...
    next_page_token: Any = ...

class GetTaskRequest(proto.Message):
    name: Any = ...
    response_view: Any = ...

class CreateTaskRequest(proto.Message):
    parent: Any = ...
    task: Any = ...
    response_view: Any = ...

class DeleteTaskRequest(proto.Message):
    name: Any = ...

class RunTaskRequest(proto.Message):
    name: Any = ...
    response_view: Any = ...
