import proto
from typing import Any

class Queue(proto.Message):
    class State(proto.Enum):
        STATE_UNSPECIFIED: int = ...
        RUNNING: int = ...
        PAUSED: int = ...
        DISABLED: int = ...
    name: Any = ...
    app_engine_routing_override: Any = ...
    rate_limits: Any = ...
    retry_config: Any = ...
    state: Any = ...
    purge_time: Any = ...
    stackdriver_logging_config: Any = ...

class RateLimits(proto.Message):
    max_dispatches_per_second: Any = ...
    max_burst_size: Any = ...
    max_concurrent_dispatches: Any = ...

class RetryConfig(proto.Message):
    max_attempts: Any = ...
    max_retry_duration: Any = ...
    min_backoff: Any = ...
    max_backoff: Any = ...
    max_doublings: Any = ...

class StackdriverLoggingConfig(proto.Message):
    sampling_ratio: Any = ...
