import proto
from typing import Any

class HttpMethod(proto.Enum):
    HTTP_METHOD_UNSPECIFIED: int = ...
    POST: int = ...
    GET: int = ...
    HEAD: int = ...
    PUT: int = ...
    DELETE: int = ...
    PATCH: int = ...
    OPTIONS: int = ...

class HttpRequest(proto.Message):
    url: Any = ...
    http_method: Any = ...
    headers: Any = ...
    body: Any = ...
    oauth_token: Any = ...
    oidc_token: Any = ...

class AppEngineHttpRequest(proto.Message):
    http_method: Any = ...
    app_engine_routing: Any = ...
    relative_uri: Any = ...
    headers: Any = ...
    body: Any = ...

class AppEngineRouting(proto.Message):
    service: Any = ...
    version: Any = ...
    instance: Any = ...
    host: Any = ...

class OAuthToken(proto.Message):
    service_account_email: Any = ...
    scope: Any = ...

class OidcToken(proto.Message):
    service_account_email: Any = ...
    audience: Any = ...
