import proto
from typing import Any

class Task(proto.Message):
    class View(proto.Enum):
        VIEW_UNSPECIFIED: int = ...
        BASIC: int = ...
        FULL: int = ...
    name: Any = ...
    app_engine_http_request: Any = ...
    http_request: Any = ...
    schedule_time: Any = ...
    create_time: Any = ...
    dispatch_deadline: Any = ...
    dispatch_count: Any = ...
    response_count: Any = ...
    first_attempt: Any = ...
    last_attempt: Any = ...
    view: Any = ...

class Attempt(proto.Message):
    schedule_time: Any = ...
    dispatch_time: Any = ...
    response_time: Any = ...
    response_status: Any = ...
