// This file is auto-generated by @hey-api/openapi-ts
import type { DefaultError, UseMutationOptions } from '@tanstack/react-query';

import {
  type Options,
  listFavorites,
  listSubscriptions,
  setModelPreferences,
} from '../sdk.gen';
import type {
  ListFavoritesData,
  ListFavoritesResponse,
  ListSubscriptionsData,
  ListSubscriptionsResponse,
  SetModelPreferencesData,
  SetModelPreferencesResponse,
} from '../types.gen';

/**
 * List favorites
 */
export const listFavoritesMutation = (
  options?: Partial<Options<ListFavoritesData>>,
): UseMutationOptions<
  ListFavoritesResponse,
  DefaultError,
  Options<ListFavoritesData>
> => {
  const mutationOptions: UseMutationOptions<
    ListFavoritesResponse,
    DefaultError,
    Options<ListFavoritesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await listFavorites({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set model preferences
 */
export const setModelPreferencesMutation = (
  options?: Partial<Options<SetModelPreferencesData>>,
): UseMutationOptions<
  SetModelPreferencesResponse,
  DefaultError,
  Options<SetModelPreferencesData>
> => {
  const mutationOptions: UseMutationOptions<
    SetModelPreferencesResponse,
    DefaultError,
    Options<SetModelPreferencesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setModelPreferences({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * List subscriptions
 */
export const listSubscriptionsMutation = (
  options?: Partial<Options<ListSubscriptionsData>>,
): UseMutationOptions<
  ListSubscriptionsResponse,
  DefaultError,
  Options<ListSubscriptionsData>
> => {
  const mutationOptions: UseMutationOptions<
    ListSubscriptionsResponse,
    DefaultError,
    Options<ListSubscriptionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await listSubscriptions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
