from google.cloud.ndb import exceptions as exceptions
from typing import Any

_MAX_STRING_LENGTH: int

class BlobKey:
    _blob_key: Any = ...
    def __init__(self, blob_key: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
