from google.cloud.ndb import _legacy_protocol_buffer as ProtocolBuffer
from typing import Any, Dict, List

class PropertyValue_ReferenceValuePathElement(ProtocolBuffer.ProtocolMessage):
    has_type_: int = ...
    type_: bytes = ...
    has_id_: int = ...
    id_: int = ...
    has_name_: int = ...
    name_: bytes = ...
    def type(self) -> bytes: ...
    def set_type(self, x: bytes) -> None: ...
    def has_type(self) -> bool: ...
    def id(self) -> int: ...
    def set_id(self, x: int) -> None: ...
    def has_id(self) -> bool: ...
    def name(self) -> bytes: ...
    def set_name(self, x: bytes) -> None: ...
    def has_name(self) -> bool: ...
    def TryMerge(self, d: Any) -> None: ...

class PropertyValue_PointValue(ProtocolBuffer.ProtocolMessage):
    has_x_: int = ...
    x_: float = ...
    has_y_: int = ...
    y_: float = ...
    def x(self) -> float: ...
    def set_x(self, x: float) -> None: ...
    def has_x(self) -> bool: ...
    def y(self) -> float: ...
    def set_y(self, x: float) -> None: ...
    def has_y(self) -> float: ...
    def TryMerge(self, d: Any) -> None: ...

class PropertyValue_ReferenceValue(ProtocolBuffer.ProtocolMessage):
    has_app_: int = ...
    app_: bytes = ...
    has_name_space_: int = ...
    name_space_: bytes = ...
    has_database_id_: int = ...
    database_id_: bytes = ...
    pathelement_: List["PropertyValue_ReferenceValuePathElement"] = ...
    def __init__(self) -> None: ...
    def app(self) -> bytes: ...
    def set_app(self, x: bytes) -> None: ...
    def has_app(self) -> bool: ...
    def name_space(self) -> bytes: ...
    def set_name_space(self, x: bytes) -> None: ...
    def has_name_space(self) -> bool: ...
    def pathelement_list(self) -> List["PropertyValue_ReferenceValuePathElement"]: ...
    def add_pathelement(self) -> "PropertyValue_ReferenceValuePathElement": ...
    def database_id(self) -> bytes: ...
    def set_database_id(self, x: bytes) -> None: ...
    def has_database_id(self) -> bool: ...
    def TryMerge(self, d: Any) -> None: ...

class PropertyValue(ProtocolBuffer.ProtocolMessage):
    has_int64value_: int = ...
    int64value_: int = ...
    has_booleanvalue_: int = ...
    booleanvalue_: int = ...
    has_stringvalue_: int = ...
    stringvalue_: bytes = ...
    has_doublevalue_: int = ...
    doublevalue_: float = ...
    has_pointvalue_: int = ...
    pointvalue_: "PropertyValue_PointValue" = ...
    has_referencevalue_: int = ...
    referencevalue_: "PropertyValue_ReferenceValue" = ...
    def int64value(self) -> int: ...
    def set_int64value(self, x: int) -> None: ...
    def has_int64value(self) -> bool: ...
    def booleanvalue(self) -> bool: ...
    def set_booleanvalue(self, x: bool) -> None: ...
    def has_booleanvalue(self) -> bool: ...
    def stringvalue(self) -> bytes: ...
    def set_stringvalue(self, x: bytes) -> None: ...
    def has_stringvalue(self) -> bool: ...
    def doublevalue(self) -> float: ...
    def set_doublevalue(self, x: float) -> None: ...
    def has_doublevalue(self) -> float: ...
    def pointvalue(self) -> "PropertyValue_PointValue": ...
    def mutable_pointvalue(self) -> "PropertyValue_PointValue": ...
    def has_pointvalue(self) -> bool: ...
    def referencevalue(self) -> "PropertyValue_ReferenceValue": ...
    def mutable_referencevalue(self) -> "PropertyValue_ReferenceValue": ...
    def has_referencevalue(self) -> bool: ...
    def TryMerge(self, d: Any) -> None: ...

class Property(ProtocolBuffer.ProtocolMessage):
    NO_MEANING: int = ...
    BLOB: int = ...
    TEXT: int = ...
    BYTESTRING: int = ...
    ATOM_CATEGORY: int = ...
    ATOM_LINK: int = ...
    ATOM_TITLE: int = ...
    ATOM_CONTENT: int = ...
    ATOM_SUMMARY: int = ...
    ATOM_AUTHOR: int = ...
    GD_WHEN: int = ...
    GD_EMAIL: int = ...
    GEORSS_POINT: int = ...
    GD_IM: int = ...
    GD_PHONENUMBER: int = ...
    GD_POSTALADDRESS: int = ...
    GD_RATING: int = ...
    BLOBKEY: int = ...
    ENTITY_PROTO: int = ...
    INDEX_VALUE: int = ...
    EMPTY_LIST: int = ...
    _Meaning_NAMES: Any = ...
    def Meaning_Name(cls, x: Any): ...
    Meaning_Name: Any = ...
    has_meaning_: int = ...
    meaning_: int = ...
    has_meaning_uri_: int = ...
    meaning_uri_: bytes = ...
    has_name_: int = ...
    name_: bytes = ...
    has_value_: int = ...
    has_multiple_: int = ...
    multiple_: int = ...
    has_stashed_: int = ...
    stashed_: int = ...
    has_computed_: int = ...
    computed_: int = ...
    value_: "PropertyValue" = ...
    def __init__(self) -> None: ...
    def meaning(self) -> int: ...
    def set_meaning(self, x: int) -> None: ...
    def has_meaning(self) -> bool: ...
    def meaning_uri(self) -> bytes: ...
    def set_meaning_uri(self, x: bytes) -> None: ...
    def has_meaning_uri(self) -> bool: ...
    def name(self) -> bytes   : ...
    def set_name(self, x: bytes) -> None: ...
    def has_name(self) -> bool: ...
    def value(self) -> "PropertyValue": ...
    def mutable_value(self) -> "PropertyValue": ...
    def has_value(self) -> bool: ...
    def multiple(self) -> int: ...
    def set_multiple(self, x: int) -> None: ...
    def has_multiple(self) -> bool: ...
    def stashed(self) -> int: ...
    def set_stashed(self, x: int) -> None: ...
    def has_stashed(self) -> bool: ...
    def computed(self) -> int: ...
    def set_computed(self, x: int) -> None: ...
    def has_computed(self) -> bool: ...
    def TryMerge(self, d: Any) -> None: ...

class Path_Element(ProtocolBuffer.ProtocolMessage):
    has_type_: int = ...
    type_: bytes = ...
    has_id_: int = ...
    id_: int = ...
    has_name_: int = ...
    name_: bytes = ...
    def type(self) -> bytes: ...
    def set_type(self, x: bytes) -> None: ...
    def has_type(self) -> bool: ...
    def id(self) -> int: ...
    def set_id(self, x: int) -> None: ...
    def has_id(self) -> bool: ...
    def name(self) -> bytes: ...
    def set_name(self, x: bytes) -> None: ...
    def has_name(self) -> bool: ...
    def TryMerge(self, d: Any) -> None: ...

class Path(ProtocolBuffer.ProtocolMessage):
    element_: List["Path_Element"] = ...
    def __init__(self) -> None: ...
    def element_list(self) -> List["Path_Element"]: ...
    def add_element(self) -> "Path_Element": ...
    def TryMerge(self, d: Any) -> None: ...

class Reference(ProtocolBuffer.ProtocolMessage):
    has_app_: int = ...
    app_: bytes = ...
    has_name_space_: int = ...
    name_space_: bytes = ...
    has_path_: int = ...
    has_database_id_: int = ...
    database_id_: bytes = ...
    path_: "Path" = ...
    def __init__(self) -> None: ...
    def app(self) -> bytes: ...
    def set_app(self, x: bytes) -> None: ...
    def has_app(self) -> bool: ...
    def name_space(self) -> bytes: ...
    def set_name_space(self, x: bytes) -> None: ...
    def has_name_space(self) -> bool: ...
    def path(self) -> "Path": ...
    def mutable_path(self) -> "Path": ...
    def has_path(self) -> bool: ...
    def database_id(self) -> bytes: ...
    def set_database_id(self, x: bytes) -> None: ...
    def has_database_id(self) -> bool: ...
    def TryMerge(self, d: Any) -> None: ...

class EntityProto(ProtocolBuffer.ProtocolMessage):
    has_key_: int = ...
    has_owner_: int = ...
    owner_: Any = ...
    has_kind_: int = ...
    kind_: int = ...
    has_kind_uri_: int = ...
    kind_uri_: bytes = ...
    key_: "Reference" = ...
    property_: List["Property"] = ...
    def __init__(self) -> None: ...
    def key(self) -> "Reference": ...
    def mutable_key(self) -> "Reference": ...
    def has_key(self) -> bool: ...
    def kind(self) -> int: ...
    def set_kind(self, x: int) -> None: ...
    def has_kind(self) -> bool: ...
    def kind_uri(self) -> bytes: ...
    def set_kind_uri(self, x: bytes) -> None: ...
    def has_kind_uri(self) -> bool: ...
    def property_list(self) -> List["Property"]: ...
    def add_property(self) -> "Property": ...
    def TryMerge(self, d: Any) -> None: ...
    def _get_property_value(self, prop: Any): ...
    def entity_props(self) -> Dict[bytes, Any]: ...
