import threading
from typing import Any

class Error(Exception): ...
class FrontendsNotSupported(Error): ...
class BackgroundThreadLimitReachedError(Error): ...

def start_new_background_thread(target, args, kwargs: Any | None = ...): ...

class BackgroundThread(threading.Thread):
    def start(self) -> None: ...
