# generated by datamodel-codegen:
#   filename:  frc-api-swagger.json

from typing import Literal, TypedDict


class AllianceModelV2(TypedDict):
    number: int
    captain: int | None
    round1: int | None
    round2: int | None
    round3: int | None
    backup: int | None
    backupReplaced: int | None
    name: str | None


type AllianceType = Literal["None", "Red", "Blue"]


type AnnouncementType = Literal["Default", "Green", "Yellow", "Red"]


class ApiIndexModelV2(TypedDict):
    name: str | None
    apiVersion: str | None
    status: str | None
    serviceManifestName: str | None
    serviceManifestVersion: str | None
    codePackageName: str | None
    codePackageVersion: str | None
    currentSeason: int
    maxSeason: int


class AwardAssignmentModelV2(TypedDict):
    awardId: int
    teamId: int | None
    eventId: int | None
    eventDivisionId: int | None
    eventCode: str | None
    name: str | None
    series: int
    teamNumber: int | None
    schoolName: str | None
    fullTeamName: str | None
    person: str | None
    CmpQualifying: bool
    CmpQualifyingReason: str | None


type AwardIds = Literal[
    "ChampionshipFinalistAward",
    "ChampionshipWinnerAward",
    "FIRSTDeansListFinalistAward",
    "FIRSTDeansListAward",
    "HighestRookieSeedAward",
    "ImageryAward",
    "JudgesAward",
    "RegionalFinalistsAward",
    "RegionalWinnersAward",
    "RookieAllStarAward",
    "WoodieFlowersAward",
    "WoodieFlowersFinalistAward",
    "FoundersAward",
    "VolunteeroftheYearAward",
    "DistrictEventWinnerAward",
    "DistrictEventFinalistAward",
    "DistrictChampionshipWinnerAward",
    "DistrictChampionshipFinalistAward",
    "DistrictChampionshipRookieAllStarAward",
    "MakeItLoudAward",
    "ChampionshipDivisionHighestRookieSeedAward",
    "CreativityAward",
    "GraciousProfessionalismAward",
    "QualityAward",
    "RookieInspirationAward",
    "TeamSpiritAward",
    "ConceptAward",
    "DesignersAward",
    "EngineeringDesignAward",
    "RookieDesignAward",
    "GameDesignChallengeFinalistAward",
    "GameDesignChallengeWinnerAward",
    "SkillsCompetitionWinnerAward",
    "SkillsCompetitionFinalistAward",
    "RookieGameChangerAward",
    "FIRSTInnovationChallengeSemiFinalistAward",
    "ChampionshipDivisionWinnerAward",
    "ChampionshipDivisionFinalistAward",
    "RegionalFIRSTImpactAward",
    "DistrictFIRSTImpactAward",
    "FIRSTImpactAward",
    "FIRSTImpactFinalistAward",
    "DistrictChampionshipDeansListSemiFinalistAward",
    "TeamSustainabilityAward",
    "InnovationInControlAward",
    "DistrictChampionshipFIRSTImpactAward",
    "RisingAllStarAward",
    "ExcellenceInEngineeringAward",
    "IndustrialDesignAward",
    "EngineeringInspirationAward",
    "AutonomousAward",
    "DistrictEngineeringInspirationAward",
    "RegionalEngineeringInspirationAward",
    "DistrictChampionshipEngineeringInspirationAward",
]


class DistrictRankingTeamModelV2(TypedDict):
    districtCode: str | None
    teamNumber: int
    rank: int
    totalPoints: int
    event1Code: str | None
    event1Points: float | None
    event2Code: str | None
    event2Points: float | None
    districtCmpCode: str | None
    districtCmpPoints: float | None
    teamAgePoints: int
    adjustmentPoints: int
    qualifiedDistrictCmp: bool
    qualifiedFirstCmp: bool


class EventAnnouncementModel(TypedDict):
    FMSAnnouncementId: str
    Type: AnnouncementType
    Title: str | None
    Text: str | None
    StartTimeUtc: str
    EndTimeUtc: str | None
    DisplayWeb: bool
    DisplayApi: bool
    Author: str | None
    IsDeleted: bool


class EventRankingTeamModelV2(TypedDict):
    rank: int
    teamNumber: int
    sortOrder1: float
    sortOrder2: float
    sortOrder3: float
    sortOrder4: float
    sortOrder5: float
    sortOrder6: float
    wins: int
    losses: int
    ties: int
    qualAverage: float
    dq: int
    matchesPlayed: int


type GamePieceType = Literal["None", "Cone", "Cube"]


type GridRowType = Literal["Top", "Mid", "Bottom"]


class Link(TypedDict):
    Row: GridRowType
    Nodes: list[int] | None


class MatchResultTeamModelV2(TypedDict):
    teamNumber: int
    station: str | None
    dq: bool


type PlayoffTiebreakType = Literal[
    "TrueTie",
    "TieBreakSortOrder1",
    "TieBreakSortOrder2",
    "TieBreakSortOrder3",
    "TieBreakSortOrder4",
    "TieBreakSortOrder5",
    "TieBreakSortOrder6",
    "Unknown",
]


class PlayoffTiebreakTypeStringValueTuple(TypedDict):
    Item1: PlayoffTiebreakType
    Item2: str | None


class ReefRowScore(TypedDict):
    NodeA: bool
    NodeB: bool
    NodeC: bool
    NodeD: bool
    NodeE: bool
    NodeF: bool
    NodeG: bool
    NodeH: bool
    NodeI: bool
    NodeJ: bool
    NodeK: bool
    NodeL: bool


class ReefScore(TypedDict):
    TopRow: ReefRowScore
    MidRow: ReefRowScore
    BotRow: ReefRowScore
    Trough: int


class RegionalDetail(TypedDict):
    TournamentCode: str | None
    TotalPoints: int
    QualificationPerformancePoints: int
    AllianceSelectionPoints: int
    PlayoffAdvancementPoints: int
    AwardPoints: int
    TeamAgePoints: int
    AwardId: AwardIds


type RegionalRankingEventStatusTypes = Literal["NotStarted", "InProgress", "Completed"]


type RegionalRankingStatusTypes = Literal[
    "None",
    "QualifiedAtEventByRanking",
    "QualifiedAtEventByAward",
    "QualifiedFromRegionalPool",
    "Prequalified",
    "NotQualified",
]


class RegionalRankingTeamDetailModelV31(TypedDict):
    Rank: int
    TeamNumber: int
    NameShort: str | None
    Regional1Points: int | None
    Regional1Details: RegionalDetail
    Regional2PointsProjection: int | None
    Regional2Points: int | None
    Regional2Details: RegionalDetail
    RegionalDirectPoints: int | None
    RegionalDirectDetails: RegionalDetail
    TotalPoints: int
    ChampionshipStatus: RegionalRankingStatusTypes
    QualifiedFirstCmp: bool
    QualifiedFirstCmpDate: str | None
    QualifiedFirstCmpEventWeek: int
    QualifiedFirstCmpEventCode: str | None
    QualifiedFirstCmpAwardId: AwardIds
    QualifiedFirstCmpAwardName: str | None
    DeclinedFirstCmp: bool
    DeclinedFirstCmpDate: str | None
    Tiebreakers: dict[str, int] | None
    AdjustPoints: int


class RegionalRankingTeamSummaryModelV31(TypedDict):
    TeamNumber: int
    Rank: int
    TotalPoints: int
    Event1Code: str | None
    Event1Points: int
    Event1AwardId: AwardIds
    Event2Code: str | None
    Event2Points: int
    Event2AwardId: AwardIds
    Event2PointsProjected: int
    EventDirectCode: str | None
    EventDirectPoints: int
    EventDirectAwardId: AwardIds
    AdjustPoints: int
    QualifiedFirstCmp: bool
    QualifiedFirstCmpReason: str | None
    QualifiedFirstCmpDate: str | None
    DeclinedFirstCmp: bool
    DeclinedFirstCmpDate: str | None


class ScheduleHybridModelTeamV2(TypedDict):
    teamNumber: int | None
    station: str | None
    surrogate: bool
    dq: bool | None


class ScheduleHybridModelV2(TypedDict):
    description: str | None
    level: str | None
    matchNumber: int
    startTime: str | None
    scoreRedFinal: int | None
    scoreRedFoul: int | None
    scoreRedAuto: int | None
    scoreBlueFinal: int | None
    scoreBlueFoul: int | None
    scoreBlueAuto: int | None
    tournamentLevel: str | None
    actualStartTime: str | None
    postResultTime: str | None
    Teams: list[ScheduleHybridModelTeamV2] | None


class ScheduleTeamModelV2(TypedDict):
    teamNumber: int | None
    station: str | None
    surrogate: bool


class ScoreDetailModelAlliance2015(TypedDict):
    alliance: str | None
    robotSet: bool
    containerSet: bool
    toteSet: bool
    toteStack: bool
    toteCountFar: int
    toteCountNear: int
    containerCountLevel1: int
    containerCountLevel2: int
    containerCountLevel3: int
    containerCountLevel4: int
    containerCountLevel5: int
    containerCountLevel6: int
    litterCountLandfill: int
    litterCountContainer: int
    litterCountUnprocessed: int
    foulCount: int
    autoPoints: int
    totePoints: int
    containerPoints: int
    litterPoints: int
    teleopPoints: int
    adjustPoints: int
    foulPoints: int
    totalPoints: int


class ScoreDetailModelAlliance2016(TypedDict):
    alliance: str | None
    robot1Auto: str | None
    robot2Auto: str | None
    robot3Auto: str | None
    autoBouldersLow: int
    autoBouldersHigh: int
    teleopBouldersLow: int
    teleopBouldersHigh: int
    towerFaceA: str | None
    towerFaceB: str | None
    towerFaceC: str | None
    towerEndStrength: int
    teleopTowerCaptured: bool
    teleopDefensesBreached: bool
    position1crossings: int
    position2: str | None
    position2crossings: int
    position3: str | None
    position3crossings: int
    position4: str | None
    position4crossings: int
    position5: str | None
    position5crossings: int
    foulCount: int
    techFoulCount: int
    autoPoints: int
    autoReachPoints: int
    autoCrossingPoints: int
    autoBoulderPoints: int
    teleopPoints: int
    teleopCrossingPoints: int
    teleopBoulderPoints: int
    teleopChallengePoints: int
    teleopScalePoints: int
    breachPoints: int
    capturePoints: int
    adjustPoints: int
    foulPoints: int
    totalPoints: int


class ScoreDetailModelAlliance2017(TypedDict):
    alliance: str | None
    robot1Auto: str | None
    robot2Auto: str | None
    robot3Auto: str | None
    autoFuelLow: int
    autoFuelHigh: int
    rotor1Auto: bool
    rotor2Auto: bool
    rotor1Engaged: bool
    rotor2Engaged: bool
    rotor3Engaged: bool
    rotor4Engaged: bool
    teleopFuelLow: int
    teleopFuelHigh: int
    touchpadNear: str | None
    touchpadMiddle: str | None
    touchpadFar: str | None
    kPaRankingPointAchieved: bool
    rotorRankingPointAchieved: bool
    foulCount: int
    techFoulCount: int
    autoPoints: int
    autoMobilityPoints: int
    autoRotorPoints: int
    autoFuelPoints: int
    teleopPoints: int
    teleopFuelPoints: int
    teleopRotorPoints: int
    teleopTakeoffPoints: int
    kPaBonusPoints: int
    rotorBonusPoints: int
    adjustPoints: int
    foulPoints: int
    totalPoints: int


class ScoreDetailModelAlliance2018(TypedDict):
    alliance: str | None
    autoRobot1: str | None
    autoRobot2: str | None
    autoRobot3: str | None
    autoSwitchOwnershipSec: int
    autoScaleOwnershipSec: int
    autoSwitchAtZero: bool
    autoRunPoints: int
    autoOwnershipPoints: int
    autoPoints: int
    teleopSwitchOwnershipSec: int
    teleopScaleOwnershipSec: int
    teleopSwitchBoostSec: int
    teleopScaleBoostSec: int
    teleopSwitchForceSec: int
    teleopScaleForceSec: int
    vaultForceTotal: int
    vaultForcePlayed: int
    vaultLevitateTotal: int
    vaultLevitatePlayed: int
    vaultBoostTotal: int
    vaultBoostPlayed: int
    endgameRobot1: str | None
    endgameRobot2: str | None
    endgameRobot3: str | None
    teleopPoints: int
    teleopOwnershipPoints: int
    vaultPoints: int
    endgamePoints: int
    autoQuestRankingPoint: bool
    faceTheBossRankingPoint: bool
    foulCount: int
    techFoulCount: int
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelAlliance2019(TypedDict):
    alliance: str | None
    preMatchLevelRobot1: str | None
    habLineRobot1: str | None
    endgameRobot1: str | None
    preMatchLevelRobot2: str | None
    habLineRobot2: str | None
    endgameRobot2: str | None
    preMatchLevelRobot3: str | None
    habLineRobot3: str | None
    endgameRobot3: str | None
    topLeftRocketNear: str | None
    topRightRocketNear: str | None
    midLeftRocketNear: str | None
    midRightRocketNear: str | None
    lowLeftRocketNear: str | None
    lowRightRocketNear: str | None
    completedRocketNear: bool
    topLeftRocketFar: str | None
    topRightRocketFar: str | None
    midLeftRocketFar: str | None
    midRightRocketFar: str | None
    lowLeftRocketFar: str | None
    lowRightRocketFar: str | None
    completedRocketFar: bool
    preMatchBay1: str | None
    preMatchBay2: str | None
    preMatchBay3: str | None
    preMatchBay6: str | None
    preMatchBay7: str | None
    preMatchBay8: str | None
    bay1: str | None
    bay2: str | None
    bay3: str | None
    bay4: str | None
    bay5: str | None
    bay6: str | None
    bay7: str | None
    bay8: str | None
    sandStormBonusPoints: int
    autoPoints: int
    hatchPanelPoints: int
    cargoPoints: int
    habClimbPoints: int
    teleopPoints: int
    completeRocketRankingPoint: bool
    habDockingRankingPoint: bool
    foulCount: int
    techFoulCount: int
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelAlliance2020(TypedDict):
    alliance: str | None
    initLineRobot1: str | None
    endgameRobot1: str | None
    initLineRobot2: str | None
    endgameRobot2: str | None
    initLineRobot3: str | None
    endgameRobot3: str | None
    autoCellsBottom: int
    autoCellsOuter: int
    autoCellsInner: int
    teleopCellsBottom: int
    teleopCellsOuter: int
    teleopCellsInner: int
    stage1Activated: bool
    stage2Activated: bool
    stage3Activated: bool
    stage3TargetColor: str | None
    endgameRungIsLevel: str | None
    autoInitLinePoints: int
    autoCellPoints: int
    autoPoints: int
    teleopCellPoints: int
    controlPanelPoints: int
    endgamePoints: int
    teleopPoints: int
    shieldOperationalRankingPoint: bool
    shieldEnergizedRankingPoint: bool
    foulCount: int
    techFoulCount: int
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelAlliance2021(TypedDict):
    alliance: str | None
    initLineRobot1: str | None
    endgameRobot1: str | None
    initLineRobot2: str | None
    endgameRobot2: str | None
    initLineRobot3: str | None
    endgameRobot3: str | None
    autoCellsBottom: int
    autoCellsOuter: int
    autoCellsInner: int
    teleopCellsBottom: int
    teleopCellsOuter: int
    teleopCellsInner: int
    stage1Activated: bool
    stage2Activated: bool
    stage3Activated: bool
    stage3TargetColor: str | None
    endgameRungIsLevel: str | None
    autoInitLinePoints: int
    autoCellPoints: int
    autoPoints: int
    teleopCellPoints: int
    controlPanelPoints: int
    endgamePoints: int
    teleopPoints: int
    shieldOperationalRankingPoint: bool
    shieldEnergizedRankingPoint: bool
    foulCount: int
    techFoulCount: int
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelAlliance2022(TypedDict):
    alliance: str | None
    taxiRobot1: str | None
    endgameRobot1: str | None
    taxiRobot2: str | None
    endgameRobot2: str | None
    taxiRobot3: str | None
    endgameRobot3: str | None
    autoCargoLowerNear: int
    autoCargoLowerFar: int
    autoCargoLowerBlue: int
    autoCargoLowerRed: int
    autoCargoUpperNear: int
    autoCargoUpperFar: int
    autoCargoUpperBlue: int
    autoCargoUpperRed: int
    autoCargoTotal: int
    teleopCargoLowerNear: int
    teleopCargoLowerFar: int
    teleopCargoLowerBlue: int
    teleopCargoLowerRed: int
    teleopCargoUpperNear: int
    teleopCargoUpperFar: int
    teleopCargoUpperBlue: int
    teleopCargoUpperRed: int
    teleopCargoTotal: int
    matchCargoTotal: int
    autoTaxiPoints: int
    autoPoints: int
    autoCargoPoints: int
    quintetAchieved: bool
    teleopPoints: int
    teleopCargoPoints: int
    endgamePoints: int
    cargoBonusRankingPoint: bool
    hangarBonusRankingPoint: bool
    foulCount: int
    techFoulCount: int
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelAlliance2024(TypedDict):
    alliance: str | None
    autoLineRobot1: str | None
    endGameRobot1: str | None
    autoLineRobot2: str | None
    endGameRobot2: str | None
    autoLineRobot3: str | None
    endGameRobot3: str | None
    autoAmpNoteCount: int
    autoSpeakerNoteCount: int
    teleopAmpNoteCount: int
    teleopSpeakerNoteCount: int
    teleopSpeakerNoteAmplifiedCount: int
    micCenterStage: bool
    micStageLeft: bool
    micStageRight: bool
    trapCenterStage: bool
    trapStageLeft: bool
    trapStageRight: bool
    autoPoints: int
    autoAmpNotePoints: int
    autoSpeakerNotePoints: int
    autoTotalNotePoints: int
    autoLeavePoints: int
    teleopPoints: int
    teleopAmpNotePoints: int
    teleopSpeakerNotePoints: int
    teleopSpeakerNoteAmplifiedPoints: int
    teleopTotalNotePoints: int
    endGameParkPoints: int
    endGameOnStagePoints: int
    endGameSpotLightBonusPoints: int
    endGameHarmonyPoints: int
    endGameNoteInTrapPoints: int
    endGameTotalStagePoints: int
    melodyBonusAchieved: bool
    ensembleBonusAchieved: bool
    coopertitionCriteriaMet: bool
    coopNotePlayed: bool
    foulCount: int
    techFoulCount: int
    g206Penalty: bool
    g408Penalty: bool
    g424Penalty: bool
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelAlliance2025(TypedDict):
    alliance: str | None
    autoLineRobot1: str | None
    endGameRobot1: str | None
    autoLineRobot2: str | None
    endGameRobot2: str | None
    autoLineRobot3: str | None
    endGameRobot3: str | None
    autoReef: ReefScore
    autoCoralCount: int
    autoMobilityPoints: int
    autoPoints: int
    autoCoralPoints: int
    teleopReef: ReefScore
    teleopCoralCount: int
    teleopPoints: int
    teleopCoralPoints: int
    algaePoints: int
    netAlgaeCount: int
    wallAlgaeCount: int
    endGameBargePoints: int
    autoBonusAchieved: bool
    coralBonusAchieved: bool
    bargeBonusAchieved: bool
    coopertitionCriteriaMet: bool
    foulCount: int
    techFoulCount: int
    g206Penalty: bool
    g410Penalty: bool
    g418Penalty: bool
    g428Penalty: bool
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelGoal2026(TypedDict):
    AutoCount: int
    transitionCount: int
    shift1Count: int
    shift2Count: int
    shift3Count: int
    shift4Count: int
    endgameCount: int
    teleopCount: int
    totalCount: int
    autoPoints: int
    transitionPoints: int
    shift1Points: int
    shift2Points: int
    shift3Points: int
    shift4Points: int
    endgamePoints: int
    teleopPoints: int
    totalPoints: int


class ScoreDetailModel2015(TypedDict):
    matchLevel: str | None
    matchNumber: int
    coopertition: str | None
    coopertitionPoints: int
    Alliances: list[ScoreDetailModelAlliance2015] | None


class ScoreDetailModel2016(TypedDict):
    matchLevel: str | None
    matchNumber: int
    AudienceGroup: str | None
    Alliances: list[ScoreDetailModelAlliance2016] | None


class ScoreDetailModel2017(TypedDict):
    matchLevel: str | None
    matchNumber: int
    Alliances: list[ScoreDetailModelAlliance2017] | None


class ScoreDetailModel2018(TypedDict):
    matchLevel: str | None
    matchNumber: int
    switchLeftNearColor: str | None
    switchRightNearColor: str | None
    scaleNearColor: str | None
    Alliances: list[ScoreDetailModelAlliance2018] | None


class ScoreDetailsModelReturn2015(TypedDict):
    MatchScores: list[ScoreDetailModel2015] | None


class ScoreDetailsModelReturn2016(TypedDict):
    MatchScores: list[ScoreDetailModel2016] | None


class ScoreDetailsModelReturn2017(TypedDict):
    MatchScores: list[ScoreDetailModel2017] | None


class ScoreDetailsModelReturn2018(TypedDict):
    MatchScores: list[ScoreDetailModel2018] | None


class SeasonAwardModelV2(TypedDict):
    awardId: int
    eventType: str | None
    description: str | None
    forPerson: bool


class SeasonDistrictModelV2(TypedDict):
    code: str | None
    name: str | None


class SeasonEventModelV2(TypedDict):
    code: str | None
    divisionCode: str | None
    name: str | None
    type: str | None
    districtCode: str | None
    venue: str | None
    city: str | None
    stateprov: str | None
    country: str | None
    dateStart: str
    dateEnd: str
    address: str | None
    website: str | None
    webcasts: list[str] | None
    timezone: str | None


class SeasonEventModelV31(TypedDict):
    allianceSelectionType: int
    backupSubstitutionType: int
    playoffBracketType: int
    allianceCount: str | None
    weekNumber: int
    announcements: list[EventAnnouncementModel] | None
    code: str | None
    divisionCode: str | None
    name: str | None
    type: str | None
    districtCode: str | None
    venue: str | None
    city: str | None
    stateprov: str | None
    country: str | None
    dateStart: str
    dateEnd: str
    address: str | None
    website: str | None
    webcasts: list[str] | None
    timezone: str | None


class SeasonSummaryCmpModelV2(TypedDict):
    name: str | None
    startDate: str | None
    location: str | None


class SeasonSummaryModelV2(TypedDict):
    frcChampionship: str | None
    eventCount: int
    gameName: str | None
    kickoff: str | None
    rookieStart: int
    teamCount: int
    FRCChampionships: list[SeasonSummaryCmpModelV2] | None


class SeasonTeamModelV2(TypedDict):
    teamNumber: int
    nameFull: str | None
    nameShort: str | None
    city: str | None
    stateProv: str | None
    country: str | None
    rookieYear: int | None
    robotName: str | None
    districtCode: str | None
    schoolName: str | None
    website: str | None
    homeCMP: str | None


class TeamAvatarModelV2(TypedDict):
    teamNumber: int
    encodedAvatar: str | None


type TournamentLevel = Literal["None", "Practice", "Qualification", "Playoff"]


type TournamentType = Literal[
    "None",
    "Regional",
    "DistrictEvent",
    "DistrictChampionship",
    "ChampionshipSubdivision",
    "ChampionshipDivision",
    "Championship",
    "OffSeason",
    "OffSeasonWithAzureSync",
    "DistrictChampionshipWithLevels",
    "DistrictChampionshipDivision",
    "Remote",
    "DistrictParent",
    "RegionalParent",
]


class AllianceCommunity(TypedDict):
    T: list[GamePieceType] | None
    M: list[GamePieceType] | None
    B: list[GamePieceType] | None


class AllianceListModelV2(TypedDict):
    Alliances: list[AllianceModelV2] | None
    count: int


class AwardAssignmentListModelV2(TypedDict):
    Awards: list[AwardAssignmentModelV2] | None


class DistrictRankingListModelV2(TypedDict):
    districtRanks: list[DistrictRankingTeamModelV2] | None
    rankingCountTotal: int
    rankingCountPage: int
    pageCurrent: int
    pageTotal: int


class EventRankingListModelV2(TypedDict):
    Rankings: list[EventRankingTeamModelV2] | None


class EventRegionalRankingSummaryModelV31(TypedDict):
    SeasonYear: int
    EventCode: str | None
    EventName: str | None
    WeekNumber: int
    Country: str | None
    TeamCapacity: int
    StartDate: str
    EndDate: str
    EventStatus: RegionalRankingEventStatusTypes
    PrequalifiedTeamCount: int
    PriorEventQualifiedTeamCount: int
    RegionalPoolQualifiedTeamCount: int
    EventQualifiedTeamCount: int
    EventNotQualifiedTeamCount: int
    EventNoneCount: int


class EventScheduleHybridModelV2(TypedDict):
    Schedule: list[ScheduleHybridModelV2] | None


class MatchResultModelV2(TypedDict):
    description: str | None
    matchNumber: int
    scoreRedFinal: int
    scoreRedFoul: int
    scoreRedAuto: int
    scoreBlueFinal: int
    scoreBlueFoul: int
    scoreBlueAuto: int
    autoStartTime: str | None
    actualStartTime: str | None
    tournamentLevel: str | None
    postResultTime: str | None
    Teams: list[MatchResultTeamModelV2] | None


class RegionalRankingEventDetailModelV31(TypedDict):
    Rank: int
    TeamNumber: int
    TeamName: str | None
    RegionalPoints: int
    RegionalDetails: RegionalDetail
    ChampionshipStatus: RegionalRankingStatusTypes
    QualifiedFirstCmp: bool
    QualifiedFirstCmpDate: str | None
    QualifiedFirstCmpEventWeek: int
    QualifiedFirstCmpEventCode: str | None
    QualifiedFirstCmpAwardId: AwardIds
    QualifiedFirstCmpAwardName: str | None
    Tiebreakers: dict[str, int] | None


class RegionalRankingTeamDetailListModelV31(TypedDict):
    Season: int
    Teams: list[RegionalRankingTeamDetailModelV31] | None
    TeamCountTotal: int
    TeamCountPage: int
    PageCurrent: int
    PageTotal: int


class RegionalRankingTeamSummaryListModelV31(TypedDict):
    Season: int
    Teams: list[RegionalRankingTeamSummaryModelV31] | None
    TeamCountTotal: int
    TeamCountPage: int
    PageCurrent: int
    PageTotal: int


class ScheduleModelV31(TypedDict):
    PlayoffLevel: str | None
    description: str | None
    startTime: str | None
    matchNumber: int
    field: str | None
    tournamentLevel: str | None
    Teams: list[ScheduleTeamModelV2] | None


class ScoreDetailModelAlliance2023(TypedDict):
    alliance: str | None
    mobilityRobot1: str | None
    autoChargeStationRobot1: str | None
    endGameChargeStationRobot1: str | None
    mobilityRobot2: str | None
    autoChargeStationRobot2: str | None
    endGameChargeStationRobot2: str | None
    mobilityRobot3: str | None
    autoChargeStationRobot3: str | None
    endGameChargeStationRobot3: str | None
    autoCommunity: AllianceCommunity
    autoGamePieceCount: int
    autoMobilityPoints: int
    autoPoints: int
    autoDocked: bool
    autoBridgeState: str | None
    autoGamePiecePoints: int
    autoChargeStationPoints: int
    teleopCommunity: AllianceCommunity
    teleopGamePieceCount: int
    teleopPoints: int
    teleopGamePiecePoints: int
    extraGamePieceCount: int
    endGameChargeStationPoints: int
    endGameParkPoints: int
    endGameBridgeState: str | None
    links: list[Link] | None
    linkPoints: int
    activationBonusAchieved: bool
    sustainabilityBonusAchieved: bool
    coopertitionCriteriaMet: bool
    coopGamePieceCount: int
    totalChargeStationPoints: int
    foulCount: int
    techFoulCount: int
    g405Penalty: bool
    h111Penalty: bool
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModelAlliance2026(TypedDict):
    alliance: str | None
    autoTowerRobot1: str | None
    endGameTowerRobot1: str | None
    autoTowerRobot2: str | None
    endGameTowerRobot2: str | None
    autoTowerRobot3: str | None
    endGameTowerRobot3: str | None
    autoTowerPoints: int
    totalAutoPoints: int
    hubScore: ScoreDetailModelGoal2026
    totalTeleopPoints: int
    endGameTowerPoints: int
    totalTowerPoints: int
    energizedAchieved: bool
    superchargedAchieved: bool
    traversalAchieved: bool
    minorFoulCount: int
    majorFoulCount: int
    g206Penalty: bool
    adjustPoints: int
    foulPoints: int
    rp: int
    totalPoints: int


class ScoreDetailModel2019(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    Alliances: list[ScoreDetailModelAlliance2019] | None


class ScoreDetailModel2020(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    Alliances: list[ScoreDetailModelAlliance2020] | None


class ScoreDetailModel2021(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    Alliances: list[ScoreDetailModelAlliance2021] | None


class ScoreDetailModel2022(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    Alliances: list[ScoreDetailModelAlliance2022] | None


class ScoreDetailModel2023(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    WinningAlliance: AllianceType
    Tiebreaker: PlayoffTiebreakTypeStringValueTuple
    Alliances: list[ScoreDetailModelAlliance2023] | None


class ScoreDetailModel2024(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    WinningAlliance: AllianceType
    Tiebreaker: PlayoffTiebreakTypeStringValueTuple
    coopertitionBonusAchieved: bool
    melodyBonusThresholdCoop: int
    melodyBonusThresholdNonCoop: int
    melodyBonusThreshold: int
    ensembleBonusStagePointsThreshold: int
    ensembleBonusOnStageRobotsThreshold: int
    Alliances: list[ScoreDetailModelAlliance2024] | None


class ScoreDetailModel2025(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    WinningAlliance: AllianceType
    Tiebreaker: PlayoffTiebreakTypeStringValueTuple
    coopertitionBonusAchieved: bool
    coralBonusLevelsThresholdCoop: int
    coralBonusLevelsThresholdNonCoop: int
    coralBonusLevelsThreshold: int
    bargeBonusThreshold: int
    autoBonusCoralThreshold: int
    Alliances: list[ScoreDetailModelAlliance2025] | None


class ScoreDetailModel2026(TypedDict):
    matchLevel: TournamentLevel
    matchNumber: int
    WinningAlliance: AllianceType
    Tiebreaker: PlayoffTiebreakTypeStringValueTuple
    energizedThreshold: int
    superchargedThreshold: int
    traversalThreshold: int
    Alliances: list[ScoreDetailModelAlliance2026] | None


class ScoreDetailsModelReturn2019(TypedDict):
    MatchScores: list[ScoreDetailModel2019] | None


class ScoreDetailsModelReturn2020(TypedDict):
    MatchScores: list[ScoreDetailModel2020] | None


class ScoreDetailsModelReturn2021(TypedDict):
    MatchScores: list[ScoreDetailModel2021] | None


class ScoreDetailsModelReturn2022(TypedDict):
    MatchScores: list[ScoreDetailModel2022] | None


class ScoreDetailsModelReturn2023(TypedDict):
    MatchScores: list[ScoreDetailModel2023] | None


class ScoreDetailsModelReturn2024(TypedDict):
    MatchScores: list[ScoreDetailModel2024] | None


class ScoreDetailsModelReturn2025(TypedDict):
    MatchScores: list[ScoreDetailModel2025] | None


class ScoreDetailsModelReturn2026(TypedDict):
    MatchScores: list[ScoreDetailModel2026] | None


class SeasonAwardListModelV2(TypedDict):
    awards: list[SeasonAwardModelV2] | None


class SeasonDistrictListModelV2(TypedDict):
    districts: list[SeasonDistrictModelV2] | None
    districtCount: int


class SeasonEventListModelV2(TypedDict):
    Events: list[SeasonEventModelV2] | None
    eventCount: int


class SeasonEventListModelV31(TypedDict):
    Events: list[SeasonEventModelV31] | None
    eventCount: int


class SeasonTeamListModelV2(TypedDict):
    teamCountTotal: int
    teamCountPage: int
    pageCurrent: int
    pageTotal: int
    teams: list[SeasonTeamModelV2] | None


class TeamAvatarListingsModelV2(TypedDict):
    teams: list[TeamAvatarModelV2] | None
    teamCountTotal: int
    teamCountPage: int
    pageCurrent: int
    pageTotal: int


class EventRegionalRankingSummaryListModelV31(TypedDict):
    EventSummaries: list[EventRegionalRankingSummaryModelV31] | None
    EventCountTotal: int
    EventCountPage: int
    PageCurrent: int
    PageTotal: int


class MatchResultListModelV2(TypedDict):
    Matches: list[MatchResultModelV2] | None


class RegionalRankingEventDetailListModelV31(TypedDict):
    SeasonYear: int
    EventCode: str | None
    EventName: str | None
    EventStatus: RegionalRankingEventStatusTypes
    TeamDetails: list[RegionalRankingEventDetailModelV31] | None
    TeamCountTotal: int
    TeamCountPage: int
    PageCurrent: int
    PageTotal: int


class ScheduleListModelV31(TypedDict):
    Schedule: list[ScheduleModelV31] | None
