import argparse
from typing import Any, List, Optional

class FastFilesCompleter:
    directories: Any = ...
    def __init__(self, directories: bool=...) -> None: ...
    def __call__(self, prefix: str, **kwargs: Any) -> List[str]: ...

filescompleter: Optional[FastFilesCompleter]

def try_argcomplete(parser: argparse.ArgumentParser) -> None: ...
