from _pytest import outcomes as outcomes
from _pytest.config import hookimpl as hookimpl
from _pytest.config.exceptions import UsageError as UsageError
from typing import Any

def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...

class pytestPDB:
    @classmethod
    def set_trace(cls, *args: Any, **kwargs: Any) -> None: ...

class PdbInvoke:
    def pytest_exception_interact(self, node: Any, call: Any, report: Any) -> None: ...
    def pytest_internalerror(self, excrepr: Any, excinfo: Any) -> None: ...

class PdbTrace:
    def pytest_pyfunc_call(self, pyfuncitem: Any) -> None: ...

def wrap_pytest_function_for_tracing(pyfuncitem: Any) -> None: ...
def maybe_wrap_pytest_function_for_tracing(pyfuncitem: Any) -> None: ...
def post_mortem(t: Any) -> None: ...
