from _pytest.store import StoreKey as StoreKey
from typing import Any

fault_handler_stderr_key: Any

def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...

class FaultHandlerHooks:
    def pytest_configure(self, config: Any) -> None: ...
    def pytest_unconfigure(self, config: Any) -> None: ...
    @staticmethod
    def get_timeout_config_value(config: Any): ...
    def pytest_runtest_protocol(self, item: Any) -> None: ...
    def pytest_enter_pdb(self) -> None: ...
    def pytest_exception_interact(self) -> None: ...
