from .deprecated import COLLECT_DIRECTORY_HOOK as COLLECT_DIRECTORY_HOOK
from _pytest.compat import TYPE_CHECKING as TYPE_CHECKING
from _pytest.main import Session as Session
from typing import Any, Optional

hookspec: Any

def pytest_addhooks(pluginmanager: Any) -> None: ...
def pytest_plugin_registered(plugin: Any, manager: Any) -> None: ...
def pytest_addoption(parser: Any, pluginmanager: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...
def pytest_cmdline_parse(pluginmanager: Any, args: Any) -> None: ...
def pytest_cmdline_preparse(config: Any, args: Any) -> None: ...
def pytest_cmdline_main(config: Any) -> None: ...
def pytest_load_initial_conftests(early_config: Any, parser: Any, args: Any) -> None: ...
def pytest_collection(session: Session) -> Optional[Any]: ...
def pytest_collection_modifyitems(session: Any, config: Any, items: Any) -> None: ...
def pytest_collection_finish(session: Any) -> None: ...
def pytest_ignore_collect(path: Any, config: Any) -> None: ...
def pytest_collect_directory(path: Any, parent: Any) -> None: ...
def pytest_collect_file(path: Any, parent: Any) -> None: ...
def pytest_collectstart(collector: Any) -> None: ...
def pytest_itemcollected(item: Any) -> None: ...
def pytest_collectreport(report: Any) -> None: ...
def pytest_deselected(items: Any) -> None: ...
def pytest_make_collect_report(collector: Any) -> None: ...
def pytest_pycollect_makemodule(path: Any, parent: Any) -> None: ...
def pytest_pycollect_makeitem(collector: Any, name: Any, obj: Any) -> None: ...
def pytest_pyfunc_call(pyfuncitem: Any) -> None: ...
def pytest_generate_tests(metafunc: Any) -> None: ...
def pytest_make_parametrize_id(config: Any, val: Any, argname: Any) -> None: ...
def pytest_runtestloop(session: Any) -> None: ...
def pytest_runtest_protocol(item: Any, nextitem: Any) -> None: ...
def pytest_runtest_logstart(nodeid: Any, location: Any) -> None: ...
def pytest_runtest_logfinish(nodeid: Any, location: Any) -> None: ...
def pytest_runtest_setup(item: Any) -> None: ...
def pytest_runtest_call(item: Any) -> None: ...
def pytest_runtest_teardown(item: Any, nextitem: Any) -> None: ...
def pytest_runtest_makereport(item: Any, call: Any) -> None: ...
def pytest_runtest_logreport(report: Any) -> None: ...
def pytest_report_to_serializable(config: Any, report: Any) -> None: ...
def pytest_report_from_serializable(config: Any, data: Any) -> None: ...
def pytest_fixture_setup(fixturedef: Any, request: Any) -> None: ...
def pytest_fixture_post_finalizer(fixturedef: Any, request: Any) -> None: ...
def pytest_sessionstart(session: Any) -> None: ...
def pytest_sessionfinish(session: Any, exitstatus: Any) -> None: ...
def pytest_unconfigure(config: Any) -> None: ...
def pytest_assertrepr_compare(config: Any, op: Any, left: Any, right: Any) -> None: ...
def pytest_assertion_pass(item: Any, lineno: Any, orig: Any, expl: Any) -> None: ...
def pytest_report_header(config: Any, startdir: Any) -> None: ...
def pytest_report_collectionfinish(config: Any, startdir: Any, items: Any) -> None: ...
def pytest_report_teststatus(report: Any, config: Any) -> None: ...
def pytest_terminal_summary(terminalreporter: Any, exitstatus: Any, config: Any) -> None: ...
def pytest_warning_captured(warning_message: Any, when: Any, item: Any, location: Any) -> None: ...
def pytest_doctest_prepare_content(content: Any) -> None: ...
def pytest_internalerror(excrepr: Any, excinfo: Any) -> None: ...
def pytest_keyboard_interrupt(excinfo: Any) -> None: ...
def pytest_exception_interact(node: Any, call: Any, report: Any) -> None: ...
def pytest_enter_pdb(config: Any, pdb: Any) -> None: ...
def pytest_leave_pdb(config: Any, pdb: Any) -> None: ...
