import py
from _pytest import deprecated as deprecated, nodes as nodes
from _pytest.config import filename_arg as filename_arg
from _pytest.store import StoreKey as StoreKey
from typing import Any

xml_key: Any

class Junit(py.xml.Namespace): ...

illegal_xml_re: Any

def bin_xml_escape(arg: Any): ...
def merge_family(left: Any, right: Any) -> None: ...

families: Any

class _NodeReporter:
    id: Any = ...
    xml: Any = ...
    add_stats: Any = ...
    family: Any = ...
    duration: int = ...
    properties: Any = ...
    nodes: Any = ...
    testcase: Any = ...
    attrs: Any = ...
    def __init__(self, nodeid: Any, xml: Any) -> None: ...
    def append(self, node: Any) -> None: ...
    def add_property(self, name: Any, value: Any) -> None: ...
    def add_attribute(self, name: Any, value: Any) -> None: ...
    def make_properties_node(self): ...
    def record_testreport(self, testreport: Any) -> None: ...
    def to_xml(self): ...
    def write_captured_output(self, report: Any) -> None: ...
    def append_pass(self, report: Any) -> None: ...
    def append_failure(self, report: Any) -> None: ...
    def append_collect_error(self, report: Any) -> None: ...
    def append_collect_skipped(self, report: Any) -> None: ...
    def append_error(self, report: Any) -> None: ...
    def append_skipped(self, report: Any) -> None: ...
    def finalize(self): ...

def record_property(request: Any): ...
def record_xml_attribute(request: Any): ...
def record_testsuite_property(request: Any): ...
def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...
def pytest_unconfigure(config: Any) -> None: ...
def mangle_test_address(address: Any): ...

class LogXML:
    logfile: Any = ...
    prefix: Any = ...
    suite_name: Any = ...
    logging: Any = ...
    log_passing_tests: Any = ...
    report_duration: Any = ...
    family: Any = ...
    stats: Any = ...
    node_reporters: Any = ...
    node_reporters_ordered: Any = ...
    global_properties: Any = ...
    open_reports: Any = ...
    cnt_double_fail_tests: int = ...
    def __init__(self, logfile: Any, prefix: Any, suite_name: str = ..., logging: str = ..., report_duration: str = ..., family: str = ..., log_passing_tests: bool = ...) -> None: ...
    def finalize(self, report: Any) -> None: ...
    def node_reporter(self, report: Any): ...
    def add_stats(self, key: Any) -> None: ...
    def pytest_runtest_logreport(self, report: Any) -> None: ...
    def update_testcase_duration(self, report: Any) -> None: ...
    def pytest_collectreport(self, report: Any) -> None: ...
    def pytest_internalerror(self, excrepr: Any) -> None: ...
    suite_start_time: Any = ...
    def pytest_sessionstart(self) -> None: ...
    def pytest_sessionfinish(self) -> None: ...
    def pytest_terminal_summary(self, terminalreporter: Any) -> None: ...
    def add_global_property(self, name: Any, value: Any) -> None: ...
