from _pytest.store import StoreKey as StoreKey
from typing import Any

pastebinfile_key: Any

def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...
def pytest_unconfigure(config: Any) -> None: ...
def create_new_paste(contents: Any): ...
def pytest_terminal_summary(terminalreporter: Any) -> None: ...
