from _pytest._code.code import ExceptionChainRepr as ExceptionChainRepr, ExceptionInfo as ExceptionInfo, ReprEntry as ReprEntry, ReprEntryNative as ReprEntryNative, ReprExceptionInfo as ReprExceptionInfo, ReprFileLocation as ReprFileLocation, ReprFuncArgs as ReprFuncArgs, ReprLocals as ReprLocals, ReprTraceback as ReprTraceback, TerminalRepr as TerminalRepr
from _pytest._io import TerminalWriter as TerminalWriter
from _pytest.compat import TYPE_CHECKING as TYPE_CHECKING
from _pytest.nodes import Node as Node
from _pytest.outcomes import skip as skip
from _pytest.pathlib import Path as Path
from typing import Any, List, Optional, Tuple

def getslaveinfoline(node: Any): ...

class BaseReport:
    when: Optional[str] = ...
    location: Optional[Tuple[str, Optional[int], str]] = ...
    longrepr: Any = ...
    sections: List[Tuple[str, str]] = ...
    nodeid: str = ...
    def __init__(self, **kw: Any) -> None: ...
    def __getattr__(self, key: str) -> Any: ...
    def toterminal(self, out: Any) -> None: ...
    def get_sections(self, prefix: Any) -> None: ...
    @property
    def longreprtext(self): ...
    @property
    def caplog(self): ...
    @property
    def capstdout(self): ...
    @property
    def capstderr(self): ...
    passed: Any = ...
    failed: Any = ...
    skipped: Any = ...
    @property
    def fspath(self) -> str: ...
    @property
    def count_towards_summary(self): ...
    @property
    def head_line(self): ...

class TestReport(BaseReport):
    __test__: bool = ...
    nodeid: Any = ...
    location: Any = ...
    keywords: Any = ...
    outcome: Any = ...
    longrepr: Any = ...
    when: Any = ...
    user_properties: Any = ...
    sections: Any = ...
    duration: Any = ...
    def __init__(self, nodeid: Any, location: Tuple[str, Optional[int], str], keywords: Any, outcome: Any, longrepr: Any, when: Any, sections: Any=..., duration: Any=..., user_properties: Any=..., **extra: Any) -> None: ...
    @classmethod
    def from_item_and_call(cls: Any, item: Any, call: Any) -> TestReport: ...

class CollectReport(BaseReport):
    when: str = ...
    nodeid: Any = ...
    outcome: Any = ...
    longrepr: Any = ...
    result: Any = ...
    sections: Any = ...
    def __init__(self, nodeid: str, outcome: Any, longrepr: Any, result: List[Node], sections: Any=..., **extra: Any) -> None: ...
    @property
    def location(self): ...

class CollectErrorRepr(TerminalRepr):
    longrepr: Any = ...
    def __init__(self, msg: Any) -> None: ...
    def toterminal(self, out: Any) -> None: ...

def pytest_report_to_serializable(report: Any): ...
def pytest_report_from_serializable(data: Any): ...
