from _pytest.store import StoreKey as StoreKey
from typing import Any

resultlog_key: Any

def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...
def pytest_unconfigure(config: Any) -> None: ...

class ResultLog:
    config: Any = ...
    logfile: Any = ...
    def __init__(self, config: Any, logfile: Any) -> None: ...
    def write_log_entry(self, testpath: Any, lettercode: Any, longrepr: Any) -> None: ...
    def log_outcome(self, report: Any, lettercode: Any, longrepr: Any) -> None: ...
    def pytest_runtest_logreport(self, report: Any) -> None: ...
    def pytest_collectreport(self, report: Any) -> None: ...
    def pytest_internalerror(self, excrepr: Any) -> None: ...
