from typing import Any

def pytest_addoption(parser: Any) -> None: ...
def pytest_fixture_setup(fixturedef: Any, request: Any) -> None: ...
def pytest_fixture_post_finalizer(fixturedef: Any) -> None: ...
def pytest_cmdline_main(config: Any) -> None: ...
