from typing import Any

def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...

class StepwisePlugin:
    config: Any = ...
    active: Any = ...
    session: Any = ...
    report_status: str = ...
    lastfailed: Any = ...
    skip: Any = ...
    def __init__(self, config: Any) -> None: ...
    def pytest_sessionstart(self, session: Any) -> None: ...
    def pytest_collection_modifyitems(
        self, session: Any, config: Any, items: Any
    ) -> None: ...
    def pytest_runtest_logreport(self, report: Any) -> None: ...
    def pytest_report_collectionfinish(self): ...
    def pytest_sessionfinish(self, session: Any) -> None: ...
