from _pytest.main import Session as Session
from typing import Any, Generator

def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...
def catch_warnings_for_item(config: Any, ihook: Any, when: Any, item: Any) -> None: ...
def warning_record_to_str(warning_message: Any): ...
def pytest_runtest_protocol(item: Any) -> None: ...
def pytest_collection(session: Session) -> Generator[None, None, None]: ...
def pytest_terminal_summary(terminalreporter: Any) -> None: ...
def pytest_sessionfinish(session: Any) -> None: ...
