from typing import List, Optional, Text, Tuple

class TransportError(Exception): ...

def get_service_account_token(scopes: List[Text], service_account: Optional[Text] = ...) -> Tuple[Text, int]: ...
