from typing import Any

class Error(Exception): ...
class BackendDeadlineExceeded(Error): ...
class BlobSizeTooLarge(Error): ...
class InternalError(Error): ...
class InvalidScope(Error): ...
class NotAllowed(Error): ...
class OperationNotImplemented(Error): ...

class PublicCertificate:
    key_name: Any
    x509_certificate_pem: Any
    def __init__(self, key_name, x509_certificate_pem) -> None: ...

def create_rpc(deadline: Any | None = ..., callback: Any | None = ...): ...
def make_sign_blob_call(rpc, bytes_to_sign): ...
def make_get_public_certificates_call(rpc): ...
def make_get_service_account_name_call(rpc): ...
def make_get_default_gcs_bucket_name_call(rpc): ...
def sign_blob(bytes_to_sign, deadline: Any | None = ...): ...
def get_public_certificates(deadline: Any | None = ...): ...
def get_service_account_name(deadline: Any | None = ...): ...
def get_default_gcs_bucket_name(deadline: Any | None = ...): ...
def get_application_id(): ...
def get_default_version_hostname(): ...
def get_access_token(scopes, service_account_id: Any | None = ...): ...
