from google.appengine.api import urlfetch as urlfetch
from google.appengine.api.app_identity import app_identity_service_pb2 as app_identity_service_pb2, app_identity_stub_base as app_identity_stub_base
from google.appengine.runtime import apiproxy_errors as apiproxy_errors
from typing import Any

def BitStringToByteString(bs): ...

class KeyBasedAppIdentityServiceStub(app_identity_stub_base.AppIdentityServiceStubBase):
    THREADSAFE: bool
    def __init__(self, service_name: str = ..., email_address: Any | None = ..., private_key_path: Any | None = ..., oauth_url: Any | None = ...) -> None: ...
    def SetDefaultGcsBucketName(self, default_gcs_bucket_name) -> None: ...
    def get_service_account_token(self, scopes, service_account: Any | None = ...): ...
    def get_service_account_name(self): ...
