from google.appengine.api import urlfetch as urlfetch
from google.appengine.api.app_identity import app_identity_service_pb2 as app_identity_service_pb2, app_identity_stub_base as app_identity_stub_base
from google.appengine.runtime import apiproxy_errors as apiproxy_errors
from google.auth import app_engine as app_engine, exceptions as exceptions
from typing import Any

def BitStringToByteString(bs): ...

class DefaultCredentialsBasedAppIdentityServiceStub(app_identity_stub_base.AppIdentityServiceStubBase):
    THREADSAFE: bool
    def __init__(self, service_name: str = ...) -> None: ...
    def SetDefaultGcsBucketName(self, default_gcs_bucket_name) -> None: ...
    def get_service_account_token(self, scopes, service_account: Any | None = ...): ...
    def get_service_account_name(self): ...

def TimestampFromNaiveUtcDatetime(dt): ...
