from firebase_admin import _auth_utils
from typing import Any, Optional

MAX_LIST_CONFIGS_RESULTS: int

class ProviderConfig:
    def __init__(self, data: Any) -> None: ...
    @property
    def provider_id(self): ...
    @property
    def display_name(self): ...
    @property
    def enabled(self): ...

class OIDCProviderConfig(ProviderConfig):
    @property
    def issuer(self): ...
    @property
    def client_id(self): ...

class SAMLProviderConfig(ProviderConfig):
    @property
    def idp_entity_id(self): ...
    @property
    def sso_url(self): ...
    @property
    def x509_certificates(self): ...
    @property
    def callback_url(self): ...
    @property
    def rp_entity_id(self): ...

class ListProviderConfigsPage:
    def __init__(self, download: Any, page_token: Any, max_results: Any) -> None: ...
    @property
    def provider_configs(self) -> None: ...
    @property
    def next_page_token(self): ...
    @property
    def has_next_page(self): ...
    def get_next_page(self): ...
    def iterate_all(self): ...

class _ListOIDCProviderConfigsPage(ListProviderConfigsPage):
    @property
    def provider_configs(self): ...

class _ListSAMLProviderConfigsPage(ListProviderConfigsPage):
    @property
    def provider_configs(self): ...

class _ProviderConfigIterator(_auth_utils.PageIterator):
    @property
    def items(self): ...

class ProviderConfigClient:
    PROVIDER_CONFIG_URL: str = ...
    http_client: Any = ...
    base_url: Any = ...
    def __init__(self, http_client: Any, project_id: Any, tenant_id: Optional[Any] = ...) -> None: ...
    def get_oidc_provider_config(self, provider_id: Any): ...
    def create_oidc_provider_config(self, provider_id: Any, client_id: Any, issuer: Any, display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def update_oidc_provider_config(self, provider_id: Any, client_id: Optional[Any] = ..., issuer: Optional[Any] = ..., display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def delete_oidc_provider_config(self, provider_id: Any) -> None: ...
    def list_oidc_provider_configs(self, page_token: Optional[Any] = ..., max_results: Any = ...): ...
    def get_saml_provider_config(self, provider_id: Any): ...
    def create_saml_provider_config(self, provider_id: Any, idp_entity_id: Any, sso_url: Any, x509_certificates: Any, rp_entity_id: Any, callback_url: Any, display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def update_saml_provider_config(self, provider_id: Any, idp_entity_id: Optional[Any] = ..., sso_url: Optional[Any] = ..., x509_certificates: Optional[Any] = ..., rp_entity_id: Optional[Any] = ..., callback_url: Optional[Any] = ..., display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def delete_saml_provider_config(self, provider_id: Any) -> None: ...
    def list_saml_provider_configs(self, page_token: Optional[Any] = ..., max_results: Any = ...): ...
