from typing import Any, Optional

class Client:
    def __init__(self, app: Any, tenant_id: Optional[Any] = ...) -> None: ...
    @property
    def tenant_id(self): ...
    def create_custom_token(self, uid: Any, developer_claims: Optional[Any] = ...): ...
    def verify_id_token(self, id_token: Any, check_revoked: bool = ...): ...
    def revoke_refresh_tokens(self, uid: Any) -> None: ...
    def get_user(self, uid: Any): ...
    def get_user_by_email(self, email: Any): ...
    def get_user_by_phone_number(self, phone_number: Any): ...
    def get_users(self, identifiers: Any): ...
    def list_users(self, page_token: Optional[Any] = ..., max_results: Any = ...): ...
    def create_user(self, **kwargs: Any): ...
    def update_user(self, uid: Any, **kwargs: Any): ...
    def set_custom_user_claims(self, uid: Any, custom_claims: Any) -> None: ...
    def delete_user(self, uid: Any) -> None: ...
    def delete_users(self, uids: Any): ...
    def import_users(self, users: Any, hash_alg: Optional[Any] = ...): ...
    def generate_password_reset_link(self, email: Any, action_code_settings: Optional[Any] = ...): ...
    def generate_email_verification_link(self, email: Any, action_code_settings: Optional[Any] = ...): ...
    def generate_sign_in_with_email_link(self, email: Any, action_code_settings: Any): ...
    def get_oidc_provider_config(self, provider_id: Any): ...
    def create_oidc_provider_config(self, provider_id: Any, client_id: Any, issuer: Any, display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def update_oidc_provider_config(self, provider_id: Any, client_id: Optional[Any] = ..., issuer: Optional[Any] = ..., display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def delete_oidc_provider_config(self, provider_id: Any) -> None: ...
    def list_oidc_provider_configs(self, page_token: Optional[Any] = ..., max_results: Any = ...): ...
    def get_saml_provider_config(self, provider_id: Any): ...
    def create_saml_provider_config(self, provider_id: Any, idp_entity_id: Any, sso_url: Any, x509_certificates: Any, rp_entity_id: Any, callback_url: Any, display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def update_saml_provider_config(self, provider_id: Any, idp_entity_id: Optional[Any] = ..., sso_url: Optional[Any] = ..., x509_certificates: Optional[Any] = ..., rp_entity_id: Optional[Any] = ..., callback_url: Optional[Any] = ..., display_name: Optional[Any] = ..., enabled: Optional[Any] = ...): ...
    def delete_saml_provider_config(self, provider_id: Any) -> None: ...
    def list_saml_provider_configs(self, page_token: Optional[Any] = ..., max_results: Any = ...): ...
