from typing import Any, Optional

DEFAULT_RETRY_CONFIG: Any
DEFAULT_TIMEOUT_SECONDS: int

class HttpClient:
    def __init__(self, credential: Optional[Any] = ..., session: Optional[Any] = ..., base_url: str = ..., headers: Optional[Any] = ..., retries: Any = ..., timeout: Any = ...) -> None: ...
    @property
    def session(self): ...
    @property
    def base_url(self): ...
    @property
    def timeout(self): ...
    def parse_body(self, resp: Any) -> None: ...
    def request(self, method: Any, url: Any, **kwargs: Any): ...
    def headers(self, method: Any, url: Any, **kwargs: Any): ...
    def body_and_response(self, method: Any, url: Any, **kwargs: Any): ...
    def body(self, method: Any, url: Any, **kwargs: Any): ...
    def headers_and_body(self, method: Any, url: Any, **kwargs: Any): ...
    def close(self) -> None: ...

class JsonHttpClient(HttpClient):
    def __init__(self, **kwargs: Any) -> None: ...
    def parse_body(self, resp: Any): ...
