from typing import Any

class UserIdentifier: ...

class UidIdentifier(UserIdentifier):
    def __init__(self, uid: Any) -> None: ...
    @property
    def uid(self): ...

class EmailIdentifier(UserIdentifier):
    def __init__(self, email: Any) -> None: ...
    @property
    def email(self): ...

class PhoneIdentifier(UserIdentifier):
    def __init__(self, phone_number: Any) -> None: ...
    @property
    def phone_number(self): ...

class ProviderIdentifier(UserIdentifier):
    def __init__(self, provider_id: Any, provider_uid: Any) -> None: ...
    @property
    def provider_id(self): ...
    @property
    def provider_uid(self): ...
