from firebase_admin import exceptions as exceptions
from typing import Any, Optional

def get_app_service(app: Any, name: Any, initializer: Any): ...
def handle_platform_error_from_requests(error: Any, handle_func: Optional[Any] = ...): ...
def handle_operation_error(error: Any): ...
def handle_requests_error(error: Any, message: Optional[Any] = ..., code: Optional[Any] = ...): ...
def handle_platform_error_from_googleapiclient(error: Any, handle_func: Optional[Any] = ...): ...
def handle_googleapiclient_error(error: Any, message: Optional[Any] = ..., code: Optional[Any] = ..., http_response: Optional[Any] = ...): ...
