from collections import namedtuple
from typing import Any

AccessTokenInfo = namedtuple('AccessTokenInfo', ['access_token', 'expiry'])

class Base:
    def get_access_token(self): ...
    def get_credential(self) -> None: ...

class Certificate(Base):
    def __init__(self, cert: Any) -> None: ...
    @property
    def project_id(self): ...
    @property
    def signer(self): ...
    @property
    def service_account_email(self): ...
    def get_credential(self): ...

class ApplicationDefault(Base):
    def __init__(self) -> None: ...
    def get_credential(self): ...
    @property
    def project_id(self): ...

class RefreshToken(Base):
    def __init__(self, refresh_token: Any) -> None: ...
    @property
    def client_id(self): ...
    @property
    def client_secret(self): ...
    @property
    def refresh_token(self): ...
    def get_credential(self): ...
