from typing import Any, Optional

def delete_instance_id(instance_id: Any, app: Optional[Any] = ...) -> None: ...

class _InstanceIdService:
    error_codes: Any = ...
    def __init__(self, app: Any) -> None: ...
    def delete_instance_id(self, instance_id: Any) -> None: ...
