from typing import Any, Optional

def bucket(name: Optional[Any] = ..., app: Optional[Any] = ...): ...

class _StorageClient:
    def __init__(self, credentials: Any, project: Any, default_bucket: Any) -> None: ...
    @classmethod
    def from_app(cls, app: Any): ...
    def bucket(self, name: Optional[Any] = ...): ...
