/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as Match_suggestionRouteImport } from './routes/match_suggestion'
import { Route as GamedayRouteImport } from './routes/gameday'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApidocsRouteImport } from './routes/apidocs'
import { Route as AddDataRouteImport } from './routes/add-data'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsChar123PgNumChar125RouteImport } from './routes/teams.{-$pgNum}'
import { Route as MatchMatchKeyRouteImport } from './routes/match.$matchKey'
import { Route as LocalDebugRouteImport } from './routes/local.debug'
import { Route as LegalPrivacyRouteImport } from './routes/legal_.privacy'
import { Route as InsightsChar123YearChar125RouteImport } from './routes/insights.{-$year}'
import { Route as EventsChar123YearChar125RouteImport } from './routes/events.{-$year}'
import { Route as EventEventKeyRouteImport } from './routes/event.$eventKey'
import { Route as ApidocsV3RouteImport } from './routes/apidocs_.v3'
import { Route as TeamTeamNumberChar123YearChar125RouteImport } from './routes/team.$teamNumber.{-$year}'
import { Route as TeamTeamNumberStatsRouteImport } from './routes/team.$teamNumber.stats'
import { Route as TeamTeamNumberHistoryRouteImport } from './routes/team.$teamNumber.history'
import { Route as DistrictDistrictAbbreviationChar123YearChar125RouteImport } from './routes/district.$districtAbbreviation.{-$year}'
import { Route as DistrictDistrictAbbreviationInsightsRouteImport } from './routes/district.$districtAbbreviation.insights'

const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const Match_suggestionRoute = Match_suggestionRouteImport.update({
  id: '/match_suggestion',
  path: '/match_suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const GamedayRoute = GamedayRouteImport.update({
  id: '/gameday',
  path: '/gameday',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApidocsRoute = ApidocsRouteImport.update({
  id: '/apidocs',
  path: '/apidocs',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDataRoute = AddDataRouteImport.update({
  id: '/add-data',
  path: '/add-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsChar123PgNumChar125Route =
  TeamsChar123PgNumChar125RouteImport.update({
    id: '/teams/{-$pgNum}',
    path: '/teams/{-$pgNum}',
    getParentRoute: () => rootRouteImport,
  } as any)
const MatchMatchKeyRoute = MatchMatchKeyRouteImport.update({
  id: '/match/$matchKey',
  path: '/match/$matchKey',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalDebugRoute = LocalDebugRouteImport.update({
  id: '/local/debug',
  path: '/local/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal_/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsChar123YearChar125Route =
  InsightsChar123YearChar125RouteImport.update({
    id: '/insights/{-$year}',
    path: '/insights/{-$year}',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsChar123YearChar125Route =
  EventsChar123YearChar125RouteImport.update({
    id: '/events/{-$year}',
    path: '/events/{-$year}',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventEventKeyRoute = EventEventKeyRouteImport.update({
  id: '/event/$eventKey',
  path: '/event/$eventKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApidocsV3Route = ApidocsV3RouteImport.update({
  id: '/apidocs_/v3',
  path: '/apidocs/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamNumberChar123YearChar125Route =
  TeamTeamNumberChar123YearChar125RouteImport.update({
    id: '/team/$teamNumber/{-$year}',
    path: '/team/$teamNumber/{-$year}',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamNumberStatsRoute = TeamTeamNumberStatsRouteImport.update({
  id: '/team/$teamNumber/stats',
  path: '/team/$teamNumber/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamNumberHistoryRoute = TeamTeamNumberHistoryRouteImport.update({
  id: '/team/$teamNumber/history',
  path: '/team/$teamNumber/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictDistrictAbbreviationChar123YearChar125Route =
  DistrictDistrictAbbreviationChar123YearChar125RouteImport.update({
    id: '/district/$districtAbbreviation/{-$year}',
    path: '/district/$districtAbbreviation/{-$year}',
    getParentRoute: () => rootRouteImport,
  } as any)
const DistrictDistrictAbbreviationInsightsRoute =
  DistrictDistrictAbbreviationInsightsRouteImport.update({
    id: '/district/$districtAbbreviation/insights',
    path: '/district/$districtAbbreviation/insights',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/add-data': typeof AddDataRoute
  '/apidocs': typeof ApidocsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gameday': typeof GamedayRoute
  '/match_suggestion': typeof Match_suggestionRoute
  '/thanks': typeof ThanksRoute
  '/apidocs/v3': typeof ApidocsV3Route
  '/event/$eventKey': typeof EventEventKeyRoute
  '/events/{-$year}': typeof EventsChar123YearChar125Route
  '/insights/{-$year}': typeof InsightsChar123YearChar125Route
  '/legal/privacy': typeof LegalPrivacyRoute
  '/local/debug': typeof LocalDebugRoute
  '/match/$matchKey': typeof MatchMatchKeyRoute
  '/teams/{-$pgNum}': typeof TeamsChar123PgNumChar125Route
  '/district/$districtAbbreviation/insights': typeof DistrictDistrictAbbreviationInsightsRoute
  '/district/$districtAbbreviation/{-$year}': typeof DistrictDistrictAbbreviationChar123YearChar125Route
  '/team/$teamNumber/history': typeof TeamTeamNumberHistoryRoute
  '/team/$teamNumber/stats': typeof TeamTeamNumberStatsRoute
  '/team/$teamNumber/{-$year}': typeof TeamTeamNumberChar123YearChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/add-data': typeof AddDataRoute
  '/apidocs': typeof ApidocsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gameday': typeof GamedayRoute
  '/match_suggestion': typeof Match_suggestionRoute
  '/thanks': typeof ThanksRoute
  '/apidocs/v3': typeof ApidocsV3Route
  '/event/$eventKey': typeof EventEventKeyRoute
  '/events/{-$year}': typeof EventsChar123YearChar125Route
  '/insights/{-$year}': typeof InsightsChar123YearChar125Route
  '/legal/privacy': typeof LegalPrivacyRoute
  '/local/debug': typeof LocalDebugRoute
  '/match/$matchKey': typeof MatchMatchKeyRoute
  '/teams/{-$pgNum}': typeof TeamsChar123PgNumChar125Route
  '/district/$districtAbbreviation/insights': typeof DistrictDistrictAbbreviationInsightsRoute
  '/district/$districtAbbreviation/{-$year}': typeof DistrictDistrictAbbreviationChar123YearChar125Route
  '/team/$teamNumber/history': typeof TeamTeamNumberHistoryRoute
  '/team/$teamNumber/stats': typeof TeamTeamNumberStatsRoute
  '/team/$teamNumber/{-$year}': typeof TeamTeamNumberChar123YearChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/add-data': typeof AddDataRoute
  '/apidocs': typeof ApidocsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gameday': typeof GamedayRoute
  '/match_suggestion': typeof Match_suggestionRoute
  '/thanks': typeof ThanksRoute
  '/apidocs_/v3': typeof ApidocsV3Route
  '/event/$eventKey': typeof EventEventKeyRoute
  '/events/{-$year}': typeof EventsChar123YearChar125Route
  '/insights/{-$year}': typeof InsightsChar123YearChar125Route
  '/legal_/privacy': typeof LegalPrivacyRoute
  '/local/debug': typeof LocalDebugRoute
  '/match/$matchKey': typeof MatchMatchKeyRoute
  '/teams/{-$pgNum}': typeof TeamsChar123PgNumChar125Route
  '/district/$districtAbbreviation/insights': typeof DistrictDistrictAbbreviationInsightsRoute
  '/district/$districtAbbreviation/{-$year}': typeof DistrictDistrictAbbreviationChar123YearChar125Route
  '/team/$teamNumber/history': typeof TeamTeamNumberHistoryRoute
  '/team/$teamNumber/stats': typeof TeamTeamNumberStatsRoute
  '/team/$teamNumber/{-$year}': typeof TeamTeamNumberChar123YearChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/add-data'
    | '/apidocs'
    | '/contact'
    | '/donate'
    | '/gameday'
    | '/match_suggestion'
    | '/thanks'
    | '/apidocs/v3'
    | '/event/$eventKey'
    | '/events/{-$year}'
    | '/insights/{-$year}'
    | '/legal/privacy'
    | '/local/debug'
    | '/match/$matchKey'
    | '/teams/{-$pgNum}'
    | '/district/$districtAbbreviation/insights'
    | '/district/$districtAbbreviation/{-$year}'
    | '/team/$teamNumber/history'
    | '/team/$teamNumber/stats'
    | '/team/$teamNumber/{-$year}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/add-data'
    | '/apidocs'
    | '/contact'
    | '/donate'
    | '/gameday'
    | '/match_suggestion'
    | '/thanks'
    | '/apidocs/v3'
    | '/event/$eventKey'
    | '/events/{-$year}'
    | '/insights/{-$year}'
    | '/legal/privacy'
    | '/local/debug'
    | '/match/$matchKey'
    | '/teams/{-$pgNum}'
    | '/district/$districtAbbreviation/insights'
    | '/district/$districtAbbreviation/{-$year}'
    | '/team/$teamNumber/history'
    | '/team/$teamNumber/stats'
    | '/team/$teamNumber/{-$year}'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/add-data'
    | '/apidocs'
    | '/contact'
    | '/donate'
    | '/gameday'
    | '/match_suggestion'
    | '/thanks'
    | '/apidocs_/v3'
    | '/event/$eventKey'
    | '/events/{-$year}'
    | '/insights/{-$year}'
    | '/legal_/privacy'
    | '/local/debug'
    | '/match/$matchKey'
    | '/teams/{-$pgNum}'
    | '/district/$districtAbbreviation/insights'
    | '/district/$districtAbbreviation/{-$year}'
    | '/team/$teamNumber/history'
    | '/team/$teamNumber/stats'
    | '/team/$teamNumber/{-$year}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AddDataRoute: typeof AddDataRoute
  ApidocsRoute: typeof ApidocsRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GamedayRoute: typeof GamedayRoute
  Match_suggestionRoute: typeof Match_suggestionRoute
  ThanksRoute: typeof ThanksRoute
  ApidocsV3Route: typeof ApidocsV3Route
  EventEventKeyRoute: typeof EventEventKeyRoute
  EventsChar123YearChar125Route: typeof EventsChar123YearChar125Route
  InsightsChar123YearChar125Route: typeof InsightsChar123YearChar125Route
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LocalDebugRoute: typeof LocalDebugRoute
  MatchMatchKeyRoute: typeof MatchMatchKeyRoute
  TeamsChar123PgNumChar125Route: typeof TeamsChar123PgNumChar125Route
  DistrictDistrictAbbreviationInsightsRoute: typeof DistrictDistrictAbbreviationInsightsRoute
  DistrictDistrictAbbreviationChar123YearChar125Route: typeof DistrictDistrictAbbreviationChar123YearChar125Route
  TeamTeamNumberHistoryRoute: typeof TeamTeamNumberHistoryRoute
  TeamTeamNumberStatsRoute: typeof TeamTeamNumberStatsRoute
  TeamTeamNumberChar123YearChar125Route: typeof TeamTeamNumberChar123YearChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match_suggestion': {
      id: '/match_suggestion'
      path: '/match_suggestion'
      fullPath: '/match_suggestion'
      preLoaderRoute: typeof Match_suggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameday': {
      id: '/gameday'
      path: '/gameday'
      fullPath: '/gameday'
      preLoaderRoute: typeof GamedayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apidocs': {
      id: '/apidocs'
      path: '/apidocs'
      fullPath: '/apidocs'
      preLoaderRoute: typeof ApidocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-data': {
      id: '/add-data'
      path: '/add-data'
      fullPath: '/add-data'
      preLoaderRoute: typeof AddDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/{-$pgNum}': {
      id: '/teams/{-$pgNum}'
      path: '/teams/{-$pgNum}'
      fullPath: '/teams/{-$pgNum}'
      preLoaderRoute: typeof TeamsChar123PgNumChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchKey': {
      id: '/match/$matchKey'
      path: '/match/$matchKey'
      fullPath: '/match/$matchKey'
      preLoaderRoute: typeof MatchMatchKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/debug': {
      id: '/local/debug'
      path: '/local/debug'
      fullPath: '/local/debug'
      preLoaderRoute: typeof LocalDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal_/privacy': {
      id: '/legal_/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/{-$year}': {
      id: '/insights/{-$year}'
      path: '/insights/{-$year}'
      fullPath: '/insights/{-$year}'
      preLoaderRoute: typeof InsightsChar123YearChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/{-$year}': {
      id: '/events/{-$year}'
      path: '/events/{-$year}'
      fullPath: '/events/{-$year}'
      preLoaderRoute: typeof EventsChar123YearChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventKey': {
      id: '/event/$eventKey'
      path: '/event/$eventKey'
      fullPath: '/event/$eventKey'
      preLoaderRoute: typeof EventEventKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apidocs_/v3': {
      id: '/apidocs_/v3'
      path: '/apidocs/v3'
      fullPath: '/apidocs/v3'
      preLoaderRoute: typeof ApidocsV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamNumber/{-$year}': {
      id: '/team/$teamNumber/{-$year}'
      path: '/team/$teamNumber/{-$year}'
      fullPath: '/team/$teamNumber/{-$year}'
      preLoaderRoute: typeof TeamTeamNumberChar123YearChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamNumber/stats': {
      id: '/team/$teamNumber/stats'
      path: '/team/$teamNumber/stats'
      fullPath: '/team/$teamNumber/stats'
      preLoaderRoute: typeof TeamTeamNumberStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamNumber/history': {
      id: '/team/$teamNumber/history'
      path: '/team/$teamNumber/history'
      fullPath: '/team/$teamNumber/history'
      preLoaderRoute: typeof TeamTeamNumberHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/$districtAbbreviation/{-$year}': {
      id: '/district/$districtAbbreviation/{-$year}'
      path: '/district/$districtAbbreviation/{-$year}'
      fullPath: '/district/$districtAbbreviation/{-$year}'
      preLoaderRoute: typeof DistrictDistrictAbbreviationChar123YearChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/$districtAbbreviation/insights': {
      id: '/district/$districtAbbreviation/insights'
      path: '/district/$districtAbbreviation/insights'
      fullPath: '/district/$districtAbbreviation/insights'
      preLoaderRoute: typeof DistrictDistrictAbbreviationInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AddDataRoute: AddDataRoute,
  ApidocsRoute: ApidocsRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GamedayRoute: GamedayRoute,
  Match_suggestionRoute: Match_suggestionRoute,
  ThanksRoute: ThanksRoute,
  ApidocsV3Route: ApidocsV3Route,
  EventEventKeyRoute: EventEventKeyRoute,
  EventsChar123YearChar125Route: EventsChar123YearChar125Route,
  InsightsChar123YearChar125Route: InsightsChar123YearChar125Route,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LocalDebugRoute: LocalDebugRoute,
  MatchMatchKeyRoute: MatchMatchKeyRoute,
  TeamsChar123PgNumChar125Route: TeamsChar123PgNumChar125Route,
  DistrictDistrictAbbreviationInsightsRoute:
    DistrictDistrictAbbreviationInsightsRoute,
  DistrictDistrictAbbreviationChar123YearChar125Route:
    DistrictDistrictAbbreviationChar123YearChar125Route,
  TeamTeamNumberHistoryRoute: TeamTeamNumberHistoryRoute,
  TeamTeamNumberStatsRoute: TeamTeamNumberStatsRoute,
  TeamTeamNumberChar123YearChar125Route: TeamTeamNumberChar123YearChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
