def GetTag(node): ...
def GetChild(node, tag): ...
def BooleanValue(node_text): ...
def GetAttribute(node, attr): ...
def GetChildNodeText(node, child_tag, default: str = ...): ...
def GetNodeText(node): ...
def GetNodes(node, match_tag): ...
