"""Type stubs for numpy 2.x"""

from typing import Any, List, Optional, Tuple, Union, overload

# Main namespace
class ndarray:
    def __init__(self, shape: Union[int, Tuple[int, ...]], dtype: Optional[Any] = None) -> None: ...
    def dot(self, b: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...

def zeros(shape: Union[int, Tuple[int, ...]], dtype: Optional[Any] = None) -> ndarray: ...
def ones(shape: Union[int, Tuple[int, ...]], dtype: Optional[Any] = None) -> ndarray: ...
def asarray(a: Any, dtype: Optional[Any] = None) -> ndarray: ...
def mean(a: Any, axis: Optional[Any] = None) -> Any: ...
def median(a: Any, axis: Optional[Any] = None) -> Any: ...
def var(a: Any, axis: Optional[Any] = None) -> Any: ...
def std(a: Any, axis: Optional[Any] = None) -> Any: ...
def dot(a: Any, b: Any) -> Any: ...
def diag(v: Any) -> ndarray: ...
def percentile(a: Any, q: Any, axis: Optional[Any] = None) -> Any: ...
def sqrt(x: Any) -> Any: ...
def exp(x: Any) -> Any: ...

# linalg submodule
class linalg:
    @staticmethod
    def inv(a: Any) -> ndarray: ...
    @staticmethod
    def pinv(a: Any) -> ndarray: ...

# random submodule
class random:
    @staticmethod
    def uniform(low: float = 0.0, high: float = 1.0, size: Optional[Any] = None) -> Any: ...
    @staticmethod
    def normal(loc: float = 0.0, scale: float = 1.0, size: Optional[Any] = None) -> Any: ...

# Constants and types
__version__: str
pi: float
e: float
inf: float
nan: float

array_api_version: str

class dtype: ...
class generic: ...

int_: type
float_: type
bool_: type
complex_: type

int8: type
int16: type
int32: type
int64: type
uint8: type
uint16: type
uint32: type
uint64: type
float16: type
float32: type
float64: type
