// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  ListFavoritesData,
  ListFavoritesResponses,
  ListSubscriptionsData,
  ListSubscriptionsResponses,
  SetModelPreferencesData,
  SetModelPreferencesResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List favorites
 */
export const listFavorites = <ThrowOnError extends boolean = false>(
  options?: Options<ListFavoritesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ListFavoritesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/favorites/list',
    ...options,
  });
};

/**
 * Set model preferences
 */
export const setModelPreferences = <ThrowOnError extends boolean = false>(
  options: Options<SetModelPreferencesData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SetModelPreferencesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/model/setPreferences',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List subscriptions
 */
export const listSubscriptions = <ThrowOnError extends boolean = false>(
  options?: Options<ListSubscriptionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ListSubscriptionsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/subscriptions/list',
    ...options,
  });
};
