from typing import Any

class Error(Exception): ...
class RPCFailedError(Error): ...
class CallNotFoundError(Error): ...
class ArgumentError(Error): ...
class DeadlineExceededError(Error): ...
class CancelledError(Error): ...

class ApplicationError(Error):
    application_error: Any
    error_detail: Any
    def __init__(self, application_error, error_detail: str = ...) -> None: ...

class OverQuotaError(Error): ...
class RequestTooLargeError(Error): ...
class ResponseTooLargeError(Error): ...
class CapabilityDisabledError(Error): ...
class FeatureNotEnabledError(Error): ...

class InterruptedError(Error):
    args: Any
    def __init__(self, exception, rpc) -> None: ...
    @property
    def rpc(self): ...
    @property
    def exception(self): ...

class RpcAuthorityError(Error): ...
