import logging
from google.appengine.runtime import default_api_stub as default_api_stub, thread_hooks as thread_hooks
from typing import Any

def GetTraceAndSpanId(): ...
def GetRequestUrl(): ...

class JsonFormatter(logging.Formatter):
    def format(self, record): ...

class SplitFileHandler(logging.FileHandler):
    def emit(self, record) -> None: ...

def InitializeFileLogging(log_path, clear_logging_handlers, custom_json_formatter: Any | None = ...) -> None: ...

class SecurityTicketThreadHook(thread_hooks.ThreadHook):
    def PreTarget(self) -> None: ...
    def PostTarget(self) -> None: ...

def InitializeThreadingApis() -> None: ...
