import abc
from google.appengine.runtime import request_environment as request_environment
from typing import Any

class ThreadHook(metaclass=abc.ABCMeta):
    __metaclass__: Any
    def __init__(self) -> None: ...
    @abc.abstractmethod
    def PreTarget(self): ...
    @abc.abstractmethod
    def PostTarget(self): ...

class RequestEnvironmentThreadHook(ThreadHook):
    cloner: Any
    def __init__(self) -> None: ...
    def PreTarget(self) -> None: ...
    def PostTarget(self) -> None: ...

def PatchStartNewThread(hooks, thread_module=..., threading_module=...) -> None: ...
