from google.appengine.ext.ndb import eventloop as eventloop, tasklets as tasklets

class NdbDjangoMiddleware:
    def process_request(self, unused_request) -> None: ...
    def process_response(self, request, response): ...
    def process_exception(self, unused_request, unused_exception) -> None: ...
