from google.appengine.ext.ndb import model
from typing import Any

class _BaseMetadata(model.Model):
    KIND_NAME: str

class Namespace(_BaseMetadata):
    KIND_NAME: str
    EMPTY_NAMESPACE_ID: int
    @property
    def namespace_name(self): ...
    @classmethod
    def key_for_namespace(cls, namespace): ...
    @classmethod
    def key_to_namespace(cls, key): ...

class Kind(_BaseMetadata):
    KIND_NAME: str
    @property
    def kind_name(self): ...
    @classmethod
    def key_for_kind(cls, kind): ...
    @classmethod
    def key_to_kind(cls, key): ...

class Property(_BaseMetadata):
    KIND_NAME: str
    @property
    def property_name(self): ...
    @property
    def kind_name(self): ...
    property_representation: Any
    @classmethod
    def key_for_kind(cls, kind): ...
    @classmethod
    def key_for_property(cls, kind, property): ...
    @classmethod
    def key_to_kind(cls, key): ...
    @classmethod
    def key_to_property(cls, key): ...

class EntityGroup(_BaseMetadata):
    KIND_NAME: str
    ID: int
    version: Any
    @classmethod
    def key_for_entity_group(cls, key): ...

def get_namespaces(start: Any | None = ..., end: Any | None = ...): ...
def get_kinds(start: Any | None = ..., end: Any | None = ...): ...
def get_properties_of_kind(kind, start: Any | None = ..., end: Any | None = ...): ...
def get_representations_of_kind(kind, start: Any | None = ..., end: Any | None = ...): ...
def get_entity_group_version(key): ...
