from typing import Any

DEBUG: bool

def logging_debug(*args) -> None: ...

wrapping: Any

def get_stack(limit: int = ...): ...
def func_info(func, lineno: Any | None = ...): ...
def gen_info(gen): ...
def frame_info(frame): ...
def code_info(code, lineno: Any | None = ...): ...
def positional(max_pos_args): ...
def decorator(wrapped_decorator): ...
def tweak_logging() -> None: ...
