from typing import MutableMapping, Optional, Text

OsEnvironLike = Optional[MutableMapping[Text, Text]]

def get(environ: OsEnvironLike = ...) -> str: ...
def put(app_id: str, environ: OsEnvironLike = ...): ...
def normalize(environ: OsEnvironLike = ...): ...
def clear(environ: OsEnvironLike = ...): ...
def parse(app_id: Optional[str] = ..., environ: OsEnvironLike = ...): ...
def project_id(app_id: Optional[str] = ..., environ: OsEnvironLike = ...): ...
