DEFAULT_MODNAME: str

class LibConfigRegistry:
    def __init__(self, modname) -> None: ...
    def register(self, prefix, mapping): ...
    def initialize(self, import_func=...) -> None: ...
    def reset(self) -> None: ...

class ConfigHandle:
    def __init__(self, prefix, registry) -> None: ...
    def __getattr__(self, suffix): ...

def register(prefix, mapping): ...
def main() -> None: ...
