class ModuleInterfaceTest:
    def setUp(self) -> None: ...
    def testAllExist(self) -> None: ...
    def testAllExported(self) -> None: ...
    def testNoExportedProtectedVariables(self) -> None: ...
    def testNoExportedModules(self) -> None: ...
