from google.appengine.api import yaml_errors as yaml_errors
from typing import Any

class EventHandler:
    def StreamStart(self, event, loader) -> None: ...
    def StreamEnd(self, event, loader) -> None: ...
    def DocumentStart(self, event, loader) -> None: ...
    def DocumentEnd(self, event, loader) -> None: ...
    def Alias(self, event, loader) -> None: ...
    def Scalar(self, event, loader) -> None: ...
    def SequenceStart(self, event, loader) -> None: ...
    def SequenceEnd(self, event, loader) -> None: ...
    def MappingStart(self, event, loader) -> None: ...
    def MappingEnd(self, event, loader) -> None: ...

class EventListener:
    def __init__(self, event_handler) -> None: ...
    def HandleEvent(self, event, loader: Any | None = ...) -> None: ...
    def Parse(self, stream, loader_class=..., **loader_args) -> None: ...
