from typing import Any

class Error(Exception): ...
class ProtocolBufferParseError(Error): ...
class EmptyConfigurationFile(Error): ...
class MultipleConfigurationFile(Error): ...
class AmbiguousConfigurationFiles(Error): ...
class UnexpectedAttribute(Error): ...
class DuplicateAttribute(Error): ...
class ListenerConfigurationError(Error): ...
class IllegalEvent(Error): ...
class InternalError(Error): ...

class EventListenerError(Error):
    cause: Any
    def __init__(self, cause) -> None: ...

class EventListenerYAMLError(EventListenerError): ...

class EventError(EventListenerError):
    event: Any
    def __init__(self, cause, event) -> None: ...
