from google.appengine.api import yaml_errors as yaml_errors, yaml_listener as yaml_listener

class Builder:
    def BuildDocument(self) -> None: ...
    def InitializeDocument(self, document, value) -> None: ...
    def BuildMapping(self, top_value) -> None: ...
    def EndMapping(self, top_value, mapping) -> None: ...
    def BuildSequence(self, top_value) -> None: ...
    def EndSequence(self, top_value, sequence) -> None: ...
    def MapTo(self, subject, key, value) -> None: ...
    def AppendTo(self, subject, value) -> None: ...

class BuilderHandler(yaml_listener.EventHandler):
    def __init__(self, builder) -> None: ...
    def StreamStart(self, event, loader) -> None: ...
    def StreamEnd(self, event, loader) -> None: ...
    def DocumentStart(self, event, loader) -> None: ...
    def DocumentEnd(self, event, loader) -> None: ...
    def Alias(self, event, loader) -> None: ...
    def Scalar(self, event, loader) -> None: ...
    def SequenceStart(self, event, loader) -> None: ...
    def SequenceEnd(self, event, loader) -> None: ...
    def MappingStart(self, event, loader) -> None: ...
    def MappingEnd(self, event, loader) -> None: ...
    def GetResults(self): ...
