// This file is auto-generated by @hey-api/openapi-ts
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AcceptModerationSuggestionData,
  AcceptModerationSuggestionErrors,
  AcceptModerationSuggestionResponses,
  GetModerationQueueData,
  GetModerationQueueErrors,
  GetModerationQueueResponses,
  ListModerationSuggestionsData,
  ListModerationSuggestionsErrors,
  ListModerationSuggestionsResponses,
  RejectModerationSuggestionsData,
  RejectModerationSuggestionsErrors,
  RejectModerationSuggestionsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Pending suggestion counts per type the caller can review
 */
export const getModerationQueue = <ThrowOnError extends boolean = false>(
  options?: Options<GetModerationQueueData, ThrowOnError>,
): RequestResult<
  GetModerationQueueResponses,
  GetModerationQueueErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetModerationQueueResponses,
    GetModerationQueueErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/queue',
    ...options,
  });

/**
 * List pending suggestions of one type with review metadata
 */
export const listModerationSuggestions = <ThrowOnError extends boolean = false>(
  options: Options<ListModerationSuggestionsData, ThrowOnError>,
): RequestResult<
  ListModerationSuggestionsResponses,
  ListModerationSuggestionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListModerationSuggestionsResponses,
    ListModerationSuggestionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/suggestions/{suggestion_type}',
    ...options,
  });

/**
 * Accept a pending suggestion, creating its target entity
 */
export const acceptModerationSuggestion = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AcceptModerationSuggestionData, ThrowOnError>,
): RequestResult<
  AcceptModerationSuggestionResponses,
  AcceptModerationSuggestionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AcceptModerationSuggestionResponses,
    AcceptModerationSuggestionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/suggestions/{suggestion_key}/accept',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reject a batch of pending suggestions
 */
export const rejectModerationSuggestions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RejectModerationSuggestionsData, ThrowOnError>,
): RequestResult<
  RejectModerationSuggestionsResponses,
  RejectModerationSuggestionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RejectModerationSuggestionsResponses,
    RejectModerationSuggestionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/suggestions/reject',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
