// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://www.thebluealliance.com/api/moderation/v1' | (string & {});
};

/**
 * The type of suggestion (event=Webcasts, match=Match Videos, media=Team Media, social-media=Social Media, offseason-event=Offseason Events, api_auth_access=API Key Requests, robot=CAD Models, event_media=Event Videos)
 */
export type SuggestionType =
  | 'event'
  | 'match'
  | 'media'
  | 'social-media'
  | 'offseason-event'
  | 'api_auth_access'
  | 'robot'
  | 'event_media';

export type QueueResponse = {
  /**
   * Pending suggestion count per suggestion type, limited to types the caller can review
   */
  counts: {
    [key: string]: number;
  };
  /**
   * Human-readable name per suggestion type
   */
  type_names: {
    [key: string]: string;
  };
};

export type SuggestionAuthor = {
  nickname?: string;
  email?: string;
  /**
   * Lifetime count of this author's accepted suggestions (reputation signal)
   */
  accepted_count?: number;
  /**
   * Lifetime count of this author's rejected suggestions (reputation signal)
   */
  rejected_count?: number;
};

/**
 * A preview of the Media entity that accepting this suggestion would create
 */
export type CandidateMedia = {
  key?: string;
  media_type_enum?: number;
  type_name?: string;
  slug_name?: string;
  foreign_key?: string;
  is_image?: boolean;
  external_link?: string;
  view_image_url?: string;
  image_direct_url?: string;
  social_profile_url?: string;
};

/**
 * The Team or Event this suggestion is attached to
 */
export type SuggestionReference = {
  type: 'team' | 'event';
  key: string;
  name?: string;
  year?: number;
  /**
   * First day of the event (events only)
   */
  start_date?: string;
  /**
   * Last day of the event (events only)
   */
  end_date?: string;
  team_number?: number;
  nickname?: string;
};

export type ExistingPreferredMedia = {
  key?: string;
  foreign_key?: string;
  media_type_enum?: number;
  view_image_url?: string;
  image_direct_url?: string;
};

export type AuthTypeInfo = {
  type?: number;
  name?: string;
};

export type ExistingAuth = {
  owner_email?: string;
  auth_types?: Array<AuthTypeInfo>;
};

export type SimilarEvent = {
  key?: string;
  name?: string;
};

export type ModerationSuggestion = {
  /**
   * The suggestion's key, used for accept/reject calls
   */
  key: string;
  target_model: SuggestionType;
  target_key?: string;
  created?: string;
  /**
   * The raw suggested contents (shape varies by suggestion type)
   */
  contents: {
    [key: string]: unknown;
  };
  author?: SuggestionAuthor;
  /**
   * Parsed details_json, with a derived thumbnail for images
   */
  details?: {
    [key: string]: unknown;
  };
  candidate_media?: CandidateMedia;
  reference?: SuggestionReference;
  event?: SuggestionReference;
  uses_official_webcast_unit?: boolean;
  existing_preferred?: Array<ExistingPreferredMedia>;
  max_preferred?: number;
  similar_events?: Array<SimilarEvent>;
  similar_events_last_year?: Array<SimilarEvent>;
  requested_auth_types?: Array<AuthTypeInfo>;
  existing_auth?: Array<ExistingAuth>;
  /**
   * match: the event has a FIRST official webcast; suggested videos may be stream rips
   */
  has_first_official_webcast?: boolean;
  /**
   * event: the event's current webcasts, to catch duplicate suggestions
   */
  existing_webcasts?: Array<{
    type?: string;
    channel?: string;
    file?: string;
    date?: string;
  }>;
  /**
   * match: YouTube title of the suggested video, when a YouTube API key is configured
   */
  video_title?: string;
  /**
   * match: duration of the suggested video in seconds, when a YouTube API key is configured
   */
  video_duration_seconds?: number;
};

export type SuggestionListResponse = {
  suggestions: Array<ModerationSuggestion>;
  /**
   * Total pending suggestions of this type, which may exceed the page returned
   */
  total: number;
};

/**
 * Type-specific reviewer overrides. All fields optional; which fields apply depends on the suggestion type.
 */
export type AcceptRequest = {
  /**
   * match: redirect the video to a different match key
   */
  target_match_key?: string;
  /**
   * media: override the media year
   */
  year?: number;
  /**
   * media: set as preferred team image (defaults to the suggester’s default_preferred request)
   */
  set_preferred?: boolean;
  /**
   * media: demote this existing preferred Media and prefer the new one
   */
  replace_preferred_media_key?: string;
  /**
   * event (webcast): webcast type, e.g. twitch/youtube
   */
  webcast_type?: string;
  /**
   * event (webcast): channel identifier
   */
  webcast_channel?: string;
  /**
   * event (webcast): optional file identifier
   */
  webcast_file?: string;
  /**
   * event (webcast): optional YYYY-MM-DD date for date-specific webcasts
   */
  webcast_date?: string;
  /**
   * event (webcast): override the target event
   */
  event_key?: string;
  /**
   * offseason-event: REQUIRED event short code, forms the event key
   */
  event_short?: string;
  /**
   * offseason-event: override event name
   */
  name?: string;
  /**
   * offseason-event: event short display name
   */
  short_name?: string;
  /**
   * offseason-event: override start date (YYYY-MM-DD)
   */
  start_date?: string;
  /**
   * offseason-event: override end date (YYYY-MM-DD)
   */
  end_date?: string;
  /**
   * offseason-event: override website
   */
  website?: string;
  /**
   * offseason-event: override venue name
   */
  venue?: string;
  /**
   * offseason-event: override venue address
   */
  venue_address?: string;
  /**
   * offseason-event: override city
   */
  city?: string;
  /**
   * offseason-event: override state/province
   */
  state?: string;
  /**
   * offseason-event: override country
   */
  country?: string;
  /**
   * offseason-event: official FIRST event code, if any
   */
  first_code?: string;
  /**
   * offseason-event: override the event type enum
   */
  event_type_enum?: number;
  /**
   * api_auth_access: auth types to grant (defaults to the requested types)
   */
  auth_types?: Array<number>;
  /**
   * api_auth_access: days after event end until the key expires; -1 for no expiration. Defaults to 7 while event end + 7 days is still in the future, otherwise -1
   */
  expiration_days?: number;
  /**
   * api_auth_access: message for the requesting user, included in the admin alert email
   */
  user_message?: string;
};

export type AcceptResponse = {
  result: ReviewResult;
  suggestion_key: string;
  /**
   * The key of the created entity (Media key, event key, match key, or auth id)
   */
  created_target_key?: string;
  message?: string;
};

export type ReviewResult =
  | 'accepted'
  | 'rejected'
  | 'not_found'
  | 'already_reviewed'
  | 'invalid'
  | 'forbidden';

export type RejectRequest = {
  suggestion_keys: Array<string>;
  /**
   * Message for the suggesting user; included in the admin alert email for api_auth_access rejections
   */
  user_message?: string;
};

export type RejectResponse = {
  results: Array<AcceptResponse>;
};

export type ErrorResponse = {
  Error?: string;
};

export type GetModerationQueueData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/queue';
};

export type GetModerationQueueErrors = {
  /**
   * Missing or invalid Firebase ID token
   */
  401: ErrorResponse;
  /**
   * Account has no review permissions
   */
  403: ErrorResponse;
};

export type GetModerationQueueError =
  GetModerationQueueErrors[keyof GetModerationQueueErrors];

export type GetModerationQueueResponses = {
  /**
   * Successful response
   */
  200: QueueResponse;
};

export type GetModerationQueueResponse =
  GetModerationQueueResponses[keyof GetModerationQueueResponses];

export type ListModerationSuggestionsData = {
  body?: never;
  path: {
    suggestion_type: SuggestionType;
  };
  query?: {
    limit?: number;
  };
  url: '/suggestions/{suggestion_type}';
};

export type ListModerationSuggestionsErrors = {
  /**
   * Missing or invalid Firebase ID token
   */
  401: ErrorResponse;
  /**
   * Missing the review permission for this suggestion type
   */
  403: ErrorResponse;
  /**
   * Unknown suggestion type
   */
  404: ErrorResponse;
};

export type ListModerationSuggestionsError =
  ListModerationSuggestionsErrors[keyof ListModerationSuggestionsErrors];

export type ListModerationSuggestionsResponses = {
  /**
   * Successful response
   */
  200: SuggestionListResponse;
};

export type ListModerationSuggestionsResponse =
  ListModerationSuggestionsResponses[keyof ListModerationSuggestionsResponses];

export type AcceptModerationSuggestionData = {
  body?: AcceptRequest;
  path: {
    suggestion_key: string;
  };
  query?: never;
  url: '/suggestions/{suggestion_key}/accept';
};

export type AcceptModerationSuggestionErrors = {
  /**
   * Invalid accept payload for this suggestion type
   */
  400: AcceptResponse;
  /**
   * Missing the review permission for this suggestion's type
   */
  403: AcceptResponse;
  /**
   * Suggestion not found
   */
  404: AcceptResponse;
  /**
   * Suggestion was already reviewed
   */
  409: AcceptResponse;
};

export type AcceptModerationSuggestionError =
  AcceptModerationSuggestionErrors[keyof AcceptModerationSuggestionErrors];

export type AcceptModerationSuggestionResponses = {
  /**
   * Suggestion accepted
   */
  200: AcceptResponse;
};

export type AcceptModerationSuggestionResponse =
  AcceptModerationSuggestionResponses[keyof AcceptModerationSuggestionResponses];

export type RejectModerationSuggestionsData = {
  body: RejectRequest;
  path?: never;
  query?: never;
  url: '/suggestions/reject';
};

export type RejectModerationSuggestionsErrors = {
  /**
   * Malformed request body
   */
  400: ErrorResponse;
  /**
   * Missing or invalid Firebase ID token
   */
  401: ErrorResponse;
};

export type RejectModerationSuggestionsError =
  RejectModerationSuggestionsErrors[keyof RejectModerationSuggestionsErrors];

export type RejectModerationSuggestionsResponses = {
  /**
   * Per-suggestion outcomes
   */
  200: RejectResponse;
};

export type RejectModerationSuggestionsResponse =
  RejectModerationSuggestionsResponses[keyof RejectModerationSuggestionsResponses];
