from google.appengine.api import apiproxy_stub_map as apiproxy_stub_map
from google.appengine.api.system import system_service_pb2 as system_service_pb2

def cpu_usage(): ...
def memory_usage(): ...
def is_shutting_down(): ...
def set_shutdown_hook(hook): ...
