from _pytest.assertion import rewrite as rewrite, truncate as truncate, util as util
from _pytest.assertion.rewrite import assertstate_key as assertstate_key
from _pytest.compat import TYPE_CHECKING as TYPE_CHECKING
from _pytest.config import Config as Config, hookimpl as hookimpl
from _pytest.main import Session as Session
from typing import Any, List, Optional

def pytest_addoption(parser: Any) -> None: ...
def register_assert_rewrite(*names: Any) -> None: ...

class DummyRewriteHook:
    def mark_rewrite(self, *names: Any) -> None: ...

class AssertionState:
    mode: Any = ...
    trace: Any = ...
    hook: Any = ...
    def __init__(self, config: Any, mode: Any) -> None: ...

def install_importhook(config: Any): ...
def pytest_collection(session: Session) -> None: ...
def pytest_runtest_protocol(item: Any): ...
def pytest_sessionfinish(session: Any) -> None: ...
def pytest_assertrepr_compare(
    config: Config, op: str, left: Any, right: Any
) -> Optional[List[str]]: ...
