from google.appengine.api import apiproxy_rpc as apiproxy_rpc, apiproxy_stub as apiproxy_stub, datastore_errors as datastore_errors
from google.appengine.datastore import datastore_pbs as datastore_pbs, datastore_rpc as datastore_rpc

class CloudDatastoreV1RemoteStub(apiproxy_stub.APIProxyStub):
    def __init__(self, datastore) -> None: ...
    def MakeSyncCall(self, service, call, request, response) -> None: ...
    def CreateRPC(self): ...
