from typing import Any

class OpenSSLVerifier:
    def __init__(self, pubkey: Any) -> None: ...
    def verify(self, message: Any, signature: Any): ...
    @staticmethod
    def from_string(key_pem: Any, is_x509_cert: Any): ...

class OpenSSLSigner:
    def __init__(self, pkey: Any) -> None: ...
    def sign(self, message: Any): ...
    @staticmethod
    def from_string(key: Any, password: bytes = ...): ...

def pkcs12_key_as_pem(private_key_bytes: Any, private_key_password: Any): ...
