from typing import Any

class RsaVerifier:
    def __init__(self, pubkey: Any) -> None: ...
    def verify(self, message: Any, signature: Any): ...
    @classmethod
    def from_string(cls, key_pem: Any, is_x509_cert: Any): ...

class RsaSigner:
    def __init__(self, pkey: Any) -> None: ...
    def sign(self, message: Any): ...
    @classmethod
    def from_string(cls, key: Any, password: str = ...): ...
