from six.moves import BaseHTTPServer
from typing import Any, Optional

argparser: Any

class ClientRedirectServer(BaseHTTPServer.HTTPServer):
    query_params: Any = ...

class ClientRedirectHandler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_GET(self) -> None: ...
    def log_message(self, format: Any, *args: Any) -> None: ...

def run_flow(flow: Any, storage: Any, flags: Optional[Any] = ..., http: Optional[Any] = ...): ...
def message_if_missing(filename: Any): ...
