from typing import Any

class Error(Exception): ...
class InvalidModuleError(Error): ...
class InvalidVersionError(Error): ...
class InvalidInstancesError(Error): ...
class UnexpectedStateError(Error): ...
class TransientError(Error): ...

def get_current_module_name(): ...
def get_current_version_name(): ...
def get_current_instance_id(): ...
def get_modules(): ...
def get_versions(module: Any | None = ...): ...
def get_default_version(module: Any | None = ...): ...
def get_num_instances(module: Any | None = ..., version: Any | None = ...): ...
def set_num_instances(instances, module: Any | None = ..., version: Any | None = ...) -> None: ...
def set_num_instances_async(instances, module: Any | None = ..., version: Any | None = ...): ...
def start_version(module, version) -> None: ...
def start_version_async(module, version): ...
def stop_version(module: Any | None = ..., version: Any | None = ...) -> None: ...
def stop_version_async(module: Any | None = ..., version: Any | None = ...): ...
def get_hostname(module: Any | None = ..., version: Any | None = ..., instance: Any | None = ...): ...
