// This file is auto-generated by @hey-api/openapi-ts
import { type UseMutationOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  type Options,
  acceptModerationSuggestion,
  getModerationQueue,
  listModerationSuggestions,
  rejectModerationSuggestions,
} from '../sdk.gen';
import type {
  AcceptModerationSuggestionData,
  AcceptModerationSuggestionError,
  AcceptModerationSuggestionResponse,
  GetModerationQueueData,
  GetModerationQueueError,
  GetModerationQueueResponse,
  ListModerationSuggestionsData,
  ListModerationSuggestionsError,
  ListModerationSuggestionsResponse,
  RejectModerationSuggestionsData,
  RejectModerationSuggestionsError,
  RejectModerationSuggestionsResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getModerationQueueQueryKey = (
  options?: Options<GetModerationQueueData>,
) => createQueryKey('getModerationQueue', options);

/**
 * Pending suggestion counts per type the caller can review
 */
export const getModerationQueueOptions = (
  options?: Options<GetModerationQueueData>,
) =>
  queryOptions<
    GetModerationQueueResponse,
    GetModerationQueueError,
    GetModerationQueueResponse,
    ReturnType<typeof getModerationQueueQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getModerationQueue({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getModerationQueueQueryKey(options),
  });

export const listModerationSuggestionsQueryKey = (
  options: Options<ListModerationSuggestionsData>,
) => createQueryKey('listModerationSuggestions', options);

/**
 * List pending suggestions of one type with review metadata
 */
export const listModerationSuggestionsOptions = (
  options: Options<ListModerationSuggestionsData>,
) =>
  queryOptions<
    ListModerationSuggestionsResponse,
    ListModerationSuggestionsError,
    ListModerationSuggestionsResponse,
    ReturnType<typeof listModerationSuggestionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listModerationSuggestions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listModerationSuggestionsQueryKey(options),
  });

/**
 * Accept a pending suggestion, creating its target entity
 */
export const acceptModerationSuggestionMutation = (
  options?: Partial<Options<AcceptModerationSuggestionData>>,
): UseMutationOptions<
  AcceptModerationSuggestionResponse,
  AcceptModerationSuggestionError,
  Options<AcceptModerationSuggestionData>
> => {
  const mutationOptions: UseMutationOptions<
    AcceptModerationSuggestionResponse,
    AcceptModerationSuggestionError,
    Options<AcceptModerationSuggestionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await acceptModerationSuggestion({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reject a batch of pending suggestions
 */
export const rejectModerationSuggestionsMutation = (
  options?: Partial<Options<RejectModerationSuggestionsData>>,
): UseMutationOptions<
  RejectModerationSuggestionsResponse,
  RejectModerationSuggestionsError,
  Options<RejectModerationSuggestionsData>
> => {
  const mutationOptions: UseMutationOptions<
    RejectModerationSuggestionsResponse,
    RejectModerationSuggestionsError,
    Options<RejectModerationSuggestionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await rejectModerationSuggestions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
