from google.appengine.api import datastore as datastore, datastore_errors as datastore_errors, datastore_types as datastore_types, users as users
from typing import Any

MultiQuery: Any
LOG_LEVEL: Any

def Execute(query_string, *args, **keyword_args): ...

class GQL:
    TOKENIZE_REGEX: Any
    RESERVED_KEYWORDS: Any
    MAX_ALLOWABLE_QUERIES: Any
    def __init__(self, query_string, _app: Any | None = ..., _auth_domain: Any | None = ..., namespace: Any | None = ...) -> None: ...
    def Bind(self, args, keyword_args, cursor: Any | None = ..., end_cursor: Any | None = ...): ...
    def EnumerateQueries(self, used_args, args, keyword_args): ...
    def Run(self, *args, **keyword_args): ...
    def filters(self): ...
    def hint(self): ...
    def limit(self): ...
    def offset(self): ...
    def orderings(self): ...
    def is_keys_only(self): ...
    def projection(self): ...
    def is_distinct(self): ...
    def kind(self): ...
    __iter__: Any

class Literal:
    def __init__(self, value) -> None: ...
    def Get(self): ...
