import pprint
import reprlib
from typing import Any

class SafeRepr(reprlib.Repr):
    maxstring: Any = ...
    maxsize: Any = ...
    def __init__(self, maxsize: int) -> None: ...
    def repr(self, x: Any) -> str: ...
    def repr_instance(self, x: Any, level: int) -> str: ...

def safeformat(obj: Any) -> str: ...
def saferepr(obj: Any, maxsize: int = ...) -> str: ...

class AlwaysDispatchingPrettyPrinter(pprint.PrettyPrinter): ...
