from google.appengine.api import apiproxy_stub_map as apiproxy_stub_map, user_service_pb2 as user_service_pb2, users as users
from google.appengine.runtime import apiproxy_errors as apiproxy_errors
from typing import Any

class Error(Exception): ...
class OAuthRequestError(Error): ...
class NotAllowedError(OAuthRequestError): ...
class InvalidOAuthParametersError(OAuthRequestError): ...
class InvalidOAuthTokenError(OAuthRequestError): ...
class OAuthServiceFailureError(Error): ...

def get_current_user(_scope: Any | None = ...): ...
def is_current_user_admin(_scope: Any | None = ...): ...
def get_oauth_consumer_key() -> None: ...
def get_client_id(_scope): ...
def get_authorized_scopes(scope): ...
