import html5lib
from _typeshed import Incomplete
from bs4 import BeautifulSoup
from bs4._typing import _AttributeValue, _AttributeValues, _Encoding, _Encodings, _NamespaceURL, _RawMarkup
from bs4.builder import HTMLTreeBuilder
from bs4.element import NavigableString, PageElement, Tag
from html5lib.treebuilders import base as treebuilder_base
from typing import Any, Iterable, Sequence

__all__ = ['HTML5TreeBuilder']

class HTML5TreeBuilder(HTMLTreeBuilder):
    NAME: str
    features: Sequence[str]
    TRACKS_LINE_NUMBERS: bool
    underlying_builder: TreeBuilderForHtml5lib
    user_specified_encoding: _Encoding | None
    def prepare_markup(self, markup: _RawMarkup, user_specified_encoding: _Encoding | None = None, document_declared_encoding: _Encoding | None = None, exclude_encodings: _Encodings | None = None) -> Iterable[tuple[_RawMarkup, _Encoding | None, _Encoding | None, bool]]: ...
    def feed(self, markup: _RawMarkup) -> None: ...
    def create_treebuilder(self, namespaceHTMLElements: bool) -> TreeBuilderForHtml5lib: ...
    def test_fragment_to_document(self, fragment: str) -> str: ...

class TreeBuilderForHtml5lib(treebuilder_base.TreeBuilder):
    soup: BeautifulSoup
    parser: html5lib.HTMLParser | None
    store_line_numbers: Incomplete
    def __init__(self, namespaceHTMLElements: bool, soup: BeautifulSoup | None = None, store_line_numbers: bool = True, **kwargs: Any) -> None: ...
    def documentClass(self) -> Element: ...
    def insertDoctype(self, token: dict[str, Any]) -> None: ...
    def elementClass(self, name: str, namespace: str) -> Element: ...
    def commentClass(self, data: str) -> TextNode: ...
    def fragmentClass(self) -> Element: ...
    def getFragment(self) -> Element: ...
    def appendChild(self, node: Element) -> None: ...
    def getDocument(self) -> BeautifulSoup: ...
    def testSerializer(self, element: Element) -> str: ...

class AttrList:
    element: Tag
    attrs: _AttributeValues
    def __init__(self, element: Tag) -> None: ...
    def __iter__(self) -> Iterable[tuple[str, _AttributeValue]]: ...
    def __setitem__(self, name: str, value: _AttributeValue) -> None: ...
    def items(self) -> Iterable[tuple[str, _AttributeValue]]: ...
    def keys(self) -> Iterable[str]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, name: str) -> _AttributeValue: ...
    def __contains__(self, name: str) -> bool: ...

class BeautifulSoupNode(treebuilder_base.Node):
    element: PageElement
    soup: BeautifulSoup
    namespace: _NamespaceURL | None
    @property
    def nodeType(self) -> int: ...
    def cloneNode(self) -> treebuilder_base.Node: ...

class Element(BeautifulSoupNode):
    element: Tag
    namespace: _NamespaceURL | None
    soup: Incomplete
    def __init__(self, element: Tag, soup: BeautifulSoup, namespace: _NamespaceURL | None) -> None: ...
    def appendChild(self, node: BeautifulSoupNode) -> None: ...
    def getAttributes(self) -> AttrList: ...
    def setAttributes(self, attributes: _Html5libAttributes | None) -> None: ...
    attributes: Incomplete
    def insertText(self, data: str, insertBefore: BeautifulSoupNode | None = None) -> None: ...
    def insertBefore(self, node: BeautifulSoupNode, refNode: BeautifulSoupNode) -> None: ...
    def removeChild(self, node: Element) -> None: ...
    def reparentChildren(self, new_parent: Element) -> None: ...
    def hasContent(self) -> bool: ...
    def cloneNode(self) -> treebuilder_base.Node: ...
    def getNameTuple(self) -> tuple[_NamespaceURL | None, str]: ...
    nameTuple: Incomplete

class TextNode(BeautifulSoupNode):
    element: NavigableString
    soup: Incomplete
    def __init__(self, element: NavigableString, soup: BeautifulSoup) -> None: ...
