from _typeshed import Incomplete
from bs4 import BeautifulSoup
from bs4._typing import _Encoding, _Encodings, _RawMarkup
from bs4.builder import DetectsXMLParsedAsHTML, HTMLTreeBuilder
from html.parser import HTMLParser
from typing import Any, Iterable

__all__ = ['HTMLParserTreeBuilder']

class BeautifulSoupHTMLParser(HTMLParser, DetectsXMLParsedAsHTML):
    REPLACE: str
    IGNORE: str
    soup: Incomplete
    on_duplicate_attribute: Incomplete
    attribute_dict_class: Incomplete
    already_closed_empty_element: Incomplete
    def __init__(self, soup: BeautifulSoup, *args: Any, on_duplicate_attribute: str | _DuplicateAttributeHandler = ..., **kwargs: Any) -> None: ...
    def error(self, message: str) -> None: ...
    def handle_startendtag(self, name: str, attrs: list[tuple[str, str | None]]) -> None: ...
    def handle_starttag(self, name: str, attrs: list[tuple[str, str | None]], handle_empty_element: bool = True) -> None: ...
    def handle_endtag(self, name: str, check_already_closed: bool = True) -> None: ...
    def handle_data(self, data: str) -> None: ...
    def handle_charref(self, name: str) -> None: ...
    def handle_entityref(self, name: str) -> None: ...
    def handle_comment(self, data: str) -> None: ...
    def handle_decl(self, data: str) -> None: ...
    def unknown_decl(self, data: str) -> None: ...
    def handle_pi(self, data: str) -> None: ...

class HTMLParserTreeBuilder(HTMLTreeBuilder):
    is_xml: bool
    picklable: bool
    NAME: str
    features: Iterable[str]
    parser_args: tuple[Iterable[Any], dict[str, Any]]
    TRACKS_LINE_NUMBERS: bool
    def __init__(self, parser_args: Iterable[Any] | None = None, parser_kwargs: dict[str, Any] | None = None, **kwargs: Any) -> None: ...
    def prepare_markup(self, markup: _RawMarkup, user_specified_encoding: _Encoding | None = None, document_declared_encoding: _Encoding | None = None, exclude_encodings: _Encodings | None = None) -> Iterable[tuple[str, _Encoding | None, _Encoding | None, bool]]: ...
    def feed(self, markup: _RawMarkup) -> None: ...
