from _typeshed import Incomplete
from bs4 import BeautifulSoup
from bs4._typing import _Encoding, _Encodings, _InvertedNamespaceMapping, _NamespaceMapping, _RawMarkup
from bs4.builder import HTMLTreeBuilder, TreeBuilder
from bs4.element import ProcessingInstruction
from lxml import etree
from typing import Any, Iterable

__all__ = ['LXMLTreeBuilderForXML', 'LXMLTreeBuilder']

class LXMLTreeBuilderForXML(TreeBuilder):
    DEFAULT_PARSER_CLASS: type[etree.XMLParser]
    is_xml: bool
    processing_instruction_class: type[ProcessingInstruction]
    NAME: str
    ALTERNATE_NAMES: Iterable[str]
    features: Iterable[str]
    CHUNK_SIZE: int
    DEFAULT_NSMAPS: _NamespaceMapping
    DEFAULT_NSMAPS_INVERTED: _InvertedNamespaceMapping
    nsmaps: list[_InvertedNamespaceMapping | None]
    empty_element_tags: set[str]
    parser: Any
    def initialize_soup(self, soup: BeautifulSoup) -> None: ...
    def default_parser(self, encoding: _Encoding | None) -> _ParserOrParserClass: ...
    def parser_for(self, encoding: _Encoding | None) -> _LXMLParser: ...
    soup: Incomplete
    active_namespace_prefixes: Incomplete
    def __init__(self, parser: etree.XMLParser | None = None, empty_element_tags: set[str] | None = None, **kwargs: Any) -> None: ...
    def prepare_markup(self, markup: _RawMarkup, user_specified_encoding: _Encoding | None = None, document_declared_encoding: _Encoding | None = None, exclude_encodings: _Encodings | None = None) -> Iterable[tuple[str | bytes, _Encoding | None, _Encoding | None, bool]]: ...
    def feed(self, markup: _RawMarkup) -> None: ...
    def close(self) -> None: ...
    def start(self, tag: str | bytes, attrs: dict[str | bytes, str | bytes], nsmap: _NamespaceMapping = {}) -> None: ...
    def end(self, name: str | bytes) -> None: ...
    def pi(self, target: str, data: str) -> None: ...
    def data(self, data: str | bytes) -> None: ...
    def doctype(self, name: str, pubid: str, system: str) -> None: ...
    def comment(self, text: str | bytes) -> None: ...
    def test_fragment_to_document(self, fragment: str) -> str: ...

class LXMLTreeBuilder(HTMLTreeBuilder, LXMLTreeBuilderForXML):
    NAME: str
    ALTERNATE_NAMES: Iterable[str]
    features: Iterable[str]
    is_xml: bool
    def default_parser(self, encoding: _Encoding | None) -> _ParserOrParserClass: ...
    parser: Incomplete
    def feed(self, markup: _RawMarkup) -> None: ...
    def test_fragment_to_document(self, fragment: str) -> str: ...
