runtime: python312
app_engine_apis: true
entrypoint: gunicorn -b :$PORT backend.default.main:app

instance_class: F1
automatic_scaling:
  max_idle_instances: 1

handlers:
  - url: .*
    script: auto
