// This file is auto-generated by @hey-api/openapi-ts
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  GetEventColorsData,
  GetEventColorsResponses,
  GetTeamColorsBatchData,
  GetTeamColorsBatchResponses,
  GetTeamColorsData,
  GetTeamColorsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get colors for all teams at an event
 */
export const getEventColors = <ThrowOnError extends boolean = false>(
  options: Options<GetEventColorsData, ThrowOnError>,
): RequestResult<GetEventColorsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetEventColorsResponses,
    unknown,
    ThrowOnError
  >({ url: '/v1/event/{eventKey}', ...options });

/**
 * Get colors for a single team
 */
export const getTeamColors = <ThrowOnError extends boolean = false>(
  options: Options<GetTeamColorsData, ThrowOnError>,
): RequestResult<GetTeamColorsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetTeamColorsResponses, unknown, ThrowOnError>(
    { url: '/v1/team/{teamNumber}', ...options },
  );

/**
 * Get colors for multiple teams, or all teams
 *
 * Pass one or more `team` query params to fetch specific teams, or `all` to fetch every team in the system.
 */
export const getTeamColorsBatch = <ThrowOnError extends boolean = false>(
  options?: Options<GetTeamColorsBatchData, ThrowOnError>,
): RequestResult<GetTeamColorsBatchResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetTeamColorsBatchResponses,
    unknown,
    ThrowOnError
  >({ url: '/v1/team', ...options });
