// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetInspectionStatusData,
  GetInspectionStatusErrors,
  GetInspectionStatusResponses,
  PullEventsData,
  PullEventsErrors,
  PullEventsResponses,
  PullLiveEventStatusData,
  PullLiveEventStatusErrors,
  PullLiveEventStatusResponses,
  PullPitAddressesData,
  PullPitAddressesErrors,
  PullPitAddressesResponses,
  PullPitMapData,
  PullPitMapErrors,
  PullPitMapResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Live event status (pull)
 */
export const pullLiveEventStatus = <ThrowOnError extends boolean = false>(
  options: Options<PullLiveEventStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PullLiveEventStatusResponses,
    PullLiveEventStatusErrors,
    ThrowOnError
  >({
    security: [{ name: 'Nexus-Api-Key', type: 'apiKey' }],
    url: '/event/{eventKey}',
    ...options,
  });

/**
 * Pit addresses (pull)
 *
 * Get the mapping from team number to pit addresses.
 */
export const pullPitAddresses = <ThrowOnError extends boolean = false>(
  options: Options<PullPitAddressesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PullPitAddressesResponses,
    PullPitAddressesErrors,
    ThrowOnError
  >({
    security: [{ name: 'Nexus-Api-Key', type: 'apiKey' }],
    url: '/event/{eventKey}/pits',
    ...options,
  });

/**
 * Pit map (pull)
 *
 * Get raw map data that can be used to render your own version of a pit map.
 */
export const pullPitMap = <ThrowOnError extends boolean = false>(
  options: Options<PullPitMapData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PullPitMapResponses,
    PullPitMapErrors,
    ThrowOnError
  >({
    security: [{ name: 'Nexus-Api-Key', type: 'apiKey' }],
    url: '/event/{eventKey}/map',
    ...options,
  });

/**
 * Inspection status (pull)
 *
 * Get the mapping from team number to inspection status.
 */
export const getInspectionStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetInspectionStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetInspectionStatusResponses,
    GetInspectionStatusErrors,
    ThrowOnError
  >({
    security: [{ name: 'Nexus-Api-Key', type: 'apiKey' }],
    url: '/event/{eventKey}/inspection',
    ...options,
  });

/**
 * Events (pull)
 */
export const pullEvents = <ThrowOnError extends boolean = false>(
  options?: Options<PullEventsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PullEventsResponses,
    PullEventsErrors,
    ThrowOnError
  >({
    security: [{ name: 'Nexus-Api-Key', type: 'apiKey' }],
    url: '/events',
    ...options,
  });
