// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://frc.nexus/api/v1' | (string & {});
};

export type Webhooks =
  | PushLiveEventStatusWebhookRequest
  | PushMatchStatusWebhookRequest;

export type PitAddresses = {
  [key: string]: PitAddress;
};

export type InspectionStatuses = {
  [key: string]: InspectionStatus;
};

/**
 * A team's inspection status.
 */
export type InspectionStatus = {
  /**
   * Whether the team has passed an initial, complete inspection.
   */
  inspected?: boolean;
  /**
   * The current inspection status of the team. Not set for demo events. This value is cached and may be a couple minutes out of date.
   */
  status?:
    | 'hold'
    | 'in-progress'
    | 'complete'
    | 'reinspection'
    | 'queued'
    | 'not-started';
  /**
   * The current position of this team in the inspection queue. Not set for demo events. This value is cached and may be a couple minutes out of date.
   */
  queuePosition?: number | null;
};

export type Events = {
  [key: string]: EventSummary;
};

/**
 * High level details of an event that is registered for Nexus. Note: being registered for Nexus does not guarantee the event will use any particular feature of Nexus, if at all. Events will not be listed after they have concluded.
 */
export type EventSummary = {
  /**
   * The name of this event.
   */
  name?: string;
  /**
   * The timestamp (Unix time in milliseconds) at which this event is scheduled to start.
   */
  start?: number;
  /**
   * The timestamp (Unix time in milliseconds) at which this event is scheduled to end.
   */
  end?: number;
};

/**
 * The unique identifier of the event. For official events, the event key will match the event code as displayed on [frc.events](http://frc.events). Offseason events may use event keys derived from either [frc.events](http://frc.events) or [thebluealliance.com](https://thebluealliance.com), or will be arbitrary. Examples: `2024casf`, `demo1234`
 */
export type EventKey = string;

/**
 * A pit address is an arbitrary string usually in the form of letter + number. They are sometimes useful for finding where a team's pit is located within a venue. Examples: `A1`, `C12`
 */
export type PitAddress = string;

export type PitMap = {
  /**
   * The size of the map.
   */
  size?: {
    /**
     * The width of the map. 10 units is approximately 1 foot.
     */
    x?: number;
    /**
     * The height of the map. 10 units is approximately 1 foot.
     */
    y?: number;
  };
  /**
   * The pits.
   */
  pits?: {
    [key: string]: MapElement & {
      /**
       * The team number assigned to this pit, if any.
       */
      team?: string | null;
    };
  };
  /**
   * Notable areas in or near the pit area, such as `Pit admin`.
   */
  areas?: {
    [key: string]: MapElement & {
      /**
       * The label of this area. Examples: `Pit admin`, `Inspection`, `Spare parts`, `EMT`, `Radio config`, `Concessions`, `Machine shop`, `Restrooms`
       */
      label?: string;
    };
  } | null;
  /**
   * Arbitrary text labels.
   */
  labels?: {
    [key: string]: MapElement & {
      /**
       * The text of this label. Examples: `Field`, `Practice field`, `Main gym`, `Auxiliary pits`
       */
      label?: string;
    };
  } | null;
  /**
   * Arrows that can indicate entrances, exits, and paths.
   */
  arrows?: {
    [key: string]: MapElement & {
      /**
       * Whether this arrow points in a single direction or in both directions. At an angle of 0°, a single arrow points up and a double arrow points up & down.
       */
      type?: 'single' | 'double';
    };
  } | null;
  /**
   * Walls that may surround or divide pit areas. May also be used to indicate areas that are inaccessible by teams.
   */
  walls?: {
    [key: string]: MapElement & {
      [key: string]: unknown;
    };
  } | null;
};

export type MapElement = {
  /**
   * The position of the center of this element.
   */
  position?: {
    /**
     * The position of the center of this element on the horizontal axis. 10 units is approximately 1 foot.
     */
    x?: number;
    /**
     * The position of the center of this element on the vertical axis. 10 units is approximately 1 foot.
     */
    y?: number;
  };
  /**
   * The size of this element.
   */
  size?: {
    /**
     * The width of this element. 10 units is approximately 1 foot.
     */
    x?: number;
    /**
     * The height of this element. 10 units is approximately 1 foot.
     */
    y?: number;
  };
  /**
   * The angle in degrees that this element is rotated about its center.
   */
  angle?: number | null;
};

export type EventStatus = {
  eventKey?: EventKey;
  /**
   * The timestamp (Unix time in milliseconds) at which this event status snapshot was generated by Nexus.
   */
  dataAsOfTime?: number;
  /**
   * The human-friendly label for the latest match that is queuing. Null if the event is not currently queuing a match. Examples: `Practice 1`, `Qualification 24`, `Qualification 24 Replay`, `Playoff 8`, `Final 1`
   */
  nowQueuing?: string | null;
  /**
   * All scheduled matches for this event, sorted by play order (practice matches first, then qualifications, then playoffs). This array is empty if the event has not yet scheduled any matches. This array can include scheduled match replays which are indicated by the `replayOf` property.
   */
  matches?: Array<Match>;
  /**
   * Current announcements that are posted for this event. This array is empty if there are no current announcements.
   */
  announcements?: Array<Announcement>;
  /**
   * Current parts requests that are posted for this event. This array is empty if there are no current parts requests.
   */
  partsRequests?: Array<PartsRequest>;
};

export type MatchStatus = {
  eventKey?: EventKey;
  /**
   * The timestamp (Unix time in milliseconds) at which this event status snapshot was generated by Nexus.
   */
  dataAsOfTime?: number;
  /**
   * The updated match.
   */
  match?: Match;
};

export type Match = {
  /**
   * The human-friendly label for a match. Examples: `Practice 1`, `Qualification 24`, `Qualification 24 Replay`, `Playoff 8`, `Final 1`
   */
  label?: string;
  /**
   * The current queuing status of this match. Typically, matches transition from `Queuing soon` -> `Now queuing` -> `On deck` -> `On field`. However, any state transition is possible and some events skip the `Now queuing` state entirely.
   */
  status?: 'Queuing soon' | 'Now queuing' | 'On deck' | 'On field';
  redTeams?: Teams;
  blueTeams?: Teams;
  /**
   * Timestamps for key match status changes based on lead queuer input.
   */
  times?: {
    /**
     * The timestamp (Unix time in milliseconds) at which this match was originally scheduled to start. Not set for playoffs and whenever scheduled match times are not available.
     */
    scheduledStartTime?: number | null;
    /**
     * The timestamp (Unix time in milliseconds) at which this match is estimated to be `Now queuing`. If the status of this match is not `Queuing soon`, then this timestamp is equivalent to `actualQueueTime`.
     */
    estimatedQueueTime?: number | null;
    /**
     * The timestamp (Unix time in milliseconds) at which this match is estimated to be `On deck`. If the status of this match is `On deck` or `On field`, then this timestamp is equivalent to `actualOnDeckTime`.
     */
    estimatedOnDeckTime?: number | null;
    /**
     * The timestamp (Unix time in milliseconds) at which this match is estimated to be `On field`. If the status of this match is `On field`, then this timestamp is equivalent to `actualOnFieldTime`.
     */
    estimatedOnFieldTime?: number | null;
    /**
     * The timestamp (Unix time in milliseconds) at which this match is estimated to start ("3 - 2 - 1 - Go!").
     */
    estimatedStartTime?: number | null;
    /**
     * The timestamp (Unix time in milliseconds) at which the status of this match was set to `Now queuing`. If the status of this match is `Queuing soon`, then this is null.
     */
    actualQueueTime?: number | null;
    /**
     * The timestamp (Unix time in milliseconds) at which the status of this match was set to `On deck`. If the status of this match is `Queuing soon` or `Now queuing`, then this is null.
     */
    actualOnDeckTime?: number | null;
    /**
     * The timestamp (Unix time in milliseconds) at which the status of this match was set to `On field`. If the status of this match is not `On field`, then this is null.
     */
    actualOnFieldTime?: number | null;
  };
  /**
   * The label for a break that begins after this match is played. Null if there is no break after this match.
   */
  breakAfter?:
    | 'Break'
    | 'Lunch'
    | 'End of day'
    | 'Alliance selection'
    | 'Awards break';
  /**
   * The match this match is a replay of. Null if this match is not a replay
   */
  replayOf?: string | null;
};

/**
 * An array of team numbers in station number order. A team number is null if there is no team assigned to that station (applicable to practice matches). The entire array is null if the alliance is undecided (applicable to playoffs). There can be up to 4 teams in the case of a backup team in playoffs.
 */
export type Teams = Array<string | null> | null;

export type Announcement = {
  /**
   * A unique identifier for this announcement.
   */
  id?: string;
  /**
   * The announcement text.
   */
  announcement?: string;
  /**
   * The timestamp (Unix time in milliseconds) at which this announcement was posted.
   */
  postedTime?: number;
};

export type PartsRequest = {
  /**
   * A unique identifier for this parts request.
   */
  id?: string;
  /**
   * The parts requested.
   */
  parts?: string;
  /**
   * The team number requesting the parts.
   */
  requestedByTeam?: string;
  /**
   * The timestamp (Unix time in milliseconds) at which this parts request was posted.
   */
  postedTime?: number;
};

export type PullLiveEventStatusData = {
  body?: never;
  path: {
    /**
     * The event you want to fetch the status of.
     */
    eventKey: EventKey;
  };
  query?: never;
  url: '/event/{eventKey}';
};

export type PullLiveEventStatusErrors = {
  /**
   * Missing API key. Get your API key from [frc.nexus/api](https://frc.nexus/api) and include it in the `Nexus-Api-Key` header.
   */
  401: unknown;
  /**
   * Invalid API key. Ensure the key you're using matches your key at [frc.nexus/api](https://frc.nexus/api). If abuse was detected, your API key may have been disabled. Email contact@frc.nexus for support.
   */
  403: unknown;
  /**
   * `eventKey` does not exist.
   */
  404: unknown;
  /**
   * An unknown server error occurred. Try again later or email contact@frc.nexus for support.
   */
  500: unknown;
};

export type PullLiveEventStatusResponses = {
  /**
   * Live event status
   */
  200: EventStatus;
};

export type PullLiveEventStatusResponse =
  PullLiveEventStatusResponses[keyof PullLiveEventStatusResponses];

export type PullPitAddressesData = {
  body?: never;
  path: {
    /**
     * The event you want to fetch the pits for.
     */
    eventKey: EventKey;
  };
  query?: never;
  url: '/event/{eventKey}/pits';
};

export type PullPitAddressesErrors = {
  /**
   * Missing API key. Get your API key from [frc.nexus/api](https://frc.nexus/api) and include it in the `Nexus-Api-Key` header.
   */
  401: unknown;
  /**
   * Invalid API key. Ensure the key you're using matches your key at [frc.nexus/api](https://frc.nexus/api). If abuse was detected, your API key may have been disabled. Email contact@frc.nexus for support.
   */
  403: unknown;
  /**
   * `eventKey` does not exist.
   */
  404: unknown;
  /**
   * An unknown server error occurred. Try again later or email contact@frc.nexus for support.
   */
  500: unknown;
};

export type PullPitAddressesResponses = {
  /**
   * Team number to pit address map
   */
  200: PitAddresses;
};

export type PullPitAddressesResponse =
  PullPitAddressesResponses[keyof PullPitAddressesResponses];

export type PullPitMapData = {
  body?: never;
  path: {
    /**
     * The event you want to fetch the map for.
     */
    eventKey: EventKey;
  };
  query?: never;
  url: '/event/{eventKey}/map';
};

export type PullPitMapErrors = {
  /**
   * Missing API key. Get your API key from [frc.nexus/api](https://frc.nexus/api) and include it in the `Nexus-Api-Key` header.
   */
  401: unknown;
  /**
   * Invalid API key. Ensure the key you're using matches your key at [frc.nexus/api](https://frc.nexus/api). If abuse was detected, your API key may have been disabled. Email contact@frc.nexus for support.
   */
  403: unknown;
  /**
   * `eventKey` does not exist or does not have a pit map.
   */
  404: unknown;
  /**
   * An unknown server error occurred. Try again later or email contact@frc.nexus for support.
   */
  500: unknown;
};

export type PullPitMapResponses = {
  /**
   * Pit map
   */
  200: PitMap;
};

export type PullPitMapResponse = PullPitMapResponses[keyof PullPitMapResponses];

export type GetInspectionStatusData = {
  body?: never;
  path: {
    /**
     * The event you want to fetch inspection status for.
     */
    eventKey: EventKey;
  };
  query?: never;
  url: '/event/{eventKey}/inspection';
};

export type GetInspectionStatusErrors = {
  /**
   * Missing API key. Get your API key from [frc.nexus/api](https://frc.nexus/api) and include it in the `Nexus-Api-Key` header.
   */
  401: unknown;
  /**
   * Invalid API key. Ensure the key you're using matches your key at [frc.nexus/api](https://frc.nexus/api). If abuse was detected, your API key may have been disabled. Email contact@frc.nexus for support.
   */
  403: unknown;
  /**
   * `eventKey` does not exist or the event has not started inspection in Nexus.
   */
  404: unknown;
  /**
   * An unknown server error occurred. Try again later or email contact@frc.nexus for support.
   */
  500: unknown;
};

export type GetInspectionStatusResponses = {
  /**
   * Team number to inspection status map
   */
  200: InspectionStatuses;
};

export type GetInspectionStatusResponse =
  GetInspectionStatusResponses[keyof GetInspectionStatusResponses];

export type PullEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/events';
};

export type PullEventsErrors = {
  /**
   * Missing API key. Get your API key from [frc.nexus/api](https://frc.nexus/api) and include it in the `Nexus-Api-Key` header.
   */
  401: unknown;
  /**
   * Invalid API key. Ensure the key you're using matches your key at [frc.nexus/api](https://frc.nexus/api). If abuse was detected, your API key may have been disabled. Email contact@frc.nexus for support.
   */
  403: unknown;
  /**
   * No events.
   */
  404: unknown;
  /**
   * An unknown server error occurred. Try again later or email contact@frc.nexus for support.
   */
  500: unknown;
};

export type PullEventsResponses = {
  /**
   * Event object
   */
  200: Events;
};

export type PullEventsResponse = PullEventsResponses[keyof PullEventsResponses];

/**
 * Register your webhook at [frc.nexus/api](https://frc.nexus/api).<br /><br />A POST request is made to each webhook when any of the following happens:
 * - a match status is updated
 * - a break time is updated
 * - a team is added to a playoff alliance
 * - an announcement is posted or removed
 * - a parts request is posted or removed
 *
 * Note that some of these events frequently happen multiple times within a short period of time. Build your application to handle repeated requests and ensure you always use the data with the most recent `dataAsOfTime`.
 */
export type PushLiveEventStatusWebhookPayload = EventStatus;

export type PushLiveEventStatusWebhookRequest = {
  body: PushLiveEventStatusWebhookPayload;
  key: 'Live event status';
  path?: never;
  query?: never;
};

/**
 * Register your webhook for a specific team number at [frc.nexus/api](https://frc.nexus/api).<br /><br />A POST request is made to each webhook when the match status is updated for a match which includes the specified team number. Multiple status updates could happen quickly so ensure you always use the data with the most recent `dataAsOfTime`.
 */
export type PushMatchStatusWebhookPayload = MatchStatus;

export type PushMatchStatusWebhookRequest = {
  body: PushMatchStatusWebhookPayload;
  key: 'Match status';
  path?: never;
  query?: never;
};
