name: On pull request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  py3-type:
    name: "[py3] Type Check"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            python:
              - '**/*.py'
              - 'pyproject.toml'
              - 'uv.lock'
      - name: Set up uv
        if: steps.changes.outputs.python == 'true'
        uses: astral-sh/setup-uv@v7
      - name: Run Type Check
        if: steps.changes.outputs.python == 'true'
        run: make typecheck
  py3-lint:
    name: "[py3] Format & Lint"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            python:
              - '**/*.py'
              - 'pyproject.toml'
              - 'uv.lock'
      - name: Set up uv
        if: steps.changes.outputs.python == 'true'
        uses: astral-sh/setup-uv@v7
      - name: Run Format & Lint
        if: steps.changes.outputs.python == 'true'
        run: make lint
  py3-test:
    name: "[py3] Test"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            python:
              - '**/*.py'
              - 'pyproject.toml'
              - 'uv.lock'
              - '.test_durations'
      - name: Set up uv
        if: steps.changes.outputs.python == 'true'
        uses: astral-sh/setup-uv@v7
      - name: Run Tests
        if: steps.changes.outputs.python == 'true'
        run: make test-ci ARGS='src --cov --splits 5 --group ${{ matrix.group }}'
      - name: Save coverage artifacts
        if: steps.changes.outputs.python == 'true'
        uses: actions/upload-artifact@v7.0.0
        with:
          name: coverage${{ matrix.group }}
          path: .coverage
          include-hidden-files: true
  py3-coverage:
    name: "[py3] Coverage"
    runs-on: ubuntu-24.04
    needs: [py3-test]
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            python:
              - '**/*.py'
              - 'pyproject.toml'
              - 'uv.lock'
              - '.test_durations'
      - name: Set up uv
        if: steps.changes.outputs.python == 'true'
        uses: astral-sh/setup-uv@v7
      - name: Download all artifacts
        if: steps.changes.outputs.python == 'true'
        uses: actions/download-artifact@v8
      - name: Combine coverage
        if: steps.changes.outputs.python == 'true'
        run: |
          uv run --frozen --group ci coverage combine coverage*/.coverage*
          uv run --frozen --group ci coverage xml
      - name: Upload coverage to Codecov
        if: steps.changes.outputs.python == 'true'
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
  node-lint:
    name: "[node] Format & Lint"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            node:
              - 'ops/**'
              - 'src/**'
              - 'package.json'
      - name: Set up Node
        if: steps.changes.outputs.node == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - name: Install Dependencies
        if: steps.changes.outputs.node == 'true'
        run: npm ci
      - name: Run Format & Lint
        if: steps.changes.outputs.node == 'true'
        run: ./ops/lint_node.sh
  node-test:
    name: "[node] Test"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            node:
              - 'ops/**'
              - 'src/**'
              - 'package.json'
      - name: Set up Node
        if: steps.changes.outputs.node == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - name: Install Dependencies
        if: steps.changes.outputs.node == 'true'
        run: npm ci
      - name: Run Tests
        if: steps.changes.outputs.node == 'true'
        run: ./ops/test_node.sh
      - name: Upload coverage to Codecov
        if: steps.changes.outputs.node == 'true'
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.node_coverage/
  bash-lint:
    name: "[bash] Lint"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            bash:
              - 'ops/**/*.sh'
      - name: Run Lint
        if: steps.changes.outputs.bash == 'true'
        run: make lint-bash
  check-python-version:
    name: "[py3] Check Python Version Consistency"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Check Python Version
        run: ./ops/check_python_version.sh

  build-web:
    name: Build Web
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            buildweb:
              - 'ops/**'
              - 'src/**'
              - 'package.json'
              - 'pyproject.toml'
      - name: Set up uv
        if: steps.changes.outputs.buildweb == 'true'
        uses: astral-sh/setup-uv@v7
      - name: Set up Node
        if: steps.changes.outputs.buildweb == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - name: Install Node Dependencies
        if: steps.changes.outputs.buildweb == 'true'
        run: npm ci
      - name: Run Build
        if: steps.changes.outputs.buildweb == 'true'
        run: ./ops/build/run_buildweb.sh --env

  ops-test:
    name: Ops Fullstack Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            web:
              - 'ops/**'
              - 'src/**'
              - 'package.json'
              - 'pyproject.toml'
      # See https://github.com/puppeteer/puppeteer/issues/12818
      # Ubuntu 23+ doesn't like running puppeteer without disabling AppArmor.
      - name: Disable AppArmor
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Set up Python 3.13
        if: steps.changes.outputs.web == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install Python Dependencies
        if: steps.changes.outputs.web == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Set up Node
        if: steps.changes.outputs.web == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
      - name: Install Node Dependencies
        if: steps.changes.outputs.web == 'true'
        run: |
          npm ci
          npm install -g capture-website-cli
      - name: Create keys file
        if: steps.changes.outputs.web == 'true'
        run: cp ./src/backend/web/static/javascript/tba_js/tba_keys_template.js ./src/backend/web/static/javascript/tba_js/tba_keys.js
      - name: Start Containers
        if: steps.changes.outputs.web == 'true'
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build
      - name: Test Docker Startup
        if: steps.changes.outputs.web == 'true'
        run: python ./ops/test_docker_startup.py
      - name: Pre-pull companion import image
        if: steps.changes.outputs.web == 'true'
        run: docker pull gcr.io/tbatv-prod-hrd/tba-offseason-companion-import:latest
      - name: Test Ops Fullstack
        if: steps.changes.outputs.web == 'true'
        run: ./ops/test_ops.sh
      - name: Capture screenshots
        if: steps.changes.outputs.web == 'true'
        run: python ./ops/pr_screenshots/capture_screenshots.py
      - name: Upload screenshots artifact
        if: steps.changes.outputs.web == 'true'
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ci_screenshots
          path: ci_screenshots.pickle
