name: On pull request (py2)

on:
  pull_request:
    branches:
      - master

jobs:
  py2-test:
    name: "[py2] Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r travis_requirements.txt
      - name: Install GAE
        run: |
          wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.66.zip -nv
          unzip -q google_appengine_1.9.66.zip -d $HOME
          rm google_appengine_1.9.66.zip
          echo "PYTHONPATH=${HOME}/google_appengine" >> $GITHUB_ENV
      - name: Install Additional Libs
        run: paver install_libs
      - name: Run Tests
        run: paver test
  node-test:
    name: "[node] Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "8.x"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  make:
    name: "Make"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "8.x"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r travis_requirements.txt
      - name: Install GAE
        run: |
          wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.66.zip -nv
          unzip -q google_appengine_1.9.66.zip -d $HOME
          rm google_appengine_1.9.66.zip
          echo "PYTHONPATH=${HOME}/google_appengine" >> $GITHUB_ENV
      - name: Install Additional Libs
        run: paver install_libs
      - name: Install Node Dependencies
        run: |
          npm install
          npm install -g gulp-cli uglify-es uglifycss less request tslib
      - name: Create tba_keys.js file
        run: ./ops/create_tba_keys_js_file.sh
      - name: Make
        run: paver make
