# generated by datamodel-codegen:
#   filename:  nexus-api-v1.5.0.json

from typing import Any, Literal, NotRequired, TypedDict


class InspectionStatus(TypedDict):
    inspected: NotRequired[bool]
    status: NotRequired[
        Literal[
            "hold", "in-progress", "complete", "reinspection", "queued", "not-started"
        ]
    ]
    queuePosition: NotRequired[float | None]


class EventSummary(TypedDict):
    name: NotRequired[str]
    start: NotRequired[float]
    end: NotRequired[float]


type EventKey = str


type PitAddress = str


class Size(TypedDict):
    x: NotRequired[float]
    y: NotRequired[float]


class Position(TypedDict):
    x: NotRequired[float]
    y: NotRequired[float]


class MapElement(TypedDict):
    position: NotRequired[Position]
    size: NotRequired[Size]
    angle: NotRequired[float | None]


class Times(TypedDict):
    scheduledStartTime: NotRequired[float | None]
    estimatedQueueTime: NotRequired[float | None]
    estimatedOnDeckTime: NotRequired[float | None]
    estimatedOnFieldTime: NotRequired[float | None]
    estimatedStartTime: NotRequired[float | None]
    actualQueueTime: NotRequired[float | None]
    actualOnDeckTime: NotRequired[float | None]
    actualOnFieldTime: NotRequired[float | None]


type Teams = list[str | None]


class Announcement(TypedDict):
    id: NotRequired[str]
    announcement: NotRequired[str]
    postedTime: NotRequired[float]


class PartsRequest(TypedDict):
    id: NotRequired[str]
    parts: NotRequired[str]
    requestedByTeam: NotRequired[str]
    postedTime: NotRequired[float]


type PitAddresses = dict[str, PitAddress]


type InspectionStatuses = dict[str, InspectionStatus]


type Events = dict[str, EventSummary]


class Pits(MapElement):
    team: NotRequired[str | None]


class PitMap(TypedDict):
    size: NotRequired[Size]
    pits: NotRequired[dict[str, Pits]]
    areas: NotRequired[dict[str, Any] | None]
    labels: NotRequired[dict[str, Any] | None]
    arrows: NotRequired[dict[str, Any] | None]
    walls: NotRequired[dict[str, Any] | None]


class Match(TypedDict):
    label: NotRequired[str]
    status: NotRequired[Literal["Queuing soon", "Now queuing", "On deck", "On field"]]
    redTeams: NotRequired[Teams]
    blueTeams: NotRequired[Teams]
    times: NotRequired[Times]
    breakAfter: NotRequired[
        Literal["Break", "Lunch", "End of day", "Alliance selection", "Awards break"]
    ]
    replayOf: NotRequired[str | None]


class EventStatus(TypedDict):
    eventKey: NotRequired[EventKey]
    dataAsOfTime: NotRequired[float]
    nowQueuing: NotRequired[str | None]
    matches: NotRequired[list[Match]]
    announcements: NotRequired[list[Announcement]]
    partsRequests: NotRequired[list[PartsRequest]]


class MatchStatus(TypedDict):
    eventKey: NotRequired[EventKey]
    dataAsOfTime: NotRequired[float]
    match: NotRequired[Match]
